### PR TITLE
Vmctl : Provide TLS config options for vm native protocol

### PR DESCRIPTION
**Pull request by khushijain21**
Part of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5748

### CODE REVIEW

**Review by zekker6 — COMMENTED** [review]
Hello @khushijain21, thanks for the PR!
Please, see a small comment.

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Review by hagen1778 — APPROVED** [review]
Thank you!

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.100.0](https://docs.victoriametrics.com/changelog/).

**Pull request merged**
