### PR TITLE
fix: [vmalert] shutdown remote write follow batch size limit

### PR DESCRIPTION
**Pull request by jiekun**
### Describe Your Changes

During shutdown period of `vmalert`, remotewrite client retrieve all pending time series from buffer queue, compose them into **1** batch and execute remote write. 

This **final batch** may exceed the limit of `-remoteWrite.maxBatchSize`, and be **rejected** by the receiver (gateway, vmcluster or others). Example: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6025

Related codes: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/ac9c2a796fcabe39a476b5194d016d1bb482b943/app/vmalert/remotewrite/client.go#L153

---

#### Fixed
- BUGFIX: [vmalert](https://docs.victoriametrics.com/vmalert.html): respect `-remoteWrite.maxBatchSize` at shutdown period. See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6025).

---

### Checklist

The following checks are mandatory:

- [X] I have read the [Contributing Guidelines](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/CONTRIBUTING.md)
- [X] All commits are signed and include `Signed-off-by` line. Use `git commit -s` to include `Signed-off-by` your commits. See this [doc](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work) about how to sign your commits.
- [X] Tests are passing locally. Use `make test` to run all tests locally.
- [X] Linting is passing locally. Use `make check-all` to run all linters locally.
- [x] Include a link to the GitHub issue in the commit message, if issue exists.
- [x] Mention the change in the [Changelog](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/CHANGELOG.md). Explain what has changed and why. If there is a related issue or documentation change - link them as well.
- [ ] After your pull request is merged, please add a message to the issue with instructions for how to test the fix or try the feature you added. Here is an [example](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4048#issuecomment-1546453726)
- [X] Do not close the original issue before the change is released. Please note, in some cases Github can automatically close the issue once PR is merged. Re-open the issue in such case.
- [X] If the change somehow affects public interfaces (a new flag was added or updated, or some behavior has changed) - add the corresponding change to documentation.

Note: tests and linting for some (existing) codes are failed. I believe it's not relevent to this pr, and could be fixed in another pr.

### CODE REVIEW

**Comment by jiekun** [comment]
# PR Notes
- Unit tests added. But it's a littly bit  [flaky](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6021). Would like to have some input from maintainers.
- New module imported for monkey patch during unit testing. Also need some advice (or test guideline/standard).

ping @Haleygo (who has done something related to the integration testing) for help.

**Comment by Haleygo** [comment]
Thanks for the pull request!
>New module imported for monkey patch during unit testing. Need some advice (or test guideline/standard).

I don't think we need to introduce external package though. We can mock a remotewrite server like [faultyRWServer](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/remotewrite/client_test.go#L166) here, which will fail write request with particular order, and increase `-remoteWrite.retryMinInterval` to control retry attempts. The test result can be verified by checking server's acceptedRows like https://github.com/VictoriaMetrics/VictoriaMetrics/blob/ac9c2a796fcabe39a476b5194d016d1bb482b943/app/vmalert/remotewrite/client_test.go#L77-L80

**Comment by jiekun** [comment]
@Haleygo Thank you for the quick review!

I've altered it to a `batchCntRWServer` as suggested.

---
I would recommand to introduce a mock package (maybe in the future) tho, which may help reducing the complexity, and make unit test focus on a single unit.

Take this PR as an example, once we use a mocked HTTP server, the test actually covers both `run` method and many other lines in `flush` method and bla bla bla.

I think the maintainers have done a lot of work on testing, which is **quite impressive**! I believe that in the future, we could possibly add more tests but specific to certain types, such as unit tests + integration tests + and end-to-end tests (in different CI pipeline) (happy to contribute).

**Review by hagen1778 — APPROVED** [review]
LGTM!
Thanks for the contribution!

**Comment by hagen1778** [comment]
>  I believe that in the future, we could possibly add more tests but specific to certain types in a well-organized way, such as unit tests + integration tests + and end-to-end tests (in different CI pipeline) (happy to contribute).

We do have a bit of an issue with some our tests, as you mentioned [here](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6039#issuecomment-2026969464). We'd appreciate recommendations or contributions to improve the test suite!

**Comment by valyala** [comment]
@Haleygo , @hagen1778 , could you backport this fix to `lts-1.93-enterprise` and `lts-1.93-enterprise-cluster` branches in enterprise repository, since the fix cannot be back-ported cleanly without conflicts in the code?

**Comment by hagen1778** [comment]
I'll take a look, @Haleygo @valyala

**Comment by hagen1778** [comment]
@valyala it is done

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.100.0 release](https://docs.victoriametrics.com/changelog/).

**Comment by valyala** [comment]
This pull request has been included also in [v1.97.4 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.97.4).

**Pull request merged**
