### PR TITLE
copy button shows undefined

### LINKED ISSUE #6421: vmui: `copy row` button in Table view produces unexpected result
### Describe the bug

Value copied from the table view in vmui isn't what it is expected to be.

### To Reproduce

Go to [playground](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=100+-+%28avg+by+%28instance%29+%28rate%28node_cpu_seconds_total%7Bmode%3D%22idle%22%7D%5B1m%5D%29%29+*+100%29&g0.range_input=30m&g0.end_input=2024-06-05T10%3A54%3A48&g0.tab=1&g0.relative_time=last_30_minutes) and press on `Copy row` button next to one of the rows in response:
image

The value copied to the buffer will be the following:
> undefined {"instance":"10.142.0.85:9100"}

^ The copied value contains unexpected `undefined` word (metric name, I suppose) and doesn't have value.

### Version

:latest

### PR DESCRIPTION
**Pull request by yincongcyincong**
### Describe Your Changes
fix #6421
some aggregation func don't return \_\_name\_\_ value

### CODE REVIEW

**Review by Loori-R — APPROVED** [review]
LGTM!

**Comment by Loori-R** [comment]
@yincongcyincong, Would you mind adding a note to the changelog?

**Comment by yincongcyincong** [comment]
> @yincongcyincong, Would you mind adding a note to the changelog?

ok, i will adding a note

**Comment by Loori-R** [comment]
@hagen1778 can you merge the pull request?

**Review by hagen1778 — APPROVED** [review]
LGTM

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.102.0-rc2 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc2)

**Pull request merged**
