### PR TITLE
vmagent: support sharding by excluded labels

### PR DESCRIPTION
**Pull request by edma2**
**Problem**

To reduce cardinality, a common streaming aggregation policy is to "aggregate away" instance-level labels like pod name, host name, etc.

Example aggregation rule in vmagent:
```
- match: '{__name__=~".+_count"}'
  outputs: [total]
  without: [pod, host]
```

To horizontally scale streaming aggregation, you might want to deploy a separate hashing tier of vmagents that route to a separate aggregation tier. The hashing tier should shard by all labels _except_ the instance-level labels, to ensure the input metrics are routed correctly to the aggregator instance responsible for those labels (- instance labels).

Unless you always know the incoming labels ahead of time, this cannot be done in general fashion with `remoteWrite.shardByURL.labels`.

**Solution**

Add a new flag `remoteWrite.shardByURL.excludeLabels` to include all labels except the ones specified in the flag. This will support the use-case described above.

**Notes**

* Alternatively, we could introduce a boolean flag that reverses the behavior of `remoteWrite.shardByURL.labels` from "allowlist" to "denylist". I can go either way.
* If both `remoteWrite.shardByURL.excludeLabels` and `remoteWrite.shardByURL.labels` are passed, then `excludeLabels` takes precedence, which is arbitrary. I'm not sure if we should log a warning instead.

### CODE REVIEW

**Comment by edma2** [comment]
ping @valyala @Amper @AndrewChubatiuk

**Comment by edma2** [comment]
@hagen1778 Thank you for reviewing this PR!

> I need to scale the aggregation layer, then I must ensure that metrics of the same pod and host always end up on the same vmagent. 

This is not true from my understanding. You want to ignore the labels that are you are aggregating away. I'll try to provide a simple example.

Input metrics:
- http_request_total{pod: a, path: foo} 1
- http_request_total{pod: b, path: foo} 2

Expected output metric (without pod):
- http_request_total{path: foo} 3

Setup:
3 vmagents (with hostnames vmagent-1, vmagent-2, vmagent-3) with the aggregation config:

```
- match: '{__name__=~".+_count"}'
  outputs: [total]
  without: [pod, host] 
```

1 vmagent configured as:
```
--remoteWrite.shardByURL
--remoteWrite.url=vmagent-1
--remoteWrite.url=vmagent-2
--remoteWrite.url=vmagent-3
```

With `--remoteWrite.shardByURL.labels=pod,host`, then
`http_request_total{pod: a, path: foo} 1` could be sent to `vmagent-1`
`http_request_total{pod: b, path: foo} 2` could be sent to `vmagent-2`

Then both `vmagent-1` and `vmagent-2` would compute the aggregation and produce
`vmagent-1`: `http_request_total{path: foo} 1`
`vmagent-2`: `http_request_total{path: foo} 2`

which is not the current total and produce duplicate series errors in the downstream remote write backend.

The correct answer depends on _ignoring_ the `pod` label for hashing, so both metrics are routed to the same instance.

With `--remoteWrite.shardByURL.labels=path`, then
`http_request_total{pod: a, path: foo} 1` and `http_request_total{pod: b, path: foo} 2` are both guaranteed to be sent to `vmagent-1` because the inputs to the hash are equal: `hash(http_request_total{path: foo})`.

`vmagent-1` would produce `http_request_total{path: foo} 3` which is the expected result.

Now, in real life, we cannot know ahead of time all the labels (unlike this simple example where `path` is the only other label). So from a usability perspective, we need the ability to exclude labels for hashing.

**Comment by hagen1778** [comment]
Thanks for the thorough explanation @edma2 ! It all makes sense now!

> Alternatively, we could introduce a boolean flag that reverses the behavior of remoteWrite.shardByURL.labels from "allowlist" to "denylist". I can go either way.

It looks to me that `labels` and `excludeLabels` are mutually exclusive. At least I can't come with case when user needs them both to be set. So I'm thinking maybe the idea of inverting the `labels` flag via `-remoteWrite.shardByURL.inverseLabels` is what we need here. For example, ` --remoteWrite.shardByURL.labels=pod,host  --remoteWrite.shardByURL.inverseLabels` will do exactly what you described above and will solve the problem of notifiying the user about possible misconfig.

Would appreciate feedback from @AndrewChubatiuk as well.

**Comment by edma2** [comment]
@hagen1778 @AndrewChubatiuk thanks for the feedback, this new approach is simpler. I added a new flag `inverseLabels` flag. please review when you have a chance

**Review by hagen1778 — APPROVED** [review]
LGTM!
Thanks for the contribution!

**Comment by hagen1778** [comment]
@edma2 please see follow-up https://github.com/VictoriaMetrics/VictoriaMetrics/commit/b6bd9a97a3cf1da0da3e8df36dfcd2be343e21c4

**Comment by valyala** [comment]
FYI, the commit 3de865655199e89620a5fcfc2e46cb4c0dbef0fb substitutes `-remoteWrite.shardByURL.inverseLabels` command-line flag with `-remoteWrite.shardByURL.ignoreLabels`, which accepts the list of labels to ignore during [sharding among remote storage systems](https://docs.victoriametrics.com/vmagent/#sharding-among-remote-storages). This should simplify `vmagent` configuration, since `-remoteWrite.shardByURL.labels` now has a single meaning - the list of labels to take into account during sharding.

**Comment by valyala** [comment]
The `-remoteWrite.shardByURL.ignoreLabels` command-line flag is available in [vmagent](https://docs.victoriametrics.com/vmagent/) starting from [v1.100.0](https://docs.victoriametrics.com/changelog/).

**Pull request merged**
