### PR TITLE
clean unused code

### PR DESCRIPTION
**Pull request by helen-frank**

### CODE REVIEW

**Review by Haleygo — APPROVED** [review]
LGTM!
Thanks!

**Comment by Haleygo** [comment]
@helen-frank 
Please sign this commit https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5735/commits/e9c8c2dd33b1c8e982d027546e69880a9b97abc0.

**Comment by helen-frank** [comment]
> @helen-frank Please sign this commit [e9c8c2d](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/e9c8c2dd33b1c8e982d027546e69880a9b97abc0).

solved

**Comment by valyala** [comment]
@helen-frank , thanks for the cleanup!

**Pull request merged**
