### PR TITLE
lib/protoparser/opentelemetry: added exponential histograms support

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
### Describe Your Changes

added opentelemetry exponential histograms support

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by chenlujjj** [comment]
hi @hagen1778 , are there any existing problems of this PR to be solved ? Looking forward to it can be merged and get https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6343 resolved, thank you

**Comment by Shindek77** [comment]
Hello @hagen1778 when we can expect to merge this PR...we need this feature so that we can send ExponentailHistogram metrics

**Comment by hagen1778** [comment]
Before reviewing this PR, I made a test by running a go app instrumented with otel sdk and exponential histogram - see gist [here](https://gist.github.com/hagen1778/08aa3b4679654ae20d756010d5c6bc42).
This app collects exp histogram metrics and pushes it to otel collector. Otel collector then pushes it via otlp protocol to VM and Prom-3:
```
exporters:
  otlphttp/victoriametrics:
    compression: gzip
    encoding: proto
    endpoint: http://localhost:8428/opentelemetry
  otlphttp/prometheus:
    compression: gzip
    encoding: proto
    endpoint: http://localhost:9090/api/v1/otlp
  debug:

service:
#  extensions: [health_check]
  pipelines:
    metrics:
      exporters:
        - otlphttp/victoriametrics
        - otlphttp/prometheus
      receivers:
        - otlp
```

In Prometheus, I'm getting a historgram `request_duration_exp` and I can plot it:
image

In VM, I'm getting metrics `request.duration.exp_bucket`, `request.duration.exp_sum`, `request.duration.exp_count`. And when I'm trying to plot it I'm getting weird results:
image

The data seems sporadic, when it should have 5s resolution. So I'm leaving this comment here in order for @AndrewChubatiuk to try reproducing it in case if current PR has any subtle bugs that weren't discovered previously. Or point me to what I'm doing wrong.

**Comment by AndrewChubatiuk** [comment]
compared results to prometheus3.0 and now it's better

**Comment by hagen1778** [comment]
Thanks @AndrewChubatiuk! After the fix I can see the data is now matching between Prometheus 3.0 and VM. There are still differences, but mostly because how `rate` works differently between systems and that we're comparing Prometheus-native histograms and [VictoriaMetrics-native histograms](https://valyala.medium.com/improving-histogram-usability-for-prometheus-and-grafana-bc7e5df0e350):
image

**Review by hagen1778 — CHANGES_REQUESTED** [review]
@AndrewChubatiuk please add some tests to cover the new functionality. Besides this, I'm happy to merge it.

**Review by hagen1778 — APPROVED** [review]
Thank you!

**Comment by Shindek77** [comment]
Hello @hagen1778 , I hope this will work in VictoriaMetrics Cluster also...as I can in release it is given as                       `FEATURE: [vmagent](https://docs.victoriametrics.com/vmagent/) and [Single-node VictoriaMetrics](https://docs.victoriametrics.com/): add support of [exponential histograms](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#exponentialhistogram) ingested via [OpenTelemetry protocol for metrics](https://docs.victoriametrics.com/#sending-data-via-opentelemetry). Such histograms will be automatically converted to [VictoriaMetrics histogram format](https://valyala.medium.com/improving-histogram-usability-for-prometheus-and-grafana-bc7e5df0e350). See [this pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6354).`

**Comment by hagen1778** [comment]
Hello @Shindek77! Yes, it works on vminsert as well. Thanks for noticing - it was a typo in changelog. See update here https://github.com/VictoriaMetrics/VictoriaMetrics/commit/7e53324f5db00a0fed5668a1931362755cce4353

**Pull request merged**
