### PR TITLE
vmalert: fix sending alert messages

### PR DESCRIPTION
**Pull request by Haleygo**
1. fix wrong behavior of `-rule.resendDelay`, before it could prevent sending firing message when rule state is volatile.
Before the firing message won't be sent if this alert is resolved a short time before(message sending interval is smaller than resendDelay)
```
return a.LastSent.Add(resendDelay).Before(currentTime)
```
Adding another check here to cover this case.
```
if a.State == notifier.StateFiring && a.End.Before(a.LastSent) {
			return true
		}
```

2. fix `endsAt` field in messages that send to alertmanager, previously rules with small interval could never be firing
address https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5995

FYI, this fix breaks the specification described in [prometheus/compliance](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#payload-format-to-send-from-the-alert-generator)
>If the alert is firing, the value MUST be StartsAt + (4 * ResendDelay) or StartsAt + (4 * Group Interval), whichever is higher. StartsAt as seen in [“Executing an Alerting Rule”](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#executing-an-alerting-rule), ResendDelay is as seen in [“Sending Alerts to Alertmanager”](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#sending-alerts-to-alertmanager), and Group Interval is the interval of the parent <rule_group> of corresponding alerting rule.

But the purpose of `endsAt` is kept, alertmanager should expect another notification for the same alert in `4*groupInterval`, and send resolve message if not.

### CODE REVIEW

**Comment by Haleygo** [comment]
@hagen1778 PTAL)

**Review by hagen1778 — APPROVED** [review]
Thanks for the fix!

**Comment by hagen1778** [comment]
@Haleygo are these fixes needed for [LTS branches ](https://docs.victoriametrics.com/lts-releases/)?

**Comment by Haleygo** [comment]
> @Haleygo are these fixes needed for [LTS branches ](https://docs.victoriametrics.com/lts-releases/)?

@hagen1778  I don't think so, both of them appear under specific cases and I haven't saw related bug report from users, unless @f41gh7 has different opinion.

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.100.0 release](https://docs.victoriametrics.com/changelog/).

**Comment by valyala** [comment]
This pull request has been included in [v1.93.14 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.14).

**Comment by valyala** [comment]
This pull request has been also included in [v1.97.4 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.97.4).

**Pull request merged**
