### PR TITLE
vmui: show tracing in json view

### LINKED ISSUE #2814: vmui: add trace to json response if it's enable
show json trace too in response if it's enabled

### PR DESCRIPTION
**Pull request by michal-kralik**
Closes #2814

Shows query tracing in json view, if enabled.

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM! 

This PR added tracing to JSON tab 
Screenshot 2022-11-08 at 10 04 06

We have similar tracings on Graph and Table tabs. I think the UI should be consistent

**Comment by Loori-R** [comment]
In this case, you can remove code duplication. Display `TracingsView` before data view:

  ``` jsx
          {isTracingEnabled && <TracingsView
            traces={tracesState}
            onDeleteClick={handleTraceDelete}
          />}
          {graphData && period && (displayType === "chart") && <>
            <GraphView data={graphData} period={period} customStep={customStep} query={query} yaxis={yaxis}
              setYaxisLimits={setYaxisLimits} setPeriod={setPeriod}/>
          </>}
          {liveData && (displayType === "code") && <JsonView data={liveData}/>}
          {liveData && (displayType === "table") && <TableView data={liveData} displayColumns={displayColumns}/>}
```

**Comment by michal-kralik** [comment]
Makes sense, updated.

**Review by Loori-R — APPROVED** [review]
Thanks

**Comment by valyala** [comment]
@michal-kralik , thanks for the pull request!

**Comment by valyala** [comment]
FYI, this pull request has been integrated into [VictoriaMetrics v1.83.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)

**Pull request merged**
