### PR TITLE
app/vmagent: Add `remoteWrite.retryMinInterval` and `remoteWrite.retryMaxTime` flags

### LINKED ISSUE #5486: vmagent: remote-write retries "hammer" vminserts
### Is your question request related to a specific component?

vmagent vminsert

### Describe the question in detail

2023-12-19T07:43:29.157Z	warn	VictoriaMetrics/app/vmagent/remotewrite/client.go:385	couldn't send a block with size 70070 bytes to "1:https://xxxxx/insert/236/prometheus": Post "https://xxxx/insert/236/prometheus": context deadline exceeded (Client.Timeout exceeded while awaiting headers); re-sending the block in 2.000 seconds

There is a problem with vminsert configuration. Therefore, vmagent keeps failing to send data if there are too many vmagent nodes. This will lead to constant retries, which in turn increases the pressure on our SLB entrance and vminsert. So is there a way to control the retry interval of vmagent?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

### PR DESCRIPTION
**Pull request by yorik**
## Describe Your Changes

Add RemoteWrite Retry Controls

This PR introduces two new flags to the remote write functionality:
- remoteWrite.retryMinInterval
- remoteWrite.retryMaxTime
 
These flags provide finer control over the retry behavior for remoteWrite operations, allowing users to customize the minimum interval between retries and the maximum duration for retry attempts.

Fixes #5486.

## Checklist

- [x] The following checks are mandatory:

 My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Review by zekker6 — APPROVED** [review]
LGTM

**Comment by zekker6** [comment]
A friendly ping to take a look at this one @f41gh7 @hagen1778

**Comment by hagen1778** [comment]
Hello @yorik! Thanks for the pull request. My question is the same as for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5486 - What settings would you like to set via these flags?

From my understanding, vmagent retries logic doesn't require additional tweaking because vmagent does infinite amount of retries to deliver the data. Exposing these flags adds unnecessary complexity and doesn't provide benefit to the end user, as I don't understand which retry values will be preferable instead. Do you have a real case where you need to tweak it?

**Comment by yorik** [comment]
> Hello @yorik! Thanks for the pull request. My question is the same as for #5486 - What settings would you like to set via these flags?
> 
> From my understanding, vmagent retries logic doesn't require additional tweaking because vmagent does infinite amount of retries to deliver the data. Exposing these flags adds unnecessary complexity and doesn't provide benefit to the end user, as I don't understand which retry values will be preferable instead. Do you have a real case where you need to tweak it?

Hi @hagen1778, we had a case when too fast retries were causing unneeded load and alerts. So we want to relax them (I think we need first retry in 10s and max durating 5m).

Thanks!

**Review by hagen1778 — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
