### PR TITLE
Removed snap packages support

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
### Describe Your Changes

Removed snap packages support as it requires time for maintenance and it's not popular at all

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by hagen1778** [comment]
@tenmozes I'd appreciate it if you could provide some numbers to support this change. Thanks!

**Comment by AndrewChubatiuk** [comment]
there's also an issue about [flathub packages support](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2194). do we want to give it a try?

**Comment by tenmozes** [comment]
@hagen1778 

the current statistic (from snap site)
- single-node 274 active snap installations
- victoria logs - 7 
- vmagent - 27

**Comment by denisgolius** [comment]
From conversation with @tenmozes : 
we can remove snap support from VictoriaMetrics team, and I will continue to build and publish snap packages by myself. @hagen1778 @AndrewChubatiuk wdyt?

**Comment by hagen1778** [comment]
> From conversation with @tenmozes :
we can remove snap support from VictoriaMetrics team, and I will continue to build and publish snap packages by myself. @hagen1778 @AndrewChubatiuk wdyt?

Sounds good to me! Let me know if any assistance is needed.

**Review by hagen1778 — APPROVED** [review]

**Pull request merged**
