### PR TITLE
Refactor/all sw run use one function

### PR DESCRIPTION
**Pull request by xbsura**
make all sw run in one method, make code clean, and ready to do smarter sw restart

### CODE REVIEW

**Comment by xbsura** [comment]
because all sd sw runner code is same, so keep it in one function maybe is more clear, more important, we can do reload only changed sw in one place now

**Comment by valyala** [comment]
@xbsura , I pushed the commit 3b234d82e541395628951db1b70f0d5079ae9918 , which is based on the ideas from the https://github.com/VictoriaMetrics/VictoriaMetrics/pull/449 . The commit covers this PR too. So closing it.

**Comment by xbsura** [comment]
thanks! anyway, what we need is such a feature, not my code

but from the other hand, it maybe more ok if your team review my pr and tell me what I should do to make this feature accessable by this project, of cource, implement it yourself is faster than me because your team is more powerful and familiar with this project, emmm... but as a open source project, I think your team is happy to see more and more people come and make this project better together, but not just report issue, review then merge is a good start for this, and I reviewed the commit, no intrinsical different with my pr, just some lock, chan struct, key sign, there exists some different, with good review, I think these pr can become better

At last, thanks for this commit, I checked it, works in our env, and some metrics/lock is better than my code

I, and my team will continue pay attention to this project and use it, now we have used vmagent/vmalert/vm storage replace Prometheus running online, the metrics write per second is more than 1Billion now, we are happy to make this project better

one more time, thanks for your commit!

**Comment by hagen1778** [comment]
Hi @xbsura! Your setup and load sounds super cool! We'd really appreciate if you can share more details for VM [case studies](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/CaseStudies), so other people can learn from that. It is totally ok if you prefer to not do this of course.

**Pull request closed without merging**
