### PR TITLE
vmauth: support for reading remote auth config file

### PR DESCRIPTION
**Pull request by TFM93**
With this patch, it is possible to read the vmauth configuration file from a remote HTTP/HTTPS server.
Let me know if this feature can be added to VictoriaMetrics.

### CODE REVIEW

**Comment by TFM93** [comment]
i made some changes to follow lint and errcheck, hopefully it's ok

**Review by valyala — COMMENTED** [review]
LGTM!

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@TFM93 , thanks for the pull request! It will be included in the next release.

**Comment by TFM93** [comment]
thanks :) 
for the future, maibe i should open a feature request or something?

**Comment by valyala** [comment]
While it is better to open a feature request and then submitting the linked pull request, it is still OK to just sending a pull request without opening a feature request ;)

**Comment by valyala** [comment]
FYI, this pull request has been included in [vmauth v1.71.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Pull request merged**
