### PR TITLE
fix: update docs for VictoriaLogs logstash data ingestion

### PR DESCRIPTION
**Pull request by TheMeier**
### Describe Your Changes

the logstash data ingestion does not work with the elasticsearch output plugin, but it works with the opensearch output plugin.
Also manage_template should be disabled in logstash.

see #4750

### Checklist

The following checks are **mandatory**:

- [x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by zekker6** [comment]
Hello @TheMeier, could you elaborate on "logstash data ingestion does not work with the elasticsearch output plugin"?
Did you see any errors in logstash or VIctoriaLogs' logs when trying it with an elasticsearch output?

A recent version of VictoriaLogs (such as [v0.28.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.28.0-victorialogs)) has support of endpoints required by logstash and should work with both output plugins. If it does not work as expected it would be better to fix this incompatibility in order to make it easier to use VictoriaLogs without installing an additional output plugin for logstash.

**Comment by TheMeier** [comment]
I have already removed my test setup, so I can't guarantee for it. But I am quite sure it was just as described in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4750

**Comment by zekker6** [comment]
Could you check a version of VictoriaLogs which you are using?

**Comment by TheMeier** [comment]
logstash error:
```
 [2024-07-31T13:49:56,589][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://victoria-logs-single-server.posas-applog-live.svc.cluster.local:9428/insert/elasticsearch/"]}
 [2024-07-31T13:49:56,602][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://victoria-logs-single-server.posas-applog-live.svc.cluster.local:9428/insert/elasticsearch/?_time_field=@timestamp&_stream_fields=host.name,process.name&_msg_field=message]}}
 [2024-07-31T13:49:56,616][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://victoria-logs-single-server.posas-applog-live.svc.cluster.local:9428/insert/elasticsearch/?_time_field=@timestamp&_stream_fields=host.name,process.name&_msg_field=message"}
 [2024-07-31T13:49:57,728][ERROR][logstash.outputs.elasticsearch][main][811d0212831e2fd3faa6eabcbe639c8b4f3ee9a991d48bef542b49ee2e7f1ba7] Elasticsearch setup did not complete normally, please review previously logged errors {:message=>"Got response code '400' contacting Elasticsearch at URL 'http://victoria-logs-single-server.posas-applog-live.svc.cluster.local:9428/insert/elasticsearch/logstash?_time_field=@timestamp&_stream_fields=host.name,process.name&_msg_field=message'", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError}
```

victorialogs error:
```
 {"ts":"2024-07-31T13:48:37.911Z","level":"warn","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:432","msg":"remoteAddr: \"100.70.23.166:55728\"; requestURI: /insert/elasticsearch/logstash?_time_field=@timestamp&_stream_fields=host.name,process.name&_msg_field=message; unsupported path requested: \"/insert/elasticsearch/logstash\""}
```

just by switching from opensearch to elastichsearch in the logstash output config.

**Comment by zekker6** [comment]
@TheMeier Thank you for the details! May I ask which version of Logstash are you using?

Based on the logs it seems like Logstash added `/logstash` to the URL which might cause an issue. It would be great to either support this at VictoriaLogs or add a documentation mentioning that starting from some version Logstash plugin does that and it is not supported.

**Comment by TheMeier** [comment]
I am using an old version of logstash `7.17.19`  for $reasons..
my config is as follows:

```
  output {
        opensearch {
         hosts => ["http://victoria-logs-single-server.posas-applog-live.svc.cluster.local:9428/insert/elasticsearch/"]
         parameters => {
             "_msg_field" => "message"
             "_time_field" => "@timestamp"
             "_stream_fields" => "host.name,process.name"
         }
         manage_template => false
        }
  }
```

**Comment by zekker6** [comment]
@TheMeier Thank you for the details! I've been able to reproduce this and created a PR to fix this incompatibility - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6742

I would suggest to close this PR in favor of fixing compatibility on VictoriaLogs side, so that it will be easier to use VictoriaLogs without a need to install OpenSearch plugin and updating the configuration. @hagen1778 @valyala Wdyt?

**Comment by TheMeier** [comment]
great. thank you @zekker6

**Pull request closed without merging**
