### PR TITLE
lib/protoparser: stop read when callback error

### PR DESCRIPTION
**Pull request by faceair**

### CODE REVIEW

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@faceair . thanks for the contribution!

**Comment by faceair** [comment]
Hi @valyala 
ref: https://github.com/VictoriaMetrics/VictoriaMetrics/commit/e028ad241ac972ee1c5223a6249398e9357fe237
I'm curious why you chose sync.Mutex instead of sync.RWMutex ?  Wouldn't sync.RWMutex perform better ?

**Comment by valyala** [comment]
> I'm curious why you chose sync.Mutex instead of sync.RWMutex ? Wouldn't sync.RWMutex perform better ?

Nice question :) The code can benefit from `sync.RWMutex` compared to `sync.Mutex` if the following conditions are met:

1) If the app needs to read the data protected by the mutex;
2) If the app spends much more time reading the protected data compared to updating the protected data.

While the first condition is true for the code in the pull request, the second condition is false. That's why there is little sense using `sync.RWMutex` instead of `sync.Mutex` in this code, since it doesn't give any measurable performance improvements. On the other hand, it makes the code a little bit complicated compared to `sync.Mutex` usage.

**Comment by faceair** [comment]
Thanks a lot, I understand 👍

**Pull request merged**
