### PR TITLE
feature: Add multitenant for vmagent

### PR DESCRIPTION
**Pull request by omarghader**
This pull request adds the feature of handling multiple tenants by `vmagent`.
Example : If vmagent has received a write request on the accountID 2, It will remotewrite on the same tenant.

Main changes:
- Multiple tenant HTTP handling
- Dynamic creation of unique disk queue for each tenant
- Multiple tenant remotewrite using the tenant of input

### CODE REVIEW

**Comment by syepes** [comment]
Created a PR to also support the multitenantURL in the chart https://github.com/VictoriaMetrics/helm-charts/pull/182

**Review by valyala — APPROVED** [review]
LGTM

**Comment by valyala** [comment]
@omarghader , thanks for the contribution!

**Comment by syepes** [comment]
Thanks for the merge, hope we can continue to help

**Comment by valyala** [comment]
See also the follow-up commit at b877538622c07106b24e3946789088116e026754

**Comment by valyala** [comment]
FYI, the pull request has been merged into vmagent [v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Pull request merged**
