### PR TITLE
vmalert-tool: add `-external.label` and `-external.url` command-line …

### PR DESCRIPTION
**Pull request by Haleygo**
…flags to perform the same as vmalert

address https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6735

### CODE REVIEW

**Comment by Haleygo** [comment]
> Hey @Haleygo! Does it breaks compatibility with promtool?

Yes, it does.
prometheus specifies `external_labels` option differently from vmalert, it's included in the [configuration file](https://prometheus.io/docs/prometheus/latest/configuration/configuration/). If there are multiple unit test files, `external_labels` must be specified in each of them.
Since vmalert uses command-line flag `-external.label`, it makes sense to me to align this behavior with vmalert, which also fixes the template problem.

**Comment by hagen1778** [comment]
> Yes, it does.

I find it concerning due to the following reasons:
1. I assume most of users migrate from promtool to vmalert-tool. And they would expect for test cases to work similarly.
2. If some settings arent' working similarly, vmalert-tool should notify user about this compatibility issue and guidance what has to be done.

**Comment by Haleygo** [comment]
>I assume most of users migrate from promtool to vmalert-tool. 

My thought is: users use vmalert-tool after they migrate from prometheus to vmalert, they need validation for MetricsQL, so they find vmalert-tool. And in this case, they already use `-external.label` flag on vmalert.

>If some settings arent' working similarly, vmalert-tool should notify user about this compatibility issue and guidance what has to be done.

ofc, I added some deprecated statement in the doc, and a warning log [here](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6766/commits/a921fe28d2de49b348687e3b1cb09106ec5ab624).

**Comment by hagen1778** [comment]
Hm, linter gets killed for some reason and CI fails because of this

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/commit/220b1659b68db0704249ddae3fd57c1087e1e447 and https://github.com/VictoriaMetrics/VictoriaMetrics/commit/febba3971b74d4d42141b282230cb715c6ecbbe1 helped.

**Review by hagen1778 — APPROVED** [review]
Thanks!

**Pull request merged**
