### PR TITLE
lib/handshake: check for deadline in Read and Write methods

### PR DESCRIPTION
**Pull request by hagen1778**
The buffered connection could have exceeded the underlying connection deadline during reading or writing to an internal buffer. With this change, buffered connection struct additionally checks for a deadline in Read/Write methods.

-------------

Substitutes https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5285

### CODE REVIEW

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@hagen1778 , thanks for the fix!

**Comment by valyala** [comment]
See also the follow-up commit ef80a89a2419d4cd8efbb87d46619306fe0766a3 , which adds `SetReadDeadline()` and `SetWriteDeadline()` methods to `BufferedConn`, since these methods are also used in some parts of VictoriaMetrics codebase.

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.95.1 release](https://docs.victoriametrics.com/CHANGELOG.html)

**Comment by Hello-World-0X** [comment]
> FYI, this pull request has been included in [v1.95.1 release](https://docs.victoriametrics.com/CHANGELOG.html)

@valyala @hagen1778  Excuse me， may i ask  why these three function   `SetDeadline(), SetReadDeadline(),SetWriteDeadline()` of the interface `net.Conn` in `BufferedConn` is not enough for checking Read or Write Deadline?

**Comment by Hello-World-0X** [comment]
> > FYI, this pull request has been included in [v1.95.1 release](https://docs.victoriametrics.com/CHANGELOG.html)
> > @valyala @hagen1778  Excuse me， may i ask  why these three function   `SetDeadline(), SetReadDeadline(),SetWriteDeadline()` of the interface `net.Conn` in `BufferedConn` is not enough for checking Read or Write Deadline?
The deadline wil be a past time when i get conn from connpool(because of the concurrency limit), and the past deadline was set as a deadline time on the net.Conn will lead the conn's Read and Write always block?
is it right?

**Pull request merged**
