### PR TITLE
vmui/logs: add markdown support

### PR DESCRIPTION
**Pull request by Loori-R**
### Describe Your Changes

Add support for markdown format and emoji for the `_msg` field in the "Group" view.
Add markdown rendering toggle. Disabled by default. Value is stored in `localStorage`.

<table>
  <tr>
    <td>before</td>
    <td>
      
    </td>
  </tr>
  <tr>
    <td>after</td>
    <td>
      
    </td>
  </tr>
</table>

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Comment by zekker6** [comment]
Do I understand it correctly that current implementation enables markdown rendering by default and there is no way to disable it?
I'm afraid that there will definetly be use-cases when this will render markdown at places where it was just using `*`, `_` or other special characters in markdown, so it would be great to have a toggle to disable this.

**Comment by Loori-R** [comment]
@zekker6, good idea, I'll add a switch.
Should we disable it by default?

**Comment by zekker6** [comment]
> @zekker6, good idea, I'll add a switch. Should we disable it by default?

From my experience, it's better to disable this by default as most logs do not contain markdown at all.

It would be great if we could enable this by default for the play environment thought (or have some kind of automatic detection logic in place).

**Comment by hagen1778** [comment]
@Loori-R could you please resolve conflicts in this PR?

**Comment by Loori-R** [comment]
@hagen1778 Resolved conflicts

**Review by hagen1778 — APPROVED** [review]
LGTM

**Comment by valyala** [comment]
FYI, this pull request has been included in [v0.19.0-victorialogs](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.19.0-victorialogs).

**Pull request merged**
