### PR TITLE
RPM packaging

### PR DESCRIPTION
**Pull request by kmansoft**
Package as RPM right from the makefile

Uses same .service file as DEB packaging.

### CODE REVIEW

**Comment by kmansoft** [comment]
CC: @patsevanton

**Comment by kmansoft** [comment]
@valyala  you may want to delete ./package/rpm/* which is @patsevanton 's scripts and not needed by my new packaging script. If you want to clean things up.

**Comment by valyala** [comment]
> @valyala you may want to delete ./package/rpm/* which is @patsevanton 's scripts and not needed by my new packaging script. If you want to clean things up.

Your RPM packaging should be backwards-compatible with @patsevanton 's scripts, since they are in active use for the last few months. It is possible to do this? @patsevanton , could you help @kmansoft in doing this? Currently `*.service` files in `package` and `package/rpm` have the following differences:

```
diff -u package/victoria-metrics.service package/rpm/victoriametrics.service 
--- package/victoria-metrics.service	2019-07-26 13:19:00.431388549 +0300
+++ package/rpm/victoriametrics.service	2019-07-25 22:26:53.951413949 +0300
@@ -1,15 +1,15 @@
 [Unit]
-Description=VictoriaMetrics is a fast, cost-effective and scalable time series database.
+Description=High-performance, cost-effective and scalable time series database, long-term remote storage for Prometheus
+After=network.target
 
 [Service]
 Type=simple
 StartLimitBurst=5
 StartLimitInterval=0
-Restart=on-failure
-RestartSec=1
-ExecStart=/usr/sbin/victoria-metrics -storageDataPath /var/lib/victoria-metrics -retentionPeriod 12
+Restart=on-abort
+ExecStart=/usr/local/bin/victoriametrics -storageDataPath=/var/lib/victoria-metrics-data start
 ExecStop=/bin/kill -s SIGTERM $MAINPID
-LimitNOFILE=32000
+LimitNOFILE=65536
 LimitNPROC=32000
```

**Comment by patsevanton** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/125

**Pull request merged**
