### PR TITLE
Simplify queries to OpenTSDB for migration

### PR DESCRIPTION
**Pull request by johnseekins**
1. Use the /api/query interface, rather than /api/query/exp. It was harder to understand what was happening before.
2. /api/query requests actually show up in OpenTSDB's query stats correctly, so that's a nice benefit
3. The code is now _far_ simpler.
4. Some of the defaults were set a bit too low. Bump those up.
5. Some of the offset calculations were wrong. Fix those, too.

Signed-off-by: John Seekins <jseekins@datto.com>

### CODE REVIEW

**Comment by johnseekins** [comment]
I'm a little lost on how to properly add unit tests to the changes I made. But this does appear to work in local tests...

**Comment by johnseekins** [comment]
@hagen1778 @f41gh7 I think y'all do most vmctl work... Does this look reasonable to you? It _works_, although I'm not entirely sure how to build out any unit tests that may be needed.

**Comment by valyala** [comment]
@hagen1778 , @f41gh7 , could you take a look at this pull request?

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
I suppose, unit tests useful for parsing response functions.

 For example function: 
` GetData(series Meta, rt RetentionMeta, start int64, end int64) (Metric, error)`

can be splitted into 2 functions, first makes http request with given params, returns []byte. Second functions parses this response and modifies data into needed format.

 Second function can be tested with unit tests.

**Comment by f41gh7** [comment]
Thanks for your contribution!

**Comment by valyala** [comment]
FYI, this pull request has been merged into [vmctl v1.70.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Pull request merged**
