### PR TITLE
git cherry-pick f35d27aa2beebde23e152dab1aeb40d708b8d496^..86f1459ca65e72416321d86db75bdc0a744779b3

### PR DESCRIPTION
**Pull request by f41gh7**

### CODE REVIEW

**Review by tenmozes — APPROVED** [review]

**Review by hagen1778 — COMMENTED** [review]
Linter fails...
I believe app/vmctl/vm_native_test.go was never meant to be cherry picked to branches other than master

**Comment by f41gh7** [comment]
> Linter fails... I believe app/vmctl/vm_native_test.go was never meant to be cherry picked to branches other than master

Any reason for that?

**Comment by hagen1778** [comment]
> Any reason for that?

No. It was initially skipped by @valyala a few releases before.

**Comment by f41gh7** [comment]
> No. It was initially skipped by @valyala a few releases before.

I suppose, he forgot to pick it. It may block future cluster releases, since it's not possible to lint cluster branch after cherry-pick.

**Comment by f41gh7** [comment]
It must be solved by the person, who'll make future release.

**Pull request closed without merging**
