### PR TITLE
moved cluster dashboard to master

### PR DESCRIPTION
**Pull request by k1rk**
moved cluster dashboard to master, to have all dashboards in one place

note: i haven't found any references to this dashboard to update

### CODE REVIEW

**Comment by hagen1778** [comment]
There is a reference here https://docs.victoriametrics.com/PerTenantStatistic.html#visualization
It would be better to point it to https://grafana.com/grafana/dashboards/11176-victoriametrics-cluster/

**Comment by k1rk** [comment]
@hagen1778 , i missed clusterbytenant.json, let me update it

**Comment by k1rk** [comment]
@hagen1778 updated, but pointed it to https://grafana.com/grafana/dashboards/16399-victoriametrics-cluster-per-tenant-statistic/

**Review by hagen1778 — APPROVED** [review]
Thank you!

**Pull request merged**
