### PR TITLE
Fix inconsistent error handling in Storage.AddRows()

### PR DESCRIPTION
**Pull request by rtm0**
### Describe Your Changes

`Storage.AddRows()` returns an error only in one case: when `Storage.updatePerDateData()` fails to unmarshal a `metricNameRaw`. But the same error is treated as a warning when it happens inside `Storage.add()` or returned by `Storage.prefillNextIndexDB()`.

This commit fixes this inconsistency by treating the error returned by `Storage.updatePerDateData()` as a warning as well. As a result `Storage.add()` does not need a return value anymore and so doesn't `Storage.AddRows()`.

Additionally, this commit adds a unit test that checks all cases that result in a row not being added to the storage.

Please note that this PR does not attempt to fix the correctness of the `TotalRowsAdded` counter metric in `Storage.AddRows()`. After fixing the error handling its value may be inaccurate but neither was it before this fix. A separate PR will be sent to fix this metric and also add more metrics to provide more visibility into what went wrong during adding records to the storage.

### Checklist

The following checks are **mandatory**:

- [ x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Review by hagen1778 — APPROVED** [review]
LGTM

**Comment by rtm0** [comment]
Fixed a few remarks based on conversation with @valyala.

Also, I am going to prepare another PR for the cluster branch because it looks like this change cannot be cherrypicked into the cluster branch without conflicts. Please wait until I send this PR. I will mention it here. Then both can be reviewed and safely merged without further cherrypicking. Thanks!

**Comment by rtm0** [comment]
Added a cluster version at #6635. Please take a look.

**Comment by rtm0** [comment]
Updated changelog.

**Pull request merged**
