### PR TITLE
vmui: query report

### PR DESCRIPTION
**Pull request by Loori-R**
Pull Request Adds Feature to Save and View Query Execution Results

<hr/>

**How to Generate a Report:**
1. Execute a query.
2. Click on the `Report query` icon.
3. Optionally, change the file name, enter a comment, and enable/disable tracing.
4. Click the `Generate Report` button.

<details><summary>Screenshots generate a report</summary>

</details>

<hr/>

**How to Open a Report:**
1. Go to the `Query Analyzer` page (`Tools` -> `Query Analyzer`).
2. Enter/upload a JSON containing the server response or upload the report file.
3. To view the comment and additional information about the report, click the `Show Report Info` button.

<details><summary>Screenshots open a report</summary>

</details>

### CODE REVIEW

**Review by zekker6 — COMMENTED** [review]
Tested this, and it looks good to me in general, thanks @Loori-R!

Found one small bug while testing:


This happened after exporting query which did not return any samples(it was an empty instance).

**Review by hagen1778 — COMMENTED** [review]
A few minor things:
- [x] `Include trace query` should be `Include query trace`
- [x] Disabling `Include trace query` doesn't work for me - I'm still getting the trace attached to report
- [x] Would be nice to show time range and step for loaded report, to see exactly how the query was executed. So far, this info is unavailable if trace wasn't attached
- [ ] `Report query` IMHO should be `Export query`. The popup should contain a small description what it means and how exported file can be used.

A more general question - can we merge Trace and Query analyzer pages in one page `Query analyzer` that will be able to display:
* trace
* query
* query+trace
?

**Comment by Loori-R** [comment]
> A more general question - can we merge Trace and Query analyzer pages in one page Query analyzer that will be able to display:
> 
> trace
> query
> query+trace

@hagen1778, Yes, we can merge the two pages and display only the information that is available in the JSON. I would like to do this as a separate PR, if you don't mind.

**Comment by Loori-R** [comment]
@hagen1778, @zekker6 
What do you think about adding the ability to display multiple reports?
I think it could be useful if there is a need to compare several reports.
The uploaded reports could be divided into tabs.

- It might be useful to have the option to display several tabs on one screen for comparison.
- Or a separate button for merging multiple data sets to display on a single graph.
Something like this:

image

**Comment by zekker6** [comment]
>  What do you think about adding the ability to display multiple reports?

@Loori-R I like the idea, seems useful to me. From my point of view displaying query results on the same chart would make it easier to compare the results.

**Comment by hagen1778** [comment]
> What do you think about adding the ability to display multiple reports?

I don't think this is a frequent case when one need to compare two queries on the same time range. 
I'd suggest keeping this idea in mind and add it afterwards, if we'll see we actually need it.

**Review by dmitryk-dk — APPROVED** [review]
From code perspective it looks good to me!

**Comment by valyala** [comment]
@Loori-R , thanks for the pull request!

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html).

**Pull request merged**
