### PR TITLE
lib/bytesutil: smooth buffer growth rate

### PR DESCRIPTION
**Pull request by hagen1778**
Before, buffer growth was always x2 of its size, which could lead to excessive memory usage when processing big amount of data.
For example, scraping a target with hundreds of MBs in response could result into hih memory spikes in vmagent because buffer has to double its size to fit the response. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6759

The change smoothes out the growth rate, trading higher allocation rate for lower mem usage at certain conditions.

### Describe Your Changes

Please provide a brief description of the changes you made. Be as specific as possible to help others understand the purpose and impact of your modifications.

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by hagen1778** [comment]
The change was temporary deployed to https://play-grafana.victoriametrics.com/d/G7Z9GzMGz_vm/victoriametrics-vmagent-vm?orgId=1&var-ds=P38648FE0F8C5BEA2&var-job=monitoring%2Fprometheus-benchmark-vmagent&var-instance=All&var-url=All
image

**Comment by hagen1778** [comment]
Related public discussion https://victoriametrics.slack.com/archives/CGZF1H6L9/p1721983962945709

**Review by AndrewChubatiuk — APPROVED** [review]
LGTM

**Review by f41gh7 — APPROVED** [review]
LGTM

**Review by valyala — APPROVED** [review]

**Pull request merged**
