### PR TITLE
fix: fix slice init length

### PR DESCRIPTION
**Pull request by rusttech**
### Describe Your Changes

The intention here should be to initialize a slice with a capacity of   len(data.Tags)   rather than initializing the length of this slice.

### Checklist

The following checks are **mandatory**:

- [x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by jiekun** [comment]
This looks like a valid fix to me.

@rusttech Just curious, may I ask what issue you encountered caused by this bug?

**Comment by rusttech** [comment]
> This looks like a valid fix to me.
> 
> @rusttech Just curious, may I ask what issue you encountered caused by this bug?

I found this problem through local static analysis. I have a friend who is trying to add an analyzer to go vet, and he needs a lot of evidence. I assisted him with his work

**Review by jiekun — APPROVED** [review]

**Comment by rusttech** [comment]
If anything need I to do, please feel free to tell me.

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
@rusttech  could you please update changelog with bugfix mention?

**Comment by rusttech** [comment]
> @rusttech could you please update changelog with bugfix mention?

Of course. 

Updated. Please review again.

**Comment by f41gh7** [comment]
Thanks for contribution!

**Pull request merged**
