### PR TITLE
vmui: heatmap

### PR DESCRIPTION
**Pull request by Loori-R**
**Added heatmap feature to vmui.**
 - `vmui` can now automatically determine if the requested time series match a single histogram segment.
- Replaced line graph with heatmap for histogram segments.
- #3384 

demo heatmap

### CODE REVIEW

**Comment by valyala** [comment]
The `Prometheus histogram` buckets are cumulative, e.g. buckets with higher `le` values include hits for all the buckets with lower `le` values. So the histogram visualization built on top of `le` buckets always has more intense colors at its' top. Such a visualization is hard to interpret by humans. On the other hand, `VictoriaMetrics histogram` buckets aren't cumulative, e.g. every `vmrange` bucket contains only hits, which got into this bucket. So the visualization of such histogram is easy to interpret by humans - buckets with more intense colors got more hits, while buckets with less intense colors get less hits.

It would be great if `vmui` could convert Prometheus histogram buckets with `le` labels into VictoriaMetrics histogram buckets before the visualization. The following pseudo-algorithm should be used:

```
promBuckets = sort_buckets_by_le(promBuckets)
vmBuckets = []
bPrev = {le: 0, value: 0}
for b in buckets:
  vmrange = b.le + ".." + bPev.le
  vmBuckets[vmrange] = b.value - bPrev.value
```

@Loori-R , could you update the pull request according to this feature?

**Comment by Loori-R** [comment]
Updated:
- Increase step when rendering heatmap
- Add data normalization to the heatmap

<br/>
@valyala, please let me know if there is anything that needs to be corrected. Once all changes have been made, I would like to perform a code refactoring.

**Review by dmitryk-dk — APPROVED** [review]

**Comment by valyala** [comment]
> please let me know if there is anything that needs to be corrected. Once all changes have been made, I would like to perform a code refactoring.

@Loori-R , everything looks good. Could you fix the merge conflicts and refactor the code if needed?

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Loori-R , thanks for the great feature!

**Pull request merged**
