### PR TITLE
Vmalert extra params

### PR DESCRIPTION
**Pull request by hagen1778**

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Btw, can you update README with new flag description?

**Comment by hagen1778** [comment]
> Btw, can you update README with new flag description?

There is no new flag. Extra params are only allowed internally so far.

**Comment by f41gh7** [comment]
> > Btw, can you update README with new flag description?
> 
> There is no new flag. Extra params are only allowed internally so far.

oops, sry!

**Pull request merged**
