### PR TITLE
app/vmselect: fix alignment panic (sigbus)

### PR DESCRIPTION
**Pull request by oliverpool**
I have been running VictoriaMetrics on a raspberry pi 1st gen, using [gokrazy](https://gokrazy.org/).

I have been quite happy with the result, however I noticed that VictoriaMetrics regularly crashed with a SIGBUS:
```unexpected fault address 0x0
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0x0 pc=0x6b2168]

goroutine 111 [running]:
runtime.throw({0xa8fb4f, 0x5})
	/usr/lib/go/src/runtime/panic.go:1047 +0x4c fp=0x2d8ec78 sp=0x2d8ec64 pc=0x4dcc0
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:834 +0xa8 fp=0x2d8ec94 sp=0x2d8ec78 pc=0x67ccc
math.IsNaN(...)
	/usr/lib/go/src/math/bits.go:39
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.removeEmptySeries(...)
	/home/olivier/go/pkg/mod/github.com/!victoria!metrics/!victoria!metrics@v1.88.1/app/vmselect/promql/exec.go:180
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.newBinaryOpFunc.func1(0x237af20)
	/home/olivier/go/pkg/mod/github.com/!victoria!metrics/!victoria!metrics@v1.88.1/app/vmselect/promql/binary_op.go:95 +0x7e8 fp=0x2d8ed9c sp=0x2d8ec98 pc=0x6b2168
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalBinaryOp(0x0, 0x2998280, 0x206f5e0)
	/home/olivier/go/pkg/mod/github.com/!victoria!metrics/!victoria!metrics@v1.88.1/app/vmselect/promql/eval.go:410 +0x344 fp=0x2d8ee1c sp=0x2d8ed9c pc=0x6b8234
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExprInternal(0x0, 0x2998280, {0xd74640, 0x206f5e0})
	/home/olivier/go/pkg/mod/github.com/!victoria!metrics/!victoria!metrics@v1.88.1/app/vmselect/promql/eval.go:290 +0x314 fp=0x2d8eefc sp=0x2d8ee1c pc=0x6b6b5c
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExpr(0x0, 0x2998280, {0xd74640, 0x206f5e0})
...
```

Panicking line:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/95e11734233d11972581496e40c3b4f9df69bfd4/app/vmselect/promql/exec.go#L180

After spending a lot a time trying to debug the issue, I added some good old Printf statements, to check the address of `ts.Values`:
```go
fmt.Fprintf(os.Stderr, "len=%d p=%p al=%d\n", len(ts.Values), &ts.Values[0], unsafe.Alignof(&ts.Values[0]))
```
I get before the SIGBUS
```
len=1457 p=0x2eb4dbb al=4
```
As you can see, the pointer address of the slice seems to be `0x2eb4dbb`, which is not 4-bytes aligned, as a `float64` should be.

I almost opened an issue in the go tracker, but then looked for `unsafe` usage in the codebase and found the `byteSliceToFloat64` function.

This function does not check alignment when converting to float64, hence my float64 was to properly aligned, triggering a sigbus!

This PR checks the alignment before doing the conversion.
With this fix, I haven't been able to reproduce the SIGBUS.

Before marking this PR as "ready to merge":
- [ ] I would love to have some feedback regarding the bug and the proposed fix
- [x] add some unit tests, to prevent future regressions
- [x] fix `byteSliceToInt64` as well

### CODE REVIEW

**Comment by oliverpool** [comment]
This appears to have been previously reported in #1147 by @haerk

**Comment by haerk** [comment]
gsdgs56d4gsd5gsなどがミドっぱくラバニラサダウのブはとてもおいしそうなりんか

**Comment by oliverpool** [comment]
I have added proper tests (for float64 and int64).

[Apparently](https://stackoverflow.com/a/20101656) this alignment is not required on x84:
> On the x86 in particular, aligning scalars to their size makes for more efficient access, but misaligned accesses still work correctly, though a little more slowly.

Currently my code always make a new allocation when alignment is wrong.
It could be discussed to adjust the alignment only when needed (ARM7) to reduce the allocation (but as noted, this could slow down x86).

**Review by valyala — COMMENTED** [review]
The patch looks good!

The `bytesSliceToInt64()` and `byteSliceToFloat64()` functions are used in a single localized place. So, probably, it would be better from performance PoV to try to make sure that byte slices passed to these functions are always aligned to 8 bytes.

**Comment by oliverpool** [comment]
I researched a bit more about performance and apparently misaligned accesses are not a problem with modern CPUs: https://lemire.me/blog/2012/05/31/data-alignment-for-speed-myth-or-reality/ (1st comment is interesting).

Maybe I could refactor it with constraint flags, to only align on ARM.

Since the byte slice is extracted from a larger src slice (with stuff before), I don’t think it is possible to guarantee alignment of the float64 by simply aligning src (or did I miss something?)

**Comment by oliverpool** [comment]
@valyala I split my patch into mutliple files, so that the execution path is unchanged for most platforms (only ARM gets a special treatment - at least for now).

I also added a build tag to force the re-alignment `vm_ensure_xxx64_alignment` if needed.
If you run `go test -v -tags "vm_ensure_xxx64_alignment"` in the `promql` folder, you will see the `TestTimeseriesByteSliceToXXX64Alignment` test (could be added to the CI to prevent regressions).

I also added a generic test `TestTimeseriesByteSliceToXXX64Evaluation`: this test would have failed with a SIGBUS on ARM. Could be useful to quickly check other platforms (if this test fails, try to run the test with the `vm_ensure_xxx64_alignment` flag): in case of success, this platform should be added to `//go:build`).

---
Changes in the files:

- app/vmselect/promql/timeseries_realigned.go

File only included if compiling for arm (32 bits) or the `vm_ensure_xxx64_alignment` tag is set. Forces proper alignment (at the cost of an allocation).

- app/vmselect/promql/timeseries_realigned_test.go

Test to check proper alignment (only executed on arm, or with `vm_ensure_xxx64_alignment` tag)

- app/vmselect/promql/timeseries_test.go

Test to check that the float64/int64 can be accessed (would have failed on ARM, before this patch).

- app/vmselect/promql/timeseries_unaligned.go

Original code of the slice conversion (without alignment adjustment).

**Comment by oliverpool** [comment]
Regarding your suggestion
> make sure that byte slices passed to these functions are always aligned

I think it would mean quite a large change, since multiple time series are stored in a byte slice:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7257a2a97f493c2ec1c05c50f267dd1432a85aa0/app/vmselect/promql/timeseries.go#L121-L133

This would mean adding padding inside the `src []byte` to ensure alignment between series, as well as some alignment preparation before calling `encoding.DecompressZSTD` (which populates `src`).

Do you want me to still try such an approach? Or are you satisfied with my latest "build constraint" changes?

**Comment by valyala** [comment]
> This would mean adding padding inside the src []byte to ensure alignment between series, as well as some alignment preparation before calling encoding.DecompressZSTD (which populates src).

> Do you want me to still try such an approach? Or are you satisfied with my latest "build constraint" changes?

Agreed that this approach requires more code churn. I still decided to go that way and re-arrange the marshaled data inside `marshalTimeseriesFast` in order to ensure that timestamps and values are aligned at 8-byte boundaries. The code remains hacky, but now it should continue taking performance advantage of in-place conversion from byte slice to float64 and int64 slices. See 0af9e2b69340b068590f36f41e53261c1046fe11 .

@oliverpool , could you verify whether this change prevents from SIGBUS errors at Rasberry Pi in your case?

**Comment by valyala** [comment]
Closing this pull request then as superseded by 0af9e2b69340b068590f36f41e53261c1046fe11

**Comment by valyala** [comment]
The commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/0af9e2b69340b068590f36f41e53261c1046fe11 has been included in [v1.89.0](https://docs.victoriametrics.com/CHANGELOG.html). It has been appeared that this commit could result in `cannot unmarshal timeseries from rollupResultCache` panic after the upgrade. This panic should be fixed in e8225d7d6bd6275db9e3c13d0ec5c66be7c6f144 , which will be included in `v1.89.1`.

**Comment by valyala** [comment]
FYI, the change mentioned above has been included in [v1.79.11 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.11).

**Comment by valyala** [comment]
The change has been also included in [v1.87.3 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.3).

**Pull request closed without merging**
