### PR TITLE
vmui/logs: add log sorting

### PR DESCRIPTION
**Pull request by Loori-R**
### Describe Your Changes

add sorting of logs by groups and within each group by time in desc order. See #7184 and #7045

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Comment by MahmudovIbragim** [comment]
wow nice

**Comment by valyala** [comment]
@Loori-R , could you resolve merge conflicts?

**Comment by Loori-R** [comment]
@valyala Done, merge conflict resolved

**Comment by valyala** [comment]
@Loori-R , thanks for the pull request!

**Pull request merged**
