### PR TITLE
app/vmselect/netstorage

### PR DESCRIPTION
**Pull request by f41gh7**
correctly handle errGlobal set

### CODE REVIEW

**Review by tenmozes — APPROVED** [review]

**Comment by valyala** [comment]
@f41gh7 , thanks for the fix!

**Comment by valyala** [comment]
FYI, this fix has been included in [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by valyala** [comment]
FYI, this fix has been also included in [v1.87.14 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.14)

**Comment by valyala** [comment]
FYI, this pull request has been included also in [v1.93.11 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.11)

**Pull request merged**
