### PR TITLE
mvm: added k8s guide for managed VM

### PR DESCRIPTION
**Pull request by k1rk**
added guide on how to start k8s monitoring using managed VM

### CODE REVIEW

**Comment by denisgolius** [comment]
Could you please add link for this guide to https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/guides/README.md ?

**Comment by denisgolius** [comment]
> Could you please add link for this guide to https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/guides/README.md ?

@tenmozes or this guide should be published to Managed VictoriaMetrics section ?

**Comment by k1rk** [comment]
@denisgolius it will under managed. but also a good idea i think to add it to guides

**Review by zekker6 — APPROVED** [review]

**Review by tenmozes — APPROVED** [review]
LGTM, thank you for contribution

**Pull request merged**
