### PR TITLE
[Snyk] Upgrade @types/webpack-env from 1.18.0 to 1.18.1

### PR DESCRIPTION
**Pull request by k1rk**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade @types/webpack-env from 1.18.0 to 1.18.1.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **1 version** ahead of your current version.
- The recommended version was released **a month ago**, on 2023-05-24.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>@types/webpack-env</b></summary>
    <ul>
      <li>
        <b>1.18.1</b> - 2023-05-24
      </li>
      <li>
        <b>1.18.0</b> - 2022-08-16
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/DefinitelyTyped/DefinitelyTyped/releases">@types/webpack-env GitHub release notes</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/victoriametrics/project/69d9ccbb-b5b1-492f-9f8c-9032dcaf021e?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/victoriametrics/project/69d9ccbb-b5b1-492f-9f8c-9032dcaf021e/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/victoriametrics/project/69d9ccbb-b5b1-492f-9f8c-9032dcaf021e/settings/integration?pkg&#x3D;@types/webpack-env&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by hagen1778** [comment]
@YuriKravetc @dmitryk-dk @k1rk should we track updates like this for TS/JS in vmui? Or should it be a decision from developer?

**Comment by dmitryk-dk** [comment]
@hagen1778 @Loori-R 
In my practice, dependency versions were always set clearly by version, and only after testing was carried out, new versions of libraries were introduced. But this approach can slow down version updates.
I met several cases when raising the library version automatically broke either the project assembly or the application itself.

**Comment by Loori-R** [comment]
I agree with @dmitryk-dk . It's better to update manually because automatic updates can break the application

**Comment by Loori-R** [comment]
And there used to be automatic version tracking for VMUI, but we discontinued it because it was causing too many PRs to be opened

**Comment by hagen1778** [comment]
@k1rk can we update Snyk cfg to skip /vmui updates?

**Pull request closed without merging**
