### PR TITLE
vmui: graph action on moush hold and move

### PR DESCRIPTION
**Pull request by Loori-R**
1. `Ctrl` (`Cmd` on mac) + hold and move mouse: graph moves left or right
2. Select by the cursor or  `Ctrl` (`Cmd` on mac) + `Scroll up`: graph zoom in 
3. `Ctrl` (`Cmd` on mac) + `Scroll down`: graph zoom out

#2812

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Comment by valyala** [comment]
@Loori-R , thanks for the pull request!

Unfortunately it has the following usability issues:

1. It breaks `Ctrl+scroll` zoom - such zoom stops working now, while it should continue working.
2. It introduces non-intuitive zoom-in and zoom-out actions on mouse click and move left/right. I'm sorry that the https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2812 isn't clear enough. The desired behavior should match Grafana in this case - user should be able to zoom in into the time range selected by the cursor. The time range for zoom in can be selected in both directions - from left to right and from right to left. There is no need to introduce yet another action for zoom out except of already existing one - `ctrl + scroll down`.

**Comment by Loori-R** [comment]
updated

<details>
  <summary>Demo</summary>
  
chrome-capture-2022-7-4
 
</details>

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Loori-R , thanks for the pull request!

**Pull request merged**
