### PR TITLE
lib/storage: remove ForceMergeAllParts internal loop

### PR DESCRIPTION
**Pull request by faceair**
for fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4987

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
@faceair  can you sign-off commit please? Our merge policy requires commits to be signed.

**Comment by faceair** [comment]
Thank you for pointing it out. I've now configured global automatic sign-off for my Git settings, so there won't be any omissions in the future.

**Comment by f41gh7** [comment]
Thanks for contribution!

**Pull request merged**
