### PR TITLE
vmui: fix the display of the link to vmalert

### PR DESCRIPTION
**Pull request by Loori-R**
### Describe Your Changes

Fix the issue mentioned in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7088#issuecomment-2391360368

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Review by hagen1778 — CHANGES_REQUESTED** [review]
The fix doesn't work for me.
Here's how to reproduce:
```
make victoria-metrics && ./bin/victoria-metrics --vmalert.proxyURL=http://localhost:8880 
```
then 
```
make run-vmalert
```

Visit vmui and click on Alerts link in header - you'll be taken to `http://localhost:8428/prometheus/vmalert/`, which is incorrect path:
image

**Comment by Loori-R** [comment]
@hagen1778, Is it correct to use the following logic to construct the vmalert URL?

1) For the **single version**, use the server URL without the `/prometheus` suffix:

- server URL (from vmui settings): `/path/to/victoria-metrics/prometheus`
- vmalert URL: `/path/to/victoria-metrics/vmalert`

2) For the **cluster version**, add the `/vmalert` suffix to the server URL:

- server URL (from vmui settings): `/path/to/victoria-metrics/select/0/prometheus`
- vmalert URL: `/path/to/victoria-metrics/select/0/prometheus/vmalert`

**Comment by hagen1778** [comment]
> @hagen1778, Is it correct to use the following logic to construct the vmalert URL?

Please rely on the following resources:
1. https://docs.victoriametrics.com/#vmalert. For accessing vmalerts UI through single-node VictoriaMetrics configure -vmalert.proxyURL flag and visit http://<victoriametrics-addr>:8428/vmalert/ link.
2. https://docs.victoriametrics.com/cluster-victoriametrics/#vmalert. For accessing vmalerts UI through vmselect configure -vmalert.proxyURL flag and visit http://<vmselect>:8481/select/<accountID>/prometheus/vmalert/ link.

**Review by hagen1778 — APPROVED** [review]
LGTM

**Pull request merged**
