### PR TITLE
lib/mergeset/encoding.go: make function commonPrefixLen faster

### PR DESCRIPTION
**Pull request by ahfuzhang**
from this issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2254
in macbook pro 2019, Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz: 
    9.785 ns/op when memory aligned, 1.6 times faster than old function
    9.833 ns/op when memory not aligned

and I will add avx2 code next time.
thanks.

### CODE REVIEW

**Review by valyala — CHANGES_REQUESTED** [review]
LGTM overall!

@ahfuzhang , could you add benchmarks for `commonPrefixLen()` function for different prefix lengths?

**Comment by valyala** [comment]
Added benchmarks and tests for `commonPrefixLen` at 5f2b5bd173b1e96a5f12664e9feb73d0f6ec49a2

**Comment by valyala** [comment]
@ahfuzhang , could you post here results for the following benchmarks before and after applying this pull request?

- BenchmarkCommonPrefixLen
- BenchmarkInmemoryBlockMarshal
- BenchmarkInmemoryBlockUnmarshal

**Comment by ahfuzhang** [comment]
here is the result:
goos: darwin
goarch: amd64
pkg: github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

BenchmarkCommonPrefixLen/prefix-len-0-8                 857229081                1.286 ns/op           0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-1-8                 709308663                1.473 ns/op     678.75 MB/s           0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-2-8                 666506119                1.763 ns/op    1134.56 MB/s           0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-3-8                 640770340                1.866 ns/op    1607.61 MB/s           0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-4-8                 547492014                2.122 ns/op    1885.26 MB/s           0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-5-8                 471679311                2.300 ns/op    2174.01 MB/s           0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-6-8                 465168498                2.483 ns/op    2416.82 MB/s           0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-7-8                 414648476                2.806 ns/op    2494.37 MB/s           0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-8-8                 551661042                2.135 ns/op    3746.74 MB/s           0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-9-8                 511113198                2.390 ns/op    3765.72 MB/s           0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-33-8                294066612                3.858 ns/op    8553.71 MB/s           0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-67-8                241150149                4.296 ns/op    15595.51 MB/s          0 B/op          0 allocs/op
BenchmarkCommonPrefixLen/prefix-len-127-8               159241046                9.037 ns/op    14053.53 MB/s          0 B/op          0 allocs/op


BenchmarkInmemoryBlockMarshal/prefix-len-0-8              231504              5257 ns/op               0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-1-8              220821              4937 ns/op         101.29 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-2-8              236294              4807 ns/op         208.03 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-3-8              246014              4879 ns/op         307.43 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-4-8              187102              5518 ns/op         362.45 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-5-8              207682              6294 ns/op         397.21 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-6-8              157136              6426 ns/op         466.85 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-7-8              191835              6113 ns/op         572.54 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-8-8              183596              5909 ns/op         676.92 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-9-8              219666              5033 ns/op         894.10 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-33-8             225073              5032 ns/op        3278.82 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-67-8             222236              5126 ns/op        6534.83 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockMarshal/prefix-len-127-8            222934              5174 ns/op        12272.12 MB/s          0 B/op          0 allocs/op


BenchmarkInmemoryBlockUnmarshal/prefix-len-0-8            261800              4785 ns/op               0 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-1-8            265483              4403 ns/op         113.56 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-2-8            267418              4286 ns/op         233.29 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-3-8            274047              4300 ns/op         348.81 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-4-8            281450              4459 ns/op         448.55 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-5-8            239926              4362 ns/op         573.13 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-6-8            247897              4557 ns/op         658.36 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-7-8            246507              4684 ns/op         747.25 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-8-8            215470              4868 ns/op         821.70 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-9-8            234486              4929 ns/op         912.97 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-33-8           243720              4738 ns/op        3482.74 MB/s           0 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-67-8           164755              6587 ns/op        5085.71 MB/s           2 B/op          0 allocs/op
BenchmarkInmemoryBlockUnmarshal/prefix-len-127-8          167634              6852 ns/op        9266.97 MB/s           3 B/op          0 allocs/op

**Comment by ahfuzhang** [comment]
@valyala sorry, I didn't use github so much, could you teach me how to do next ? thanks.

**Comment by valyala** [comment]
@ahfuzhang , thanks for posting the benchmark results! As I understood, these results correspond to the patched code with the pull request applied. It would be great if you could post also benchmark results before applying the patch from this pull request, so these benchmark results could be compared in order to see the performance difference between the original and the patched code.

See also https://pkg.go.dev/golang.org/x/perf/cmd/benchstat - this program analyzes benchmark results before and after applying the change and shows the performance difference in easy-to-read form.

**Comment by valyala** [comment]
I'm going to close this pull request, since it looks like it doesn't bring significant performance improvements after [this optimization](de6dd1cd5a69af41428ca3efda5aef43d3dd6ea3) according to benchmark results, while reduces `commonPrefixLen()` code readability and maintainability. Additionally, this pull request reduces the performance for common prefixes with the length up to 60 chars.

@ahfuzhang , thanks for all the filed issues and pull requests oriented towards performance optimizations in VictoriaMetrics.

**Pull request closed without merging**
