### PR TITLE
[streaming aggregation] parameter for discarding samples with timestamps outside of aggregation interval

### PR DESCRIPTION
**Pull request by Amper**
issue #4068 
related PR by @zekker6 (was reverted): #4199
need to be merged only after: #5491

### CODE REVIEW

**Comment by rbizos** [comment]
Very useful for push metrics, do you know when this would be potentially merged ?

**Comment by hagen1778** [comment]
@AndrewChubatiuk would you mind looking at the problem described in this PR?

**Comment by rbizos** [comment]
To be fair it would be even better to have multiple windows for aggregations, for instance keep the previous one for let say a minute to allow for points a little late :) . I'm willing to implement it if you think its reasonable. VM deals nicely with late points anyway so adding a little delay isn't too impactful

**Comment by hagen1778** [comment]
> VM deals nicely with late points anyway so adding a little delay isn't too impactful

I'm afraid, this could be too impactful for vmagent to maintain multiple states of stream aggregation. It is important to consider potential resource usage in this case.

**Comment by rbizos** [comment]
For increase it should be bounded to a window so the two windows should be independent no ? I admit that for total this would require some smart logic as this isn't that simple. Like some kind of rebase logic.

One note is that aggregations that rely on the previous values are not as affected with delay as may be acceptable to have. On the other hand, for sum_samples, its trivial to implement and its the most affected by delay.

One implementation is on carbon-relay-ng https://github.com/grafana/carbon-relay-ng/blob/master/aggregator/aggregator.go

**Comment by hagen1778** [comment]
Closing this PR in favour of https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5981

**Pull request closed without merging**
