### PR TITLE
app/vmalert: fix datasource.roundDigits Parameter

### LINKED ISSUE #4340: vmalert: datasource.roundDigits Parameter does not work
### Describe the bug

When I set **-datasource.roundDigits="2"**,I expect the request to be sent to carry parameters **round_digits=2**. But it does not work

### To Reproduce

```
cat <<EOF >> pod.yaml
groups:
  - name: cadvisor
    rules:
      - alert: ContainerMemoryUsage
        expr: '(sum(container_memory_working_set_bytes{name!=""}) BY (instance, name) / sum(container_spec_memory_limit_bytes > 0) BY (instance, name) * 100) > 80'
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Container Memory usage (instance {{ $labels.instance }})
          description: "Container Memory usage is above 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        debug: true
EOF
```

```
./vmalert -rule=pod.yaml -datasource.url=http://vmselect.vm.svc.cluster.local:8421/select/0/prometheus -d
atasource.roundDigits=2 -notifier.url=http://10.2.112.25:30717 -evaluationInterval=10s
```

### Version

 # ./vmalert-prod --version
vmalert-20230518-212228-tags-v1.91.0-0-g73dfb030d

### Logs

./vmalert -rule=pod.yaml -datasource.url=http://vmselect.vm.svc.cluster.local:8421/select/0/prometheus -d
atasource.roundDigits=2 -notifier.url=http://10.2.112.25:30717 -evaluationInterval=10s    
2023-05-24T06:26:41.207Z        info    VictoriaMetrics/lib/logger/flag.go:12   build version:    
2023-05-24T06:26:41.207Z        info    VictoriaMetrics/lib/logger/flag.go:13   command-line flags
2023-05-24T06:26:41.207Z        info    VictoriaMetrics/lib/logger/flag.go:20     -datasource.roundDigits="2"
2023-05-24T06:26:41.207Z        info    VictoriaMetrics/lib/logger/flag.go:20     -datasource.url="secret"
2023-05-24T06:26:41.207Z        info    VictoriaMetrics/lib/logger/flag.go:20     -evaluationInterval="10s"
2023-05-24T06:26:41.207Z        info    VictoriaMetrics/lib/logger/flag.go:20     -notifier.url="http://10.2.112.25:30717"
2023-05-24T06:26:41.207Z        info    VictoriaMetrics/lib/logger/flag.go:20     -rule="pod.yaml"
2023-05-24T06:26:41.211Z        info    VictoriaMetrics/app/vmalert/main.go:162 reading rules configuration file from "pod.yaml"
2023-05-24T06:26:41.218Z        info    VictoriaMetrics/lib/httpserver/httpserver.go:99 starting http server at http://127.0.0.1:8880/
2023-05-24T06:26:41.219Z        info    VictoriaMetrics/lib/httpserver/httpserver.go:100        pprof handlers are exposed at http://127.0.0.1:8880/debug/pprof/
2023-05-24T06:26:46.267Z        info    VictoriaMetrics/app/vmalert/group.go:264        group "cadvisor" started; interval=10s; concurrency=1
2023-05-24T06:26:46.268Z        info    VictoriaMetrics/app/vmalert/datasource/vm.go:162        DEBUG datasource request: executing POST request with params "query=%28su
m%28container_memory_working_set_bytes%7Bname%21%3D%22%22%7D%29+BY+%28instance%2C+name%29+%2F+sum%28container_spec_memory_limit_bytes+%3E+0%29+BY+%28instance%2C+name%29+
%2A+100%29+%3E+80&step=300s&time=1684909600"

### Screenshots

_No response_

### Used command-line flags

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gsakun**
fix #4340

### CODE REVIEW

**Comment by hagen1778** [comment]
Hello @gsakun! What problem does this fix solve? Do you have an issue link?

**Comment by dmitryk-dk** [comment]
Hi @gsakun , @hagen1778 ! Here is the issue which describe this problem
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4340

**Comment by gsakun** [comment]
@hagen1778 @dmitryk-dk 
Sorry, I didn't give you enough detail.Since the returned data has more digits after the decimal point,I want to reduce the number of digits. So I use **datasource.roundDigits** flag, but it doesn't seem to work. I add debug field in alert_rule file,and test it. But in the output log, DEBUG datasource request does not contain **round_digits**. This parameter is not included as described in the [documentation](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html?highlight=digits#prometheus-querying-api-enhancements)

I read the source code.When the group rule is initialized,[newAlertingRule](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/alerting.go#L57) will be called.but when the [Clone ](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/datasource/vm.go#LL64C1-L64C1) method is called，The extraParams during program initialization are not injected. So i add it and modify And modified the merging strategy of extraParams in ApplyParams and custom extraParams of the alarm group in this pr.

**Comment by gsakun** [comment]
@hagen1778 @dmitryk-dk PTAL

**Review by hagen1778 — APPROVED** [review]
LGTM!

**Pull request merged**
