### PR TITLE
Adding Grafana dashboards for VM cluster

### PR DESCRIPTION
**Pull request by jtyr**
This PR is adding basic Grafana dashboards for VM cluster.

### CODE REVIEW

**Comment by tenmozes** [comment]
@hagen1778 could please take a look?

**Comment by valyala** [comment]
@jtyr , thanks for the pull request! We'll review it in the nearest time.

**Comment by valyala** [comment]
@jtyr , thanks again!

**Comment by byakku** [comment]
@jtyr which export method did you use? I can confirm that these dashboards are not usable right now on grafana 6.2.5.

**Pull request merged**
