### PR TITLE
app/vmselect: return +Inf as null in graphite render api

### LINKED ISSUE #3783: graphite interface to vmselect sometimes return +Inf as datapoint metric value, which breaks graphana
### Describe the bug

We put some amount of legacy metric traffic to graphite interface of VictoriaMetrics cluster, v1.79.5.
When I read these metrics back using vmselect graphite API:

```curl  -o- -s "https://vmselect-cluster/select/0/graphite/render?&format=json&from=-2d&maxDataPoints=2048&target==aliasByNode(exclude(asPercent(groupByNode(aliasSub(aliasByNode(exclude(movingAverage(ops.*.server.sde*.container.*.role.*.nginx_sla_statuses.*499%2C2)%2C'fo1%7CoSMStaging%7Co3%7Co5%7CoCi%7Cas8%7Caproxy1%7Cstat3dev1%7Cswift')%2C%203%2C%201%2C%207)%2C%20'%5Es(%5Cw%7B2%7D).*%5C.(.*).*%5C.(.*)'%2C%20'%5C1_%5C2_%5C3')%2C%200%2C%20'sum')%2C%20groupByNode(aliasSub(aliasByNode(exclude(movingAverage(ops.*.server.sde*.container.*.role.*.nginx_sla_accesses.total%2C2)%2C'fo1%7CoSMStaging%7Co3%7Co5%7CoCi%7Cas8%7Caproxy1%7Cstat3dev1%7Cswift')%2C%203%2C%201%2C%207)%2C%20'%5Es(%5Cw%7B2%7D).*%5C.(.*).*%5C.(.*)'%2C%20'%5C1_%5C2_%5C3')%2C%200%2C%20'sum'))%2C%20'nj_oMobileMeter%7Cnodejs1%7Cnodeproxy%7Cstat3dev1%7Coqa%7Csc_os8_revproxy1')%2C%200)&from=-3h&until=now&format=json&maxDataPoints=960"|python3 -m json.tool```

I get error from python json parser: `Expecting value: line 1 column 59883 (char 59882)`

cutting output around column 59883 gives: `l,1675722112],[+Inf,1675722196]`

This `+Inf` value breaks json parser in graphana.

### To Reproduce

I can't reproduce problem as it involve some real constantly changing data, but probably one of the functions included in the request `target` return +Inf as result of division on 0.

### Version

v1.79.5.

### Logs

_No response_

### Screenshots

_No response_

### Used command-line flags

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kaey**
0/0 = NaN
123/0 = +Inf

Fixes #3783

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
@kaey  can you sign-off commit?

**Comment by kaey** [comment]
Done (assuming you meant `git commit --signoff`)

**Comment by f41gh7** [comment]
> Done (assuming you meant `git commit --signoff`)

Yes, that's correct. But commit is still unsigned.

  There is a guide for it https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

  Can you follow it and force push new commit?

**Comment by kaey** [comment]
Done

**Comment by f41gh7** [comment]
Thanks for contribution!

**Pull request merged**
