### PR TITLE
vmselect/netstorage: introduce `search.maxWorkersPerQuery` for reduci…

### PR DESCRIPTION
**Pull request by hagen1778**
…ng contention on multi-core systems

Build on v1.93.5 single node

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by valyala** [comment]
FYI, this pull request addresses similar scalability issue on systems with many CPU cores as the https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5119 does . See the related issue at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5087 .

**Comment by hagen1778** [comment]
@valyala I just got a feedback when this change helped to resolve the contention problem on multi core system. I'll transition this PR from draft ASAP.

**Comment by valyala** [comment]
The best case would be to automatically adjust the default value for `-search.maxWorkersPerQuery` depending on the number of available CPU cores, in order to achieve the maximum scalability for the particular system without the need to tune the `-search.maxWorkersPerQuery` command-line flag. This flag may remain for cases when the default logic sets incorrect default value for this flag.

**Comment by hagen1778** [comment]
closing this PR in favour of https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5195

**Pull request closed without merging**
