### PR TITLE
Address some edge cases in OpenTSDB importer and speed it up

### PR DESCRIPTION
**Pull request by johnseekins**
By default, we were using the "row size" for making our subqueries. (The second section here: `sum-1m-avg:1h:1d`). This works fine until we produce a query like this: `sum-6h-avg:4h:30d`. In this case, we're requesting a smaller range than we're actually aggregating, which produces either:

1. no data
2. bad data

Using the row size as our subquery size also meant we had a chance of missing data (since we land exactly on row boundaries).

This PR looks at the row size and the aggregation window, selects the larger of the two, then doubles that to produce our subquery size. This should both make results more accurate _and_ speed up migration (as we'll be performing fewer subqueries for each series).

There was also a bug in the current implementation where OpenTSDB was returning timestamps in seconds to VictoriaMetrics, which expects milliseconds. And thus all the written data was significantly outside any reasonable retention period.

### CODE REVIEW

**Comment by johnseekins** [comment]
As a side note, these changes have _significantly_ improved the speed of the importer _and_ reduced the load on the underlying OpenTSDB cluster. We're seeing somewhere around twice the speed as before.

**Comment by valyala** [comment]
@hagen1778 , could you look at this pull request?

**Review by hagen1778 — APPROVED** [review]
LGTM!

**Comment by hagen1778** [comment]
Thanks!

**Comment by valyala** [comment]
FYI, this pull request has been included in `vmctl` [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Pull request merged**
