### PR TITLE
vmui: ui improvements

### PR DESCRIPTION
**Pull request by Loori-R**
<details>
<summary>1. Improved Accessibility score from 72 to 100</summary>

measured using [Lighthouse](https://developer.chrome.com/docs/lighthouse/accessibility/?utm_source=lighthouse&utm_medium=devtools):<br/>

</details>

<details>
<summary>2. Modified chart tooltip and legend for better data readability</summary>

</details>

<details>
<summary>3. Fixed value rounding for the chart</summary>

For example query `1.600`: <br/>

</details>

### CODE REVIEW

**Review by hagen1778 — APPROVED** [review]
Look great!

**Comment by valyala** [comment]
Looks great, except the rounding part. Values were rounded in the way to make sure they have enough significant digits to show the difference between distinct values on the graph. E.g. different values should be *always* shown differently when hovering them on the graph.

For example, if the graph contains values in the range `[1.000001 - 1.000002]`, then values in this range on the graph - such as `1.0000001`, `1.0000002` and `1.0000009` - should be displayed as is without rounding to `1` or to `1.000001` and `1.000002`. This is needed in order to reduce user's confusion when it sees non-constant graph line, while the same constant value is displayed when hovering different parts of the graph.

On the other hand, values displayed on the graph must be rounded in order to remove noisy non-significant digits, since these digits distract users without bringing any benefits. For example, if the graph shows values in the range `[1e9 - 2e9]`, then there is no need to show all the 9 digits per each graph line. It is enough to show the first 3-5 digits then. E.g. it is better to display `123000000` instead of `1234567890`, since `4567890` is a noise, which distracts users' attention from graph values.

Another example - it is better to display `1.23` instead of `1.23456789` on the graph for values in the range `[1 - 2]`. Note that the number of significant digits depends on the graph range. For example, if the graph range is `[1.234 .. 1.235]`, then `1.23456789` must be rounded to something like `1.23457`, so distinct points on the graph have distinct values.

**Comment by valyala** [comment]
@Loori-R , please take a look at the comment above and make sure vmui displays values according to the recommendations there.

**Comment by valyala** [comment]
Also make sure that the rounding logic doesn't break for constant graphs. The rounding should work great for constant graphs with values equal to zero, close to zero, negative values close to zero, large positive and negative value.

**Comment by Loori-R** [comment]
@valyala, checked the rounding taking into account the comment above - everything works correctly.

**Pull request merged**
