### PR TITLE
Fix: count inmemoryParts that have not been taken for merge

### PR DESCRIPTION
**Pull request by lujiajing1126**
When checking if assisted merge is needed, inMerge parts are counted now. 

But I suppose parts that have not been taken for merge should be counted instead. Otherwise `assistedMergeForInmemoryParts` could only get an empty parts (since every part may be in merge)... 

```go
func (ddb *datadb) assistedMergeForInmemoryParts() {
	ddb.partsLock.Lock()
	parts := make([]*partWrapper, 0, len(ddb.inmemoryParts))
	parts = appendNotInMergePartsLocked(parts, ddb.inmemoryParts)
	// Do not take into account available disk space when merging in-memory parts,
	// since otherwise the outdated in-memory parts may remain in-memory, which, in turn,
	// may result in increased memory usage plus possible loss of historical data.
	// It is better to crash on out of disk error in this case.
	pws := make([]*partWrapper, 0, len(parts))
	pws = appendPartsToMerge(pws[:0], parts, math.MaxUint64)
	setInMergeLocked(pws)
	ddb.partsLock.Unlock()

	ddb.mustMergeParts(pws, false)
}
```

I am not pretty sure if it is a typo. Pls correct me if I am wrong.

### CODE REVIEW

**Comment by lujiajing1126** [comment]
An update:

image

After this patch, ingestion rate has been stabilized even if a higher request rate is reached.

image

In the meanwhile, active merges have been mitigated.

**Review by valyala — APPROVED** [review]
Nice catch!

**Comment by valyala** [comment]
@lujiajing1126 , thanks for the fix!

**Comment by valyala** [comment]
FYI, this bugfix has been included in [VictoriaLogs v0.5.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.5.0-victorialogs)

**Pull request merged**
