### PR TITLE
vmui: introduce application mode

### PR DESCRIPTION
**Pull request by Loori-R**
Added the ability to configure vmui for app mode. If params are set:
- Will be predefine a Server URL by default from params (Server URL cannot be edited from UI);
- Query string writing will be disabled (range_input, end_input, step_input, expr, etc.).
<br/>
A way to provide an additional configuration of the following or similar structure:

```
{
  "serverURL": ""http://localhost/myRouter?customParam=e0077a1a-5b8d-452b-ad89-7b3498f349be"
}
```

where serverURL contains a URL for serverURL field - where to send requests.
The described config should be set to attribute `data-params` for the parent container.
#1918

### CODE REVIEW

**Comment by hagen1778** [comment]
Hi @Loori-R! Thanks for PR!

> Query string writing will be disabled (range_input, end_input, step_input, expr, etc.).

Can you elaborate a bit on this? Why these params are disabled?

Also, the PR seems to contain some changes unrelated to application-mode feature. Is this intentional?

**Comment by Loori-R** [comment]
> Can you elaborate a bit on this? Why these params are disabled?

@dmitryk-dk asked to disable these params for the application to work correctly.

<br>

> Also, the PR seems to contain some changes unrelated to application-mode feature. Is this intentional?

Maybe I missed something, but I don't see some changes unrelated to application mode. 
Can you point to the location where the question arose?

**Comment by hagen1778** [comment]
> Can you point to the location where the question arose?

I had the following commits in mind: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1949/commits/1154147226c276bb66f8c99545518e5db23a867b  https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1949/commits/db0c3d202974aa0e1160993a326e4125fb46a40d https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1949/commits/cc86dca062a4b9ac77e6401ce826073dfaa33eb6 https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1949/commits/0e1f3a1a9cec8b0d403b474fb60a0e3e72a317b1 etc.

**Comment by Loori-R** [comment]
> I had the following commits in mind: [1154147](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/1154147226c276bb66f8c99545518e5db23a867b) [db0c3d2](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/db0c3d202974aa0e1160993a326e4125fb46a40d) [cc86dca](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/cc86dca062a4b9ac77e6401ce826073dfaa33eb6) [0e1f3a1](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/0e1f3a1a9cec8b0d403b474fb60a0e3e72a317b1) etc.

These commits are already in the master. Merged to avoid conflicts

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
Thanks!

**Pull request merged**
