### PR TITLE
app/vmbackup: introduce new flag type URL

### PR DESCRIPTION
**Pull request by hagen1778**
The new flag type is supposed to be used for specifying URL values which could contain sensitive information such as auth tokens in GET params or HTTP basic authentication.

The URL flag also allows loading its value from files if `file://` prefix is specified. As example, the new flag type was used in app/vmbackup as it requires specifying `authKey` param for making the snapshot.

See related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5973

Thanks to @wasim-nihal for initial implementation https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6060

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks!

**Comment by hagen1778** [comment]
@wasim-nihal @f41gh7 this PR was reverted in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/679844feafe0cc6c0187c0acb39ab5ad9f7d6eb5

The reason for revert is that this change doesn't improve security of vmbackup flags. See example below:
```
./bin/vmbackup -storageDataPath=/path/to/victoria-metrics-data -snapshot.createURL="http://user:pass@localhost:8428/snapshot/create?authKey=foobar" -dst=gs://bucket/path/to/new/backup
...
2024-04-24T10:26:38.092Z        info    VictoriaMetrics/app/vmbackup/main.go:62 Snapshot create url http://xxxxx:xxxxx@localhost:8428/snapshot/create?authKey=xxxxx
2024-04-24T10:26:38.092Z        info    VictoriaMetrics/app/vmbackup/main.go:70 Snapshot delete url http://xxxxx:xxxxx@localhost:8428/snapshot/delete?authKey=xxxxx
2024-04-24T10:26:38.092Z        info    VictoriaMetrics/lib/snapshot/snapshot.go:32     Creating snapshot
2024-04-24T10:26:38.097Z        fatal   VictoriaMetrics/app/vmbackup/main.go:73 cannot create snapshot via "http://xxxxx:xxxxx@localhost:8428/snapshot/create?authKey=xxxxx": Get "http://user:***@localhost:8428/snapshot/create?authKey=foobar": dial tcp 127.0.0.1:8428: connect: connection refused
```

As you see, flags initialization was successful, or sensitive data was hidden `http://xxxxx:xxxxx@localhost:8428/snapshot/delete?authKey=xxxxx`. However, on attempt to make an HTTP call we pass the original unmasked URL to the Go std lib. And if any error happens during the call, the std HTTP lib returns the error message that we do not control:
```
2024-04-24T10:26:38.097Z        fatal   VictoriaMetrics/app/vmbackup/main.go:73 cannot create snapshot via "http://xxxxx:xxxxx@localhost:8428/snapshot/create?authKey=xxxxx": Get "http://user:***@localhost:8428/snapshot/create?authKey=foobar": dial tcp 127.0.0.1:8428: connect: connection refused
```
And this error message contains the exposed sensitive information.

**Comment by wasim-nihal** [comment]
@hagen1778 @f41gh7 , how about the approach taken this [PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5983)? This approach separates the sensitive info/creds from the URLs.

**Comment by hagen1778** [comment]
@wasim-nihal with [this approach](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5983) authToken will still be exposed on HTTP errors, as they're still a part of URL. authToken need to be passed as header for this to work.

**Comment by hagen1778** [comment]
>  I understand there will be changes at vmstorage end to check for the auth key header as well along with the query param for backward compatibility.

Right! vmstorage should understand both: query arg and header (if query arg is missing) for backward compatibility.
Sorry for late replies, busy days(

**Comment by wasim-nihal** [comment]
sure. thanks!

**Comment by valyala** [comment]
@hagen1778 , it would be great to add the reason for revert directly in the commit message for the `revert` type commit similar to this one - 679844feafe0cc6c0187c0acb39ab5ad9f7d6eb5 . This simplifies investigation of commit history.

**Pull request merged**
