### PR TITLE
Changed vmalert --remoteWrite.url to port 8429 (vmagent)

### PR DESCRIPTION
**Pull request by dmitry-shur**
### Describe Your Changes

Updated docker.compose.yml, set remotewrite.url to port 8429 so it would correspond to documentation 

### Checklist

The following checks are **mandatory**:

- [x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Review by hagen1778 — APPROVED** [review]
Thanks for the contribution!

**Comment by Haleygo** [comment]
@dmitry-shur @hagen1778 
Why is this change needed? vmalert writes data to `victoriametrics` instead of `vmagent`, and `victoriametrics` exposes `8428` by default.

**Comment by hagen1778** [comment]
Hey @Haleygo! Sorry if this was poorly explained by me and @dmitry-shur
The point was to make docker-compose config to reflect the diagram here https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker#victoriametrics-single-server
image

**Comment by Haleygo** [comment]
@hagen1778 
okay, then remoteWrite url must be updated to `--remoteWrite.url=http://vmagent:8429/`.

**Comment by hagen1778** [comment]
Yeah, you're right. It is better for me to not merge PRs today. Will address it asap

**Comment by dmitry-shur** [comment]
> @hagen1778 okay, then remoteWrite url must be updated to `--remoteWrite.url=http://vmagent:8429/`.

oops, my bad - lack of understanding. @Haleygo thanks for keeping an eye on that!

**Pull request merged**
