### PR TITLE
docs: Add VictoriaLogs HA example for single nodes

### PR DESCRIPTION
**Pull request by tenmozes**
### Describe Your Changes

Please provide a brief description of the changes you made. Be as specific as possible to help others understand the purpose and impact of your modifications.

### Checklist

The following checks are **mandatory**:

- [x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by tenmozes** [comment]
Original image

ha-victorialogs-single-node

**Review by func25 — APPROVED** [review]
LGTM

**Comment by valyala** [comment]
Good scheme, but it would be great providing guides on how to configure every log collector shown on the scheme for sending the collected logs to multiple VictoriaLogs instances (or to other destinations). Otherwise it could be hard to figure out this by the user.

@func25 , these are the same guides which should help new users setting up log collectors for sending logs simultaneously to the original destination (such as Elasticsearch or Grafana Loki) and to VictoriaLogs. Could you put links to these guides into the chapter from this pull request when these guides will be ready?

**Comment by tenmozes** [comment]
@valyala let me merge this first and update the documentation i want to have links in place

**Comment by tenmozes** [comment]
you can track the progress of adding examples here - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6968

**Pull request merged**
