### PR TITLE
Feature allow configuring disableOnDiskQueue and dropSamplesOnOverload per url

### PR DESCRIPTION
**Pull request by hagen1778**
* FEATURE: [vmagent](https://docs.victoriametrics.com/vmagent.html): allow configuring `-remoteWrite.disableOnDiskQueue` and `-remoteWrite.dropSamplesOnOverload` cmd-line flags per each `-remoteWrite.url`. See this [pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6065). Thanks to @rbizos for implementaion!
* FEATURE: [vmagent](https://docs.victoriametrics.com/vmagent.html): add labels `path` and `url` to metrics `vmagent_remotewrite_push_failures_total` and `vmagent_remotewrite_samples_dropped_total`. Now number of failed pushes and dropped samples can be tracked per `-remoteWrite.url`.

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks for contribution!

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.102.0-rc1 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc1).

**Comment by valyala** [comment]
Please see the follow-up commit 0145b65f251c0b9ee10333dca31f4032c82f9dbf

**Comment by valyala** [comment]
See also another follow-up commit - f3ccbe181d672962658153e12c9f6e13089fff17

**Pull request merged**
