### PR TITLE
lib/fs: properly call windows APIs

### PR DESCRIPTION
**Pull request by f41gh7**
Previously we manually imported system windows DDLs
and made direct syscall.

 But golang exposes syscall wrappers with sys/windows package.
It seems, that direct syscall was broken at 1.23 golang release. It was `GetDiskFreeSpace` syscall in our case.

This commit replaces all manual syscalls with wrappers

Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6973

### CODE REVIEW

**Comment by hagen1778** [comment]
@f41gh7 is there related issue on Golang issue tracker?

**Review by hagen1778 — APPROVED** [review]
LGTM!
Thanks for quick fix!

**Comment by hagen1778** [comment]
Looks related to https://github.com/golang/go/issues/69029. If so, please mention this ticket in the changelog.

**Comment by denisgolius** [comment]
@f41gh7  Checked victoria-logs and victoria-metrics on windows 10 under go 1.23.1 - it works without any issue.

**Comment by tqangxl** [comment]
> @f41gh7 Checked victoria-logs and victoria-metrics on windows 10 under go 1.23.1 - it works without any issue.
win11 v1.103.0- run fatal error: sync: inconsistent mutex state and fatal error: unexpected signal during runtime execution
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7011

**Pull request merged**
