### PR TITLE
make: build and release vmagent

### PR DESCRIPTION
**Pull request by jsvisa**

### CODE REVIEW

**Comment by f41gh7** [comment]
Hello, vmutils build for cluster version was disabled at this commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/441822c4ccec0aa8b1245c204d2e365785676f1b
 ```There are subtle differences between these binaries in cluster branch from binaries in single-node branch
such as missing `-httpAuth.*` command-line flags. These differences introduce confusion to users,
so let's stop building these binaries from cluster version.```

**Comment by jsvisa** [comment]
Thanks for your quick reply, but how could I build those binaries?

**Comment by valyala** [comment]
> Thanks for your quick reply, but how could I build those binaries?

`vmagent` can be built from `master` branch with `make vmagent` command. See [these docs](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources) for more details.

**Comment by valyala** [comment]
Closing the pull request.

**Pull request closed without merging**
