### PR TITLE
vmui: minor enhancements

### PR DESCRIPTION
**Pull request by Loori-R**
- Update NPM dependencies
- Fix the filter by the label on the cardinality page
- Fix display icons in Safari
- Add copyright and link to [website](https://victoriametrics.com/) to the Footer
- Move "create an issue" from the Header to the Footer

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Comment by valyala** [comment]
@Loori-R , thanks for vmui enhancements!

**Comment by valyala** [comment]
@Loori-R , it looks like this change broke displaying some graphs. For example, https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/?g0.expr=process&g0.range_input=30m&g0.end_input=2022-12-13T02%3A31%3A02&g0.step_input=3.886&g0.relative_time=last_30_minutes#/

**Comment by valyala** [comment]
Hm, it looks like the auto-completion is somewhat broken - try entering `process_` at https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/ and selecting `process_cpu_cores_available` in the autocompletion list. The expected behavior is to show the corresponding graph for the selected metric. But the actual behavior is that vmui sends the `process_` query to VictoriaMetrics instead of the selected `process_cpu_cores_available`.

**Comment by Loori-R** [comment]
@valyala, it looks like autocomplete was broken before. My fault. I will fix this.

**Pull request merged**
