### PR TITLE
vmalert: [bug] fixed System hyperlink 404 redirect

### PR DESCRIPTION
**Pull request by jiekun**
### Describe Your Changes

As mentioned in #6603 , some hyperlinks under `vmalert` -> `System` section is not working as expected. 

image

I will take `/flags` as example, it's redirecting with HTML `<a href="flags">`

Pages and redirection:
- For page `http://127.0.0.1:8880/`: `flags` button will redirect to `http://127.0.0.1:8880/flags`
- For page `http://127.0.0.1:8880/vmalert`: `http://127.0.0.1:8880/flags`
- For page `http://127.0.0.1:8880/vmalert/`: `http://127.0.0.1:8880/vmalert/flags` (page not exists)
- Similar redirection could be observed with `-http.pathPrefix`

Two potential ways to avoid 404 redirection:
1. **avoid visiting `/vmalert/`** (I'm trying to do this).
2. provide support for `/vmalert/flags`.

`/vmalert/` could be visit only when user click other navigator (e.g. Group) and click vmalert again:
Peek 2024-07-10 10-07
Because: `http://127.0.0.1:8880/vmalert/groups?search=` + `<a class="nav-link" href=".">` = `http://127.0.0.1:8880/vmalert/`

So I'm trying to change the `href="."` to `href="../vmalert"`.

### Checklist

The following checks are **mandatory**:

- [X] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by jiekun** [comment]
ping @Loori-R for front-end suggestion, not sure if `href="../vmalert"` is the best choice here. Thanks!

**Comment by hagen1778** [comment]
I'm removing label `vmui` since it's related only to the following components:
* https://docs.victoriametrics.com/#vmui
* https://docs.victoriametrics.com/victorialogs/querying/#web-ui

The rest of VictoriaMetrics could have their own Web UI, but it is usually super simple and doesn't require @Loori-R involvement.

**Comment by hagen1778** [comment]
Links in vmalert UI are tricky, because they need to satisfy the following requirements:
1. All links should work when vmalert starts with default configs
2. All links should work when vmalert starts with `-http.pathPrefix`
3. All links should work when vmalert is accessed from vmselect/vmsingle when they're configured with `-vmalert.proxyURL` - see https://docs.victoriametrics.com/#vmalert. This is why `/vmalert/` prefix has to stay.

**Comment by jiekun** [comment]
Thank you for the hint.

These two parts are tested locally.
> 1. All links should work when vmalert starts with default configs
> 2. All links should work when vmalert starts with `-http.pathPrefix`

I'm going to check this proxy way today. But I think this PR should works even with a proxy for vmselect/vmsingle.
> 3. All links should work when vmalert is accessed from vmselect/vmsingle when they're configured with `-vmalert.proxyURL` - see https://docs.victoriametrics.com/#vmalert. This is why `/vmalert/` prefix has to stay.

**Review by hagen1778 — APPROVED** [review]
Thanks for contribution!

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.93.16 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.16).

**Pull request merged**
