### PR TITLE
Limit concurrent inmemory parts to 100

### PR DESCRIPTION
**Pull request by misutoth**
This change seems to improve a lot on #5190 

The highest CPU consumption of a storage was 41 as opposed to earlier 80-90. The whole system came up much sooner, in about an hour. 

However, there are still some "unlucky" storage or storages that takes much more time to come up to speed than for the others.

### CODE REVIEW

**Comment by hagen1778** [comment]
@valyala ptal

**Comment by misutoth** [comment]
@valyala , @zekker6 , I have repeated the test and tried to clarify in what aspect does this change bring any improvement. The test starts off from an empty storage and is loaded with 945 million time series. With the change it took 35 minutes, without the change it took 116 minutes to get all of them accommodated. Although the test is from empty database we have experienced similar problems when receiving a sudden bigger churn and also during daily indexdb rotation.

We believe this difference can be attributed to the inefficient state of vmstorage when the inmemory indexdb parts goes even beyond 1000. In such a state **both** ingestion and querying starts to show linear computational complexity.

We have been running our production system with the changes for more than 2 months and our life is happy again. :)

Please find the screenshots attached for both cases:

1. Original cluster version
Screenshot 2023-12-27 at 17 14 36
Screenshot 2023-12-27 at 17 14 54
Screenshot 2023-12-27 at 17 15 10
Screenshot 2023-12-27 at 17 15 27
Screenshot 2023-12-27 at 17 15 43
Screenshot 2023-12-27 at 17 15 57
Screenshot 2023-12-27 at 17 16 08
Screenshot 2023-12-27 at 17 16 21
Screenshot 2023-12-27 at 17 16 35
Screenshot 2023-12-27 at 17 16 52
Screenshot 2023-12-27 at 17 17 53

2. Change with this PR included
Screenshot 2023-12-27 at 14 37 49
Screenshot 2023-12-27 at 14 38 12
Screenshot 2023-12-27 at 14 38 55
Screenshot 2023-12-27 at 14 39 31
Screenshot 2023-12-27 at 14 39 46
Screenshot 2023-12-27 at 14 40 09
Screenshot 2023-12-27 at 14 40 37
Screenshot 2023-12-27 at 14 41 05
Screenshot 2023-12-27 at 14 41 35

**Comment by valyala** [comment]
@misutoth , thanks for very detailed description of the root cause of the issue and for the pull request! I prepared the commit fa566c68a6ccf7385a05f649aee7e5f5a38afb15 , which is based on ideas from this pull request. Could you verify whether this commit improves data ingestion performance under [high churn rate](https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate) on your workload?

**Comment by misutoth** [comment]
> @misutoth , thanks for very detailed description of the root cause of the issue and for the pull request! I prepared the commit [fa566c6](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/fa566c68a6ccf7385a05f649aee7e5f5a38afb15) , which is based on ideas from this pull request. Could you verify whether this commit improves data ingestion performance under [high churn rate](https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate) on your workload?

Thanks for your reply. Unfortunately I am no longer with the company. @Kislaci90 or @marcellhegedus may be able to repeat the test... depending on their workload. 😄

**Comment by valyala** [comment]
FYI, an [additional commit](bb7a419cc30afed0a42c431d48cb5f4d1ac29e7b) has been merged into VictoriaMetrics, which should further improve the scalability of background merge speed for both `indexdb` and `data` parts on systems with many CPU cores.

I'm going to close this pull request, since commits referred above already implement main ideas from this pull request.

@misutoth , thanks again for your time spent on the initial investigation of the issue and preparing this pull request!

**Pull request closed without merging**
