### PR TITLE
support multi-tenancy when query rules

### PR DESCRIPTION
**Pull request by dxtrzhang**

### CODE REVIEW

**Review by hagen1778 — APPROVED** [review]

**Comment by hagen1778** [comment]
Looks like tests are failing

**Review by hagen1778 — COMMENTED** [review]
Looks like tests are failing

**Review by hagen1778 — CHANGES_REQUESTED** [review]
tests are failing

**Comment by dxtrzhang** [comment]
failed test fixed.

**Comment by hagen1778** [comment]
Closing due to inactivity. Please also see https://docs.victoriametrics.com/vmalert.html#multitenancy

**Pull request closed without merging**
