### PR TITLE
vmauth: expose latency metrics per user

### PR DESCRIPTION
**Pull request by hagen1778**
expose `vmauth_user_request_duration_seconds`
and `vmauth_unauthorized_user_request_duration_seconds` summary metrics for measuring requests latency per user.

### CODE REVIEW

**Review by Amper — APPROVED** [review]
LGTM

**Comment by Amper** [comment]
In this [issue](#4522) users also ask for `vmauth_user_http_request_duration_seconds_bucket `.

**Comment by hagen1778** [comment]
Oh wow, I haven't seen that issue)

The metric name is picked to be consistent with already existing `vmauth_user_requests_total` metric name.

**Comment by hagen1778** [comment]
> As far as I remember, we discussed with @valyala this metric. And he was strongly against adding it, since it may produce high cardinality values.

@f41gh7 this is Summary type, it produces controlled number of unique series per-user.

**Comment by Amper** [comment]
It will not contain more entries than the number of users in the configuration. Is it a high cardinality?

**Comment by hagen1778** [comment]
I believe, @f41gh7 meant potential cardinality issues when using histograms. But with summary type number of series is limited by 7 per metric_name+unique labels. Basically, if we had 10 users in vmauth then this change would add 70 more time series.

However, summary type for duration measurement can't be aggregated across multiple instances since its quantiles are pre-calculated already. Unlike in histogram. But we already use summary for `vm_request_duration_seconds` metric and it shows itself pretty good.

**Comment by f41gh7** [comment]
> > As far as I remember, we discussed with @valyala this metric. And he was strongly against adding it, since it may produce high cardinality values.
> 
> @f41gh7 this is Summary type, it produces fixed number of unique series per-user.

Oh, yes, in this case, cardinality is limited. LGTM!

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by Sin4wd** [comment]
Sorry if this is not the right place to discuss.
Thanks for the summary metric. I  understand the worry about cardinality, however I want to mention that buckets are valuable enough that we can accept the burden. Why? because we can define  a clear SLI that let's us debug query issues and drill down the problem to specific sources of queries.
As you know for sure it's impossible to provide good latency for all sorts of queries. At least we can agree with our developers to use a separate user (for example grafana-dev) as they experiment with queries and then use main-user only if they came up with the right and light query.
I understand that the whole histogram type might be too much, but only a limited number of fixed sized buckets will suffice for our purpose. I mean we can have only two or three buckets with fixed sizes to calculate `1-X_bucket{le="5"}/X_count`. Moreover, buckets can be correctly aggregated in cases that we have many replicas of vmauth.
What do you think?

**Pull request merged**
