### PR TITLE
Update NPM deps to fix dependabot CVEs

### PR DESCRIPTION
**Pull request by dima-vm**
Fixes #2024, #2025, #2026, #2027, #2028

### CODE REVIEW

**Comment by dima-vm** [comment]
Also ran `npm upgrade`

**Comment by valyala** [comment]
@Loori-R , could you look at this PR?

@dima-vm , did you follow https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmui/README.md when preparing this PR? Note that it is expected that all the `npm` commands are executed inside Docker container instead of host machine. This guarantees reproducible builds with the same `npm` version and the same set of dependencies on any host machine.

**Comment by dima-vm** [comment]
> @dima-vm , did you follow https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmui/README.md when preparing this PR? Note that it is expected that all the `npm` commands are executed inside Docker container instead of host machine. This guarantees reproducible builds with the same `npm` version and the same set of dependencies on any host machine.

Thanks, good to know. (It didn't differ from what dependabot suggested, checked that `git diff origin/master -- package-lock.json` was empty, so this PR had the same changes as dependabot's).
However, `make vmui-update` fails for me on any branch:
```
> vmui@0.1.0 build
> GENERATE_SOURCEMAP=false react-app-rewired build

Creating an optimized production build...
Failed to compile.

TS7016: Could not find a declaration file for module 'dayjs'. '/build/packages/vmui/node_modules/dayjs/dayjs.min.js' implicitly has an 'any' type.
  If the 'dayjs' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'dayjs';`
     7 | import makeStyles from "@mui/styles/makeStyles";
     8 | import TimeDurationSelector from "./TimeDurationSelector";
  >  9 | import dayjs from "dayjs";
       |                   ^^^^^^^
    10 |
    11 | interface TimeSelectorProps {
    12 |   setDuration: (str: string) => void;
```

I probably need to file a separate issue.

**Comment by valyala** [comment]
> However, `make vmui-update` fails for me on any branch

I cannot reproduce this in the latest commit at `master` branch - `e4e36383e20f00d43d1bf8d96d7b2e31e2d79c8c`:

```
$ make vmui-update 
docker build -t vmui-builder-image -f app/vmui/Dockerfile-build ./app/vmui
Sending build context to Docker daemon  346.7MB
Step 1/4 : FROM node:alpine3.14
 ---> aae0878eed12
Step 2/4 : RUN apk update && apk add --no-cache bash bash-doc bash-completion libtool autoconf automake nasm pkgconfig libpng gcc make g++ zlib-dev gawk
 ---> Using cache
 ---> 3a190b1ecba7
Step 3/4 : RUN mkdir -p /app
 ---> Using cache
 ---> c4b8818af737
Step 4/4 : WORKDIR /app
 ---> Using cache
 ---> c7a05ea3913a
Successfully built c7a05ea3913a
Successfully tagged vmui-builder-image:latest
docker run --rm \
          --user 1000:1000 \
         --mount type=bind,src="/home/valyala/work/VictoriaMetrics/app/vmui",dst=/build \
         -w /build/packages/vmui \
         --entrypoint=/bin/bash \
         vmui-builder-image -c "npm install && npm run build"

up to date, audited 1370 packages in 5s

181 packages are looking for funding
  run `npm fund` for details

10 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice 
npm notice New major version of npm available! 7.21.1 -> 8.3.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.3.0>
npm notice Run `npm install -g npm@8.3.0` to update!
npm notice 

> vmui@0.1.0 build
> GENERATE_SOURCEMAP=false react-app-rewired build

Creating an optimized production build...
Compiled with warnings.

src/components/Home/Configurator/Query/QueryConfigurator.tsx
  Line 24:10:  'serverUrl' is assigned a value but never used  @typescript-eslint/no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  239.29 kB  build/static/js/main.22df0342.js
  1.73 kB    build/static/js/27.85f0e2b0.chunk.js
  1.38 kB    build/static/css/main.79ff1ad2.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

rm -rf app/vmselect/vmui/* && mv app/vmui/packages/vmui/build/* app/vmselect/vmui
```

Note that `make vmui-update` command must run from the root directory of VictoriaMetrics repository. Probably you run this command from another directory.

**Pull request closed without merging**
