### PR TITLE
vmui: improve tracing styles

### PR DESCRIPTION
**Pull request by Loori-R**
Improved trace display for better visual separation of branches:
- Increased left padding for each element
- Added padding for the last element in the branch

<table>
<tr>
<td>before</td>
<td>after</td>
</tr>
<tr>
<td>
Screenshot 2024-03-05 at 13 20 32
</td>
<td>
Screenshot 2024-03-05 at 13 40 57
</td>
</tr>
</table>

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Comment by hagen1778** [comment]
@Loori-R would you mind adding a short line to the changelog?

**Comment by Loori-R** [comment]
@hagen1778, the changelog has been updated

**Review by hagen1778 — APPROVED** [review]
Thank you!

**Comment by valyala** [comment]
The query trace usually contains many lines. If these lines do not fit the vertical screen space, the user needs to scroll the presented query trace. Too much vertical scrolling makes harder investigating the provided query trace. That's why it is better to condense the vertical space used by the query trace as much as possible.

While the `after` screenshot looks better visually than the `before` screenshot, it uses **slightly** more vertical space. That's OK in this, case, but please do not increase vertical spacing too much in VMUI components - instead, it is better trying to reduce it in order to avoid vertical scrolling.

**Comment by hagen1778** [comment]
I agree, that we should always care about user experience. In this case, vertical spacing was important to distinguish trace branches of the same level one from another. I really like how it looks now with changes by @Loori-R .

**Comment by valyala** [comment]
FYI, this pull request has been included in [vmui](https://docs.victoriametrics.com/#vmui) starting from [v1.100.0](https://docs.victoriametrics.com/changelog/).

**Pull request merged**
