### PR TITLE
docs/CaseStudies.md: add case study for zhihu

### PR DESCRIPTION
**Pull request by faceair**

### CODE REVIEW

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@faceair , thanks for cool case study!

**Comment by hagen1778** [comment]
Hello @faceair! Just noticed the case study and it looks impressive! I have a question, though. Is the number of active time series correct? If so, what is the cluster size? Thanks!

**Comment by faceair** [comment]
image
Sorry, the real number is 25 million, I wrote it wrong. It's running on a 36-core CPU, 128g RAM, RAID 50 HDD machine.

**Comment by hagen1778** [comment]
Thanks! It has been fixed in the following commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/43552fa8d3d0d21bfd66526c49cbfd77e2807031

**Pull request merged**
