### PR TITLE
Fix/vmagent multi queues may fail

### PR DESCRIPTION
**Pull request by xbsura**
Because cond.Signal() is not a sync method, so the MustWriteBlock may acquire Lock after Signal() before wait wake up, at this time, the len == 1 condition will always fail, which cause only one client worker running, if pending data is a lot, pending data will keep growing

In fact, this happens multi times every day in one of our agent...

Just make == to >= is not a perfect solution as if peningblock remain in memory, Signal() will keep running, which may cost some cpu

A better way need a number as max reader init in fq, and a running number as readers state, init as max, and before Wait(), decrease it, after Wait(), increase it, Writer will check if state is smaller than max, try Signal()

But this solution may cause other problem, and more complex, I will make another pr for this, thanks

### CODE REVIEW

**Comment by xbsura** [comment]
I finished another pr, but a littile ugly, maybe we'd better not consider it

If we just replace == to >=, which may cost a little cpu, and waste some Signal() in limited scene, but this can make worker always keep queues if data is a lot

**Comment by valyala** [comment]
@xbsura , the solution looks good overall, i.e. it consistently unblocks all the existing readers, which should help with faster queue draining. Thanks for the pull request!

**Comment by valyala** [comment]
A made a similar change in the `persistentqueue.Queue` as well, removed always-true condition around `cond.Signal()` call and added `cond.Broadcast()` after flushing in-memory data to persistent queue in order to wake up all the readers. See 4e850cd6a7a556471ec956aa370fabceda4cb77c for details.

**Comment by valyala** [comment]
FYI, the [v1.35.5](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) release includes both the original and the updated commit.

**Pull request merged**
