### PR TITLE
Ensure that each time series has one and only one metric id.

### PR DESCRIPTION
**Pull request by rtm0**
### Describe Your Changes

This change adresses the case when more than one metric ID is created for a single time series. This happens when data for a new time series is inserted concurrently. An example use case is when a lot of historical data is imported into the database.

For example, say we have a year of temperature registered across the globe:

```
# day 1

T{la="90", lo="0"} -10 2023-01-01
T{la="90", lo="0.25"} -10 2023-01-01
...
T{la="-90", lo="359.75"} -10 2023-01-01

# day 2

T{la="90", lo="0"} -9 2023-01-02
T{la="90", lo="0.25"} -9 2023-01-02
...
T{la="-90", lo="359.75"} -9 2023-01-02

# day 365

T{la="90", lo="0"} -11 2023-12-31
T{la="90", lo="0.25"} -11 2023-12-31
...
T{la="-90", lo="359.75"} -11 2023-12-31
```

If we import each day concurrently, then the same new time series will be imported concurrently. Since these time series do not exist in db yet, they are not present in tsdbCache nor in indexdb, which means that the slow insertion path will take place for them (see Storage.add() func) and each metric will get a new metric ID even though the metric has already been seen.

This is an uncommon use case and is should not be observerd under normal circumstances.

The key precondition here is that new time series need to be inserted concurrently, if they are inserted sequentially or concurrently but within one day, duplicates won't be created. The `TestEachTimeSeriesHasOneUniqueMetricID` addresses these three cases.

To show the effect of such concurrent insertion, the patch also provides a benchmark. Here are the results before the fix (the number of duplicates grows as concurrency grows):

```
user@laptop:~/p/github.com/rtm0/VictoriaMetrics/01/src$ GOMAXPROCS=32 go test -run=^$ -bench=StorageAddHistoricalRowsConcurrently ./lib/storage/ -loggerLevel=ERROR; sync
goos: linux
goarch: amd64
pkg: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage
cpu: 13th Gen Intel(R) Core(TM) i7-1355U
BenchmarkStorageAddHistoricalRowsConcurrently/1-32            30          40288038 ns/op           2482126 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/2-32            24          41880760 ns/op           2387731 rows/s             1766 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/4-32            30          38699310 ns/op           2584025 rows/s             1930 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/8-32            31          36784672 ns/op           2718524 rows/s             2582 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/16-32           32          34991868 ns/op           2857807 rows/s             2468 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/32-32           32          35449259 ns/op           2820933 rows/s             2572 ts-ids             1000 ts-names
PASS
ok      github.com/VictoriaMetrics/VictoriaMetrics/lib/storage  20.766s
```

And the result after the fix (duplicate metric IDs are not created):

```
user@laptop:~/p/github.com/rtm0/VictoriaMetrics/01/src$ GOMAXPROCS=32 go test -run=^$ -bench=StorageAddHistoricalRowsConcurrently ./lib/storage/ -loggerLevel=ERROR; sync
goos: linux
goarch: amd64
pkg: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage
cpu: 13th Gen Intel(R) Core(TM) i7-1355U
BenchmarkStorageAddHistoricalRowsConcurrently/1-32            24          41935214 ns/op           2384631 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/2-32            28          40869791 ns/op           2446795 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/4-32            30          39618185 ns/op           2524093 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/8-32            26          38496418 ns/op           2597644 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/16-32           32          36164710 ns/op           2765127 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/32-32           32          36914587 ns/op           2708956 rows/s             1000 ts-ids             1000 ts-names
PASS
ok      github.com/VictoriaMetrics/VictoriaMetrics/lib/storage  19.344s
``` 

The benchmark also attemps to measure row insertion rate (see `rows/s` metric values) to see which performance penalty this fix might introduce although the numbers do not look definite enough. The fix introduces a critical section into the insertion path so the it must become slower. Here are the result of a real-world import of a dataset containing `6229440` unique time series.

Import time before fix: `1m56s`
Import time after fix: `2m8s`

That's `10%` slower.

Let's also look at the metrics.

Before the fix, the number of new time series created equals the number the insertion took the slow path:

```
vm_new_timeseries_created_total 15247877
vm_slow_row_inserts_total 15247877
```

After the fix, the number of new time series is exactly `6229440`, but the number of times the slow path was taken is `10%` bigger.

```
vm_new_timeseries_created_total 6229440
vm_slow_row_inserts_total 16775134
```

### Checklist

The following checks are **mandatory**:

- [ x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by rtm0** [comment]
Import and benchmark results after addressing code review remarks:

## Before the fix

Import time: `2m9s`

Metrics:

```
vm_new_timeseries_created_total 15941451
vm_slow_row_inserts_total 15941451
vm_slow_per_day_index_inserts_total 1184
```

Benchmark:

```
user@laptop:~/p/github.com/rtm0/VictoriaMetrics/01/src$ sync; sudo sysctl -w vm.drop_caches=3; GOMAXPROCS=32 go test -run=^$ -bench=StorageAddHistoricalRowsConcurrently ./lib/storage/ -loggerLevel=ERROR
vm.drop_caches = 3
goos: linux
goarch: amd64
pkg: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage
cpu: 13th Gen Intel(R) Core(TM) i7-1355U
BenchmarkStorageAddHistoricalRowsConcurrently/1-32            28          39313259 ns/op           2543671 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/2-32            28          39160446 ns/op           2553597 rows/s             1591 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/4-32            32          39268187 ns/op           2546591 rows/s             1846 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/8-32            31          37131695 ns/op           2693117 rows/s             2522 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/16-32           31          34102306 ns/op           2932353 rows/s             2564 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/32-32           31          38397385 ns/op           2604344 rows/s             2710 ts-ids             1000 ts-names
PASS
ok      github.com/VictoriaMetrics/VictoriaMetrics/lib/storage  22.278s
```

## After the fix

Import time: `2m7s`

Metrics:

```
vm_new_timeseries_created_total 6229440
vm_slow_row_inserts_total 34132319
vm_slow_per_day_index_inserts_total 869
```

Benchmark:

```
user@laptop:~/p/github.com/rtm0/VictoriaMetrics/01/src$ sync; sudo sysctl -w vm.drop_caches=3; GOMAXPROCS=32 go test -run=^$ -bench=StorageAddHistoricalRowsConcurrently ./lib/storage/ -loggerLevel=ERROR
[sudo] password for user: 
vm.drop_caches = 3
goos: linux
goarch: amd64
pkg: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage
cpu: 13th Gen Intel(R) Core(TM) i7-1355U
BenchmarkStorageAddHistoricalRowsConcurrently/1-32            28          40022015 ns/op           2498625 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/2-32            28          39484298 ns/op           2532652 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/4-32            26          39230817 ns/op           2549017 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/8-32            31          37861286 ns/op           2641220 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/16-32           32          33812489 ns/op           2957487 rows/s             1000 ts-ids             1000 ts-names
BenchmarkStorageAddHistoricalRowsConcurrently/32-32           26          39254135 ns/op           2547502 rows/s             1000 ts-ids             1000 ts-names
PASS
ok      github.com/VictoriaMetrics/VictoriaMetrics/lib/storage  19.808s
```

**Comment by hagen1778** [comment]
Thanks for the patch @rtm0 !

> If we import each day concurrently, then the same new time series will be imported concurrently. 

I know that vmctl does concurrent ingestion of historical data, but in per-metric-name fashion. This helps to properly utilize VM indexes and improves data locality during background merges. Could this be helpful for your case as well?

**Comment by rtm0** [comment]
Hi @hagen1778!

> I know that vmctl does concurrent ingestion of historical data, but in per-metric-name fashion. This helps to properly utilize VM indexes and improves data locality during background merges. Could this be helpful for your case as well?

That certainly helps. But what I've learned is that duplicate metric IDs is not a big deal. This PR is the result of my getting acquainted with the code base, i.e. mostly educational. However I may increase the accuracy of the numbers on the `Explore Cardinality` page of the vmui. Note that even wit this fix that page would still show inaccurate numbers since another source of inaccuracy is the creation of per-date indexes. This may or may not be addressed in the subsequent PRs.

**Comment by hagen1778** [comment]
>  However I may increase the accuracy of the numbers on the Explore Cardinality page of the vmui. Note that even wit this fix that page would still show inaccurate numbers since another source of inaccuracy is the creation of per-date indexes. This may or may not be addressed in the subsequent PRs.

True. But I don't think that attempts to make things more accurate for edge cases cost 10% of the ingestion performance for all cases. 

I'm closing this PR as it won't be merged because of the performance penalties it implies. Thanks for your efforts!

**Pull request closed without merging**
