### PR TITLE
app/vmalert: extend metrics set exported by `vmalert` #573

### PR DESCRIPTION
**Pull request by hagen1778**
New metrics were added to improve observability:
+ vmalert_alerts_pending{alertname, group} - number of pending alerts per group
per alert;
+ vmalert_alerts_acitve{alertname, group} - number of active alerts per group
per alert;
+ vmalert_alerts_error{alertname, group} - is 1 if alertname ended up with error
during prev execution, is 0 if no errors happened;
+ vmalert_recording_rules_error{recording, group} - is 1 if recording rule
 ended up with error during prev execution, is 0 if no errors happened;
* vmalert_iteration_total{group, file} - now contains group and file name labels.
This should improve control over specific groups;
* vmalert_iteration_duration_seconds{group, file} - now contains group and file name labels. This should improve control over specific groups;

Some collisions for alerts and recording rules are possible, because neither
group name nor alert/recording rule name are unique for compatibility reasons.

Commit contains list of TODOs for Unregistering metrics since groups and rules
are ephemeral and could be removed without application restart. In order to
unlock Unregistering feature corresponding PR was filed - https://github.com/VictoriaMetrics/metrics/pull/13

### CODE REVIEW

**Comment by valyala** [comment]
@hagen1778 , the https://github.com/VictoriaMetrics/metrics/pull/13 has been merged, so you can update this PR.

**Comment by hagen1778** [comment]
Thanks! Unfortunately new bug appeared in `metrics` package that must be solved before merging. Pls see https://github.com/VictoriaMetrics/metrics/pull/16

The change contains hot-config reload support for rules/groups metrics. Consider the case when one or more rule were added or removed from the group, or whole group was added or removed without app restart. In this case we expect from `vmalert` to expose only current rules metrics and cleanup old ones. Pls keep that in mind during the review.

Another tricky thing is having an ID label in rules metrics. This is important since having rules with the same name within one group is a common practice. The k8s rules is a good example. I understand, that having ID label results into high cardinality but we need to accept if we want per-rule metrics. We probably should consider to make per-rule metrics exposure optional.

@valyala @tenmozes ^

**Comment by valyala** [comment]
>  I understand that having ID label results into high cardinality but we need to accept it if we want per-rule metrics. We probably should consider to make per-rule metrics exposure optional.

It is OK to have distinct ID label per rule, since the number of rules is usually limited. Let's add rule ID label unconditionally and then see whether it needs to be removed with optional config option (or command-line flag).

**Comment by valyala** [comment]
FYI, the https://github.com/VictoriaMetrics/metrics/pull/16 has been merged into VictoriaMetrics in the commit 807c2b076cce72de43ee9f84a6e52dcadec0df8c

**Comment by hagen1778** [comment]
Looks like all tests are passing now when I merged with master. Open for review now

**Comment by valyala** [comment]
Thanks!

**Pull request merged**
