### PR TITLE
#5833 Fix Deadlock when using shardByURL of VMAgent

### PR DESCRIPTION
**Pull request by penguinlav**

### CODE REVIEW

**Review by masv87 — APPROVED** [review]

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5833

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@penguinlav , thanks for the bugfix!

**Comment by valyala** [comment]
FYI, this bugfix has been included in [v1.93.13 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.13).

**Comment by valyala** [comment]
FYI, this bugfix has been included in [v1.97.3 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.97.3).

**Comment by valyala** [comment]
FYI, this bugfix has been included in [v1.99.0 release](https://docs.victoriametrics.com/changelog/).

**Pull request merged**
