### PR TITLE
app/vmui: bundle web fonts for self-contained offline use

### PR DESCRIPTION
**Pull request by ScottKevill**
Including vmui's web fonts in its bundle (via [Fontsource](https://github.com/fontsource/fontsource)) allows it to run fully self-contained for offline use. These were the only external requests being made by vmui.

Bundling Lato and Jetbrains Mono increases the binary size by 216KB.

The font-weight of `300` for Lato was not actually being used, so I've removed that.

The styles also had two references to font-weight `500` and one reference to `600`, despite neither of those weights being specified in the original external requests. It wasn't clear if this was intentional (perhaps to be used in the case of fallback fonts), so I haven't changed those, but they should probably be changed to `normal` (ie. `400`) and `bold` (ie. `700`) respectively as that is what browsers display now. Lato's full set of weights is `100`, `300`, `400`, `700` and `900`.

### CODE REVIEW

**Comment by valyala** [comment]
@ScottKevill , thanks for the pull request! I think we need mimizing the number of external fonts used in VMUI (ideally, zero external fonts should be used, e.g. use only systems fonts). This will reduce both binary size and the size of font files, which need to be downloaded by web browser during initial VMUI load. @Loori-R , could you look into this pull request and this idea?

**Comment by ScottKevill** [comment]
Even better. :)

FWIW, I'm not that familiar with font subsetting, but watching the network tab with the cache disabled, the browser only seemed to request the `lato-latin-400-normal`, `lato-latin-700-normal`, and `jetbrains-mono-latin-400-normal` files. With the others excluded, it's a 147KB difference rather than 216KB.

Another option could be to leave the styles preferring Lato and Jetbrains Mono, but not bundle or request them either. If the user already has them installed on their system, they would be used, otherwise the fallback system font choices. I don't know how likely that is to be worth bothering with though.

**Comment by valyala** [comment]
@Loori-R created and merged https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3705 on top of this pull request. Then closing this one.

**Comment by valyala** [comment]
FYI, `vmui` embeds fonts starting from [v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Pull request closed without merging**
