### PR TITLE
vmui: add responsive styles for small screens

### PR DESCRIPTION
**Pull request by Loori-R**
- add wrapping controls on small screens
- #3239

For example 960x886:

### CODE REVIEW

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Loori-R , could you resolve merge conflicts before merging? Could you also add a FEATURE entry to docs/CHAGNELOG.md for this change?

**Comment by Loori-R** [comment]
@valyala updated

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Loori-R , thanks for the pull request!

**Comment by valyala** [comment]
FYI, this pull request has been included in [vmui v1.83.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Pull request merged**
