### PR TITLE
[cluster/vminsert]:add reload -relabelConfig on the request to /-/reload

### PR DESCRIPTION
**Pull request by z-anshun**
When I use vminsert's  `relabelConfig`, I found that now there is no reloaded api. However, `vminsert` under `VM-Single` has it. So, I hope to add it to the `cluster/vminster`.

### CODE REVIEW

**Review by hagen1778 — APPROVED** [review]
LGTM

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by z-anshun** [comment]
@valyala ,please help review the code.

**Comment by z-anshun** [comment]
> The code looks good except one thing - usually the cluster contains multiple `vminsert` nodes hidden behind a load balancer. So the load balancer sends every request to `/-/reload` to different `vminsert` node. This may lead to inconsistent state at `vminsert` nodes, where different `vmagent` nodes have different relabeling configs. This adds confusion on how to properly reload relabeling configs at `vminsert` nodes. That's why the `/-/reload` endpoint wasn't added to `vminsert`. Right now it is possible to reload relabeling configs at `vminsert` nodes by sending `SIGHUP` signal to them.
> 
> So I'm not sure this is a good enhancement. Probably, it would be better adding an option such as `-relabelConfigCheckInterval` in the way similar to `-promscrape.configCheckInterval` at `vmagent`.

@valyala greate.I think add

> The code looks good except one thing - usually the cluster contains multiple `vminsert` nodes hidden behind a load balancer. So the load balancer sends every request to `/-/reload` to different `vminsert` node. This may lead to inconsistent state at `vminsert` nodes, where different `vmagent` nodes have different relabeling configs. This adds confusion on how to properly reload relabeling configs at `vminsert` nodes. That's why the `/-/reload` endpoint wasn't added to `vminsert`. Right now it is possible to reload relabeling configs at `vminsert` nodes by sending `SIGHUP` signal to them.
> 
> So I'm not sure this is a good enhancement. Probably, it would be better adding an option such as `-relabelConfigCheckInterval` in the way similar to `-promscrape.configCheckInterval` at `vmagent`.

@valyala very good. I found that `vmagent` has `-promscrape.configCheckInterval` and `/-/reload`, so I thought it would be better to add both of them to `vminert`.

**Comment by z-anshun** [comment]
@valyala ,please review

**Comment by Haleygo** [comment]
>This may lead to inconsistent state at vminsert nodes, where different vmagent nodes have different relabeling configs.

@valyala I'm not quite understand your point here. As you said, component like vmagent or vmalert already have this `/-/reload` endpoint, all of them can get inconsistent state if user put load balancer in front of them and use it to perform reloading. So it's a generic wrong operation for reloading multiple instances.
The right move here should be putting a sidecar for each instance, like in k8s, it's common to having a config-reloader container as sidecar along with the service, so each instance will be updated when the config changed.
I think we should expose this `/-/reload` for vminsert, since it gives user an option to do so, instead of waiting for  `configCheckInterval`.

**Comment by f41gh7** [comment]
Thanks for contribution!

**Comment by valyala** [comment]
> component like vmagent or vmalert already have this /-/reload endpoint, all of them can get inconsistent state if user put load balancer in front of them and use it to perform reloading. So it's a generic wrong operation for reloading multiple instances.

There is usually a single `vmagent` and `vmalert` instance in typical VictoriaMetrics observability setups. There may be a pair of `vmagent` / `vmalert` instances in HA setups. Other cases with many `vmagent` / `vmalert` instances are very rare. These cases may occur if a single `vmagent` / `vmalert` instance cannot keep up with the workload. In these cases every `vmagent` instance usually has distinct configs, including the `-relabelConfig`, since it processes some subset of the whole workload. In this case it is OK to send individual request to `/-/reload` per each instance after its' config changes. This also means that these distinctly configured `vmagent` / `vmalert` instances aren't put in a single load balancing group for accessing their web IUs such as [`/targets` page](https://docs.victoriametrics.com/vmagent/#debugging-scrape-targets) at `vmagent`, since this makes impossible targets' debugging.

There are usually many `vminsert` instances in a typical VictoriaMetrics cluster. All these instances have identical configuration, including the `-relabelConfig` one. These instances are usually put in a single load balancing group for accessing [HTTP data ingestion APIs](https://docs.victoriametrics.com/cluster-victoriametrics/#url-format). It isn't OK to request `/-/reload` endpoint via this load balancing group, since it doesn't guarantee that the endpoint will be eventually called across all the `vminsert` nodes.

> The right move here should be putting a sidecar for each instance, like in k8s, it's common to having a config-reloader container as sidecar along with the service, so each instance will be updated when the config changed.
I think we should expose this /-/reload for vminsert, since it gives user an option to do so, instead of waiting for configCheckInterval.

While this sounds good, it is easier and more clear to the end user to just restart `vminsert` nodes whenever the `-relabelConfig` contents changes. This can be done by the config-reloader sidecar or in any other suitable way.

So let's don't add `/-/reload` endpoint to `vminsert` nodes, since it brings more confusion to VictoriaMetrics users, without improving its' usability.

**Pull request merged**
