### PR TITLE
migrated to yaml.v3

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
### Describe Your Changes

Fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6081

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by hagen1778** [comment]
@AndrewChubatiuk am I right to assume the only benefit of having yamlv3 is support of anchors?

**Comment by AndrewChubatiuk** [comment]
here's a full list of changes
https://ubuntu.com/blog/api-v3-of-the-yaml-package-for-go-is-available

**Comment by hagen1778** [comment]
So far it is unclear to me if this change is needed:
* it doesn't solve https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3117. Using anchors still requires `--promscrape.config.strictParse=false`
* https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6081 doesn't provide a specific reason for updating, appealing only to activity of the project.

**Comment by AndrewChubatiuk** [comment]
looks like anchoring is already supported by yaml.v2, I've modified an example in issue to make it working

**Comment by hagen1778** [comment]
> looks like anchoring is already supported by yaml.v2, I've modified an example in issue to make it working

Thanks! So far I can find the reasons to update to v3. Do you? If not, let's keep this change on hold.

**Pull request closed without merging**
