### PR TITLE
app/victoriametrics: update the test suite

### PR DESCRIPTION
**Pull request by hagen1778**
* simplify /query and /query_range test cases configuration and tests
* support instant queries with lookbehind window like `query=foo[5m]`
* support instant queries selecting scalar value like `query=42`
* add query_range test for prometheus

### CODE REVIEW

**Review by tenmozes — APPROVED** [review]

**Comment by tenmozes** [comment]
```
2024-01-16T19:31:02.748Z	info	VictoriaMetrics/app/vmselect/querystats/querystats.go:68	enabled query stats tracking at `/api/v1/status/top_queries` with -search.queryStats.lastQueriesCount=20000, -search.queryStats.minQueryDuration=1ms
--- FAIL: TestWriteRead (1.06s)
    --- FAIL: TestWriteRead/read (0.03s)
        --- FAIL: TestWriteRead/read/graphite (0.00s)
            --- FAIL: TestWriteRead/read/graphite/subquery-aggregation (0.01s)
                main_test.go:338: "/api/v1/query?query=min%20by%20(item)%20(min_over_time(forms_daily_count[10m:1m]))&time=1705433400&latency_offset=1ms" fails with error expected metrics [{Metric:map[item:x] Values:[2] Timestamps:[1705433400]} {Metric:map[item:y] Values:[4] Timestamps:[1705433400]}] not found in [{Metric:map[item:x] Values:[1] Timestamps:[1705433400]} {Metric:map[item:y] Values:[3] Timestamps:[1705433400]}].
                    Regression in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/184

```
failed test :)

**Review by tenmozes — APPROVED** [review]

**Comment by hagen1778** [comment]
> failed test :)

Looks like a flaky test. Re-run fixed it. I also remember seeing this failed test a couple of times before.

**Comment by tenmozes** [comment]
it happens again 

```
-search.queryStats.lastQueriesCount=20000, -search.queryStats.minQueryDuration=1ms
--- FAIL: TestWriteRead (1.12s)
    --- FAIL: TestWriteRead/read (0.07s)
        --- FAIL: TestWriteRead/read/graphite (0.00s)
            --- FAIL: TestWriteRead/read/graphite/subquery-aggregation (0.02s)
                main_test.go:338: "/api/v1/query?query=min%20by%20(item)%20(min_over_time(forms_daily_count[10m:1m]))&time=1705570140&latency_offset=1ms" fails with error expected metrics [{Metric:map[item:x] Values:[2] Timestamps:[1705570140]} {Metric:map[item:y] Values:[4] Timestamps:[1705570140]}] not found in [{Metric:map[item:x] Values:[1] Timestamps:[1705570140]} {Metric:map[item:y] Values:[3] Timestamps:[1705570140]}].
                    Regression in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/184

```

**Comment by hagen1778** [comment]
It happened many times before as well. The test need to be fixed. It is not related to the test suite change.

**Pull request merged**
