### PR TITLE
docs: fix rule unittest rule_files point to alerts.yaml

### PR DESCRIPTION
**Pull request by hvnsweeting**
### Describe Your Changes

Fix wrong path to rules_file in vmalert-tool doc

### Checklist

The following checks are **mandatory**:

- [x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by Haleygo** [comment]
Thanks for the pull request!
Would you mind changing the fix to use `rules.yaml` instead of `alerts.yaml`, since it includes both alerting and recording rules?

**Comment by hvnsweeting** [comment]
sure, updated.

**Comment by hagen1778** [comment]
Related ticket https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7663

**Review by Haleygo — APPROVED** [review]
LGTM!

**Comment by Haleygo** [comment]
Thanks for contribution!

**Pull request merged**
