### PR TITLE
new `|`-operator for metric expression (#3997)

### PR DESCRIPTION
**Pull request by Amper**
issue #3997

### CODE REVIEW

**Comment by groobyming** [comment]
@Amper Looking forward to this new feature very much. Is it still in progress?

**Comment by Amper** [comment]
Hi @groobyming, the feature is completed, but is still awaiting a review from @valyala, he is busy at the moment.

**Comment by groobyming** [comment]
Great！, we are looking forward to the new feature in future versions. Currently, we are facing difficulties migrating our existing influxdb users. @Amper @valyala

**Comment by valyala** [comment]
> I assume this plays well with the optimizer ?

Yes, this feature shouldn't affect [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) optimizer.

**Comment by valyala** [comment]
FYI, the commit 4cb024d8a3a2cdd0b14ee6850770ba114e3537e7 adds support for multiple `or`-delimited series selectors according to [these docs](https://docs.victoriametrics.com/keyConcepts.html#filtering-by-multiple-or-filters).

Closing this pull request then, since it is overridden by the commit 4cb024d8a3a2cdd0b14ee6850770ba114e3537e7 .
The commit is going to be included in the next release. See [the linked issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3997) for details.

**Pull request closed without merging**
