### PR TITLE
app/vmalert: add alert.resolvedRetention flags to configure resolvedRetention

### PR DESCRIPTION
**Pull request by gsakun**
Currently, [resolvedRetention](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/alerting.go#L296) is a constant in the code, but I think it should be made into a configurable option.

### CODE REVIEW

**Comment by Haleygo** [comment]
Hello!
Is there any specific case for you to change `resolvedRetention`? 
I think right now `resolvedRetention` is only a parameter used inside vmalert to reserve alert state and those repeatedly request to AlertManager shouldn't cause any side effect on AlertManager side.

**Comment by gsakun** [comment]
> Hello! Is there any specific case for you to change `resolvedRetention`? I think right now `resolvedRetention` is only a parameter used inside vmalert to reserve alert state and those repeatedly request to AlertManager shouldn't cause any side effect on AlertManager side.

Actually, in my case, I'm not using Alertmanager. I'm integrating vmalert with our own service. In my specific use case, 15 minutes is too long, and I think this value should not be hardcoded. It should be configurable.

**Comment by Haleygo** [comment]
> > Hello! Is there any specific case for you to change `resolvedRetention`? I think right now `resolvedRetention` is only a parameter used inside vmalert to reserve alert state and those repeatedly request to AlertManager shouldn't cause any side effect on AlertManager side.
> 
> Actually, in my case, I'm not using Alertmanager. I'm integrating vmalert with our own service. In my specific use case, 15 minutes is too long, and I think this value should not be hardcoded. It should be configurable.

So you want to set `resolvedRetention` to 0 to prevent repeatedly request to your own service?

**Comment by gsakun** [comment]
> resolvedRetention

This parameter is determined by our end users, and in the program I'm currently using, I have also added a parameter to control whether inactive alerts are sent. this pull request allows for controlling resolvedRetention based on our specific requirements without affecting the original design, as 15 minutes may not be universally reasonable.

**Comment by gsakun** [comment]
> > > Hello! Is there any specific case for you to change `resolvedRetention`? I think right now `resolvedRetention` is only a parameter used inside vmalert to reserve alert state and those repeatedly request to AlertManager shouldn't cause any side effect on AlertManager side.
> > 
> > 
> > Actually, in my case, I'm not using Alertmanager. I'm integrating vmalert with our own service. In my specific use case, 15 minutes is too long, and I think this value should not be hardcoded. It should be configurable.
> 
> So you want to set `resolvedRetention` to 0 to prevent repeatedly request to your own service?

This parameter is determined by our end users, and in the program I'm currently using, I have also added a parameter to control whether inactive alerts are sent. this pull request allows for controlling resolvedRetention based on our specific requirements without affecting the original design, as 15 minutes may not be universally reasonable.

**Comment by Haleygo** [comment]
I believe vmalert notifier address is initially designed to send notify to alertmanager, which already has the ability to set `sendResolved` and dealing with repeated resolved request. And I think sending resolved message multiple times do more good than harm on vmalert side.
>This parameter is determined by our end users, and in the program I'm currently using, I have also added a parameter to control whether inactive alerts are sent. 

Maybe you can implement this in your system too?

@hagen1778 WDYT?

**Comment by hagen1778** [comment]
The 15min value is there to satisfy [alert-generator-spec](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#conditions-for-sending-inactive-alerts). Allowing to change that might be not intuitive for most of the users, even if explained.
Would it make sense to add a new notification integration instead? 

Let's keep this issue open to see if there are more than one request for this change.

**Pull request closed without merging**
