### PR TITLE
vmui: predefined panels

### PR DESCRIPTION
**Pull request by Loori-R**
Added the ability to add configuration files for predefined dashboards and display them in the interface.

To add a dashboard, create a `.json` file at "app/vmui/packages/vmui/src/dashboards/"
See [this doc](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/vmui-predefined-panels/app/vmui/packages/vmui/src/dashboards#readme) for detailed configuration information.

VMUI automatically detects all .json files from a directory and displays the appropriate tabs in the "Dashboards" section.

### CODE REVIEW

**Comment by valyala** [comment]
This functionality looks amazing! @Loori-R , could you add a pre-defined dashboard in this pull request with the following graphs:
* Per-job CPU usage - `sum(rate(process_cpu_seconds_total)) by (job)`
* Per-job RSS usage - `sum(process_resident_memory_bytes) by (job)`
* Per-job disk read - `sum(rate(process_io_storage_read_bytes_total)) by (job)`
* Per-job disk write - `sum(rate(process_io_storage_written_bytes_total)) by (job)`

This will help with further refining of the dashboards functionality.

**Comment by Loori-R** [comment]
@valyala Thanks. Added your requested predefined dashboard

**Comment by hagen1778** [comment]
Hi @Loori-R! First of all - it looks amazing! Thanks for doing this!
I've tried to compile my own dashboard and here's my notes:
* [ ] [bug]: refresh of the /vmui/dashboards page results into 404
* [ ] [bug]: make "Custom panel" and "dashboards" button as links, so users would be able to open them in a new tab 
* [ ] [bug]: units are cut on the Y-axis: 
Pasted Graphic

* [ ] [bug]: configured units aren't used in the hover-tooltip:


* [ ] [enh]: option to set expression alias. The alias is needed to distinguish series if more than one expression is set. Consider the example of the panel which should show `free` and `used` disk space on the same panel:
Pasted Graphic 2

* [ ] [enh]: is it possible to read predefined panels from some specific folder without the need to rebuild VMUI? The purpose is to have ability to modify dashboards without rebuilding the VMUI. Or having different predefined panels for single/cluster versions of VM with the same VMUI build.
* [ ] [enh]: grid support - option to choose panel width in pre-defined units, which represent the grid system. For example, if full-width panel has `width: 8`, the half-width panel has `width: 4`. Two panels with `width: 4` can be displayed in the same row.

**Comment by hagen1778** [comment]
Looks great @Loori-R! Thank you for doing this!

**Review by hagen1778 — APPROVED** [review]

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
Thanks!

**Comment by thomas725** [comment]
I'd like to use this feature, but:
* I don't know where to find "app/vmui/packages/vmui/src/dashboards/"
* the docs link https://github.com/VictoriaMetrics/VictoriaMetrics/tree/vmui-predefined-panels/app/vmui/packages/vmui/src/dashboards#readme shows me a 404
* https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#vmui doesn't say anything about the Dashboards feature

**Comment by hagen1778** [comment]
@Loori-R could you please assist here?

**Comment by Loori-R** [comment]
Yes, you are right, in this case, the dashboards must be defined before compiling VictoriaMetrics.

You can read this [doc](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmui/packages/vmui/public/dashboards).

Folder `dashboards` must be inside vmui root.

**Comment by hagen1778** [comment]
Hi @Loori-R! Do you think it is possible to implement hot load for dashbaords? How complicated could it be?

**Comment by Loori-R** [comment]
This cannot be done through the frontend. 
The team discussed this task, there are several options, one of them is the cli-option (as described in [comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3322#issuecomment-1307650747))

**Comment by thomas725** [comment]
Hey @Loori-R , thank you for acknowledging my suggestion as an option how dashboards could be modified after compilation of the single-server binary!

Does your team consider implementing this or one of the other (for me unknown) options that could make the vmui dashboard feature available to users of the single-server binary releases?

**Pull request merged**
