### PR TITLE
Vmstorage/group-storage

### PR DESCRIPTION
**Pull request by IceRain00**

### CODE REVIEW

**Comment by IceRain00** [comment]
The info this merge as follow: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/572

**Comment by xbsura** [comment]
review remind

**Comment by xbsura** [comment]
review remind

**Comment by valyala** [comment]
Closing this pull request, since it has been overridden by https://github.com/VictoriaMetrics/VictoriaMetrics/pull/640

**Pull request closed without merging**
