### PR TITLE
stream aggregation add output function sum_samples_positive

### PR DESCRIPTION
**Pull request by leiwingqueen**
### Describe Your Changes

I need to make an alert when pod terminated using the metrics "kube_pod_container_status_terminated_reason" collected from kube-state-metrics. Unfortunately, the count of metrics is too large and it will cost many time to query(there is 300_000 metrics per minute). The only valuable metric is the metric that value bigger than zero. So I want to add a aggregation function that only report positive value to vminsert.

here is my record rule file.

``` yaml
- record: kube_pod_container_status_terminated_reason:sum_over_5m
        expr: |
          sum by (namespace, pod, container, instance, reason) (
            sum_over_time(kube_pod_container_status_terminated_reason{}[5m])
          )
```

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by Haleygo** [comment]
Hi,
As I understand, the `kube_pod_container_status_terminated_reason` should only be reported for pod that currently in terminated state, such as `kube_pod_container_status_terminated_reason{instance="10.71.3.3:8080",job="kube-state-metrics",pod="xxx-6c7f9b6b8b-mpr6z",reason="**OOMKilled**",service="kube-state-metrics",uid="92cfc17a-e989-4898-bd6f-15b3ed04c855"}   1`. 
This metric should not be reported by KSM once the pod either returns to running state or is deleted, so there shouldn't be metric `kube_pod_container_status_terminated_reason` with value 0. I'm wonder why you have 300_000 of them, are they all stay in the terminated states, which version of kube-state-metrics you're using?

**Comment by leiwingqueen** [comment]
> Hi, As I understand, the `kube_pod_container_status_terminated_reason` should only be reported for pod that currently in terminated state, such as `kube_pod_container_status_terminated_reason{instance="10.71.3.3:8080",job="kube-state-metrics",pod="xxx-6c7f9b6b8b-mpr6z",reason="**OOMKilled**",service="kube-state-metrics",uid="92cfc17a-e989-4898-bd6f-15b3ed04c855"} 1`. This metric should not be reported by KSM once the pod either returns to running state or is deleted, so there shouldn't be metric `kube_pod_container_status_terminated_reason` with value 0. I'm wonder why you have 300_000 of them, are they all stay in the terminated states, which version of kube-state-metrics you're using?

thanks for reply.

KSM version: v1.9.5

here is KSM metrics return
```json
{__name__="kube_pod_container_status_terminated_reason", cluster="xxx", clusterId="11", container="metis", endpoint="https-main", instance="10.20.7.109:8443", job="kube-state-metrics-main", namespace="oss", pod="metis-v2-8-t-20220803171951-7bc4c6965-252zd", reason="Error"} 0
{__name__="kube_pod_container_status_terminated_reason", cluster="xxx", clusterId="11", container="metis", endpoint="https-main", instance="10.20.7.109:8443", job="kube-state-metrics-main", namespace="oss", pod="metis-v2-8-t-20220803171951-7bc4c6965-252zd", reason="Evicted"} 0
{__name__="kube_pod_container_status_terminated_reason", cluster="xxx", clusterId="11", container="metis", endpoint="https-main", instance="10.20.7.109:8443", job="kube-state-metrics-main", namespace="oss", pod="metis-v2-8-t-20220803171951-7bc4c6965-252zd", reason="Completed"} 1
{__name__="kube_pod_container_status_terminated_reason", cluster="xxx", clusterId="11", container="metis", endpoint="https-main", instance="10.20.7.109:8443", job="kube-state-metrics-main", namespace="oss", pod="metis-v2-8-t-20220803171951-7bc4c6965-252zd", reason="OOMKilled"} 0

```

only the metrics which value>0 is valuable.

**Comment by leiwingqueen** [comment]
> Regarding this feature, I think `sum_samples_positive` output has limited use cases, but it could be very useful to support general **value filter** like
> 
> ```
> - match: 'room_temperature'
>   interval: 5m
>   outputs: [avg]
>   threshold: 0      // samples that have `value < 0` will be ignored
> ```
> 
> It allows user to filter out unwanted or anomalous values in advance, to get more accurate results or store less data to the storage. wdyt? cc @hagen1778

good idea. maybe I can fix it

**Comment by Haleygo** [comment]
>KSM version: v1.9.5

@leiwingqueen v1.9.5 is released in 2020, and `kube_pod_container_status_terminated_reason` in this version is very bloated, as only the value 1 is useful, the others unnecessarily increase pressure on the TSDB. 
So I'd recommend to upgrade to the latest [v2.13.0 / 2024-07-19](https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.13.0)(I'm not sure this improvment starts from which version), which improves this situation by not exposing any meaningless metrics like `{__name__="kube_pod_container_status_terminated_reason", cluster="xxx", clusterId="11", container="metis", endpoint="https-main", instance="10.20.7.109:8443", job="kube-state-metrics-main", namespace="oss", pod="metis-v2-8-t-20220803171951-7bc4c6965-252zd", reason="Error"} 0`.

**Comment by leiwingqueen** [comment]
> > Regarding this feature, I think `sum_samples_positive` output has limited use cases, but it could be very useful to support general **value filter** like
> > ```
> > - match: 'room_temperature'
> >   interval: 5m
> >   outputs: [avg]
> >   threshold: 0      // samples that have `value < 0` will be ignored
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It allows user to filter out unwanted or anomalous values in advance, to get more accurate results or store less data to the storage. wdyt? cc @hagen1778
> 
> good idea. maybe I can fix it

I create a PR to fix it. https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6722

**Pull request closed without merging**
