### PR TITLE
docs/api corrected broken links to Kubernetes documentation 

### PR DESCRIPTION
**Pull request by greynix**
the links to the Kubernetes documentation have changed the version from v1.22 to v1.27

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Could you sign commit and force push it?

**Comment by greynix** [comment]
> Could you sign commit and force push it?
done

**Comment by f41gh7** [comment]
Thanks for contribution!

**Pull request merged**
