### PR TITLE
vmui/logs: add display top streams in the hits graph

### PR DESCRIPTION
**Pull request by Loori-R**
### Describe Your Changes

- Adds support for displaying the top 5 log streams in the hits graph, grouping the remaining streams into an "other" label.
   #6545

- Adds options to customize the graph display with bar, line, stepped line, and points views.

### Checklist

The following checks are **mandatory**:

- [x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by hagen1778** [comment]
@Loori-R could you please rebase this PR on master branch?

**Comment by hagen1778** [comment]
@dmitryk-dk I would appreciate your review

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Review by hagen1778 — APPROVED** [review]
Thanks!

**Pull request merged**
