### PR TITLE
vmui: fix app routing issues

### PR DESCRIPTION
**Pull request by Loori-R**
This pull request focuses on rectifying inconsistencies in the navigation behavior of the application and eliminating issues encountered when manually altering the URL.

The key updates include:

- Refactoring of the routing mechanism to handle all possible routes and their states.
- Enhancement of the React Router usage to ensure a smoother navigation experience.
- Handling application state when the URL is manually changed.

### CODE REVIEW

**Comment by hagen1778** [comment]
@dmitryk-dk would you mind taking a look?

**Comment by hagen1778** [comment]
@Loori-R can I request a practical example when URL editing failed in past and is successful within this change?

**Comment by Loori-R** [comment]
> @Loori-R can I request a practical example when URL editing failed in past and is successful within this change?

#### Example 1
1. Go to the tab [WITH template](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/expand-with-exprs)
2. Then go to the `Trace analyzer` tab
3. Press the back button in your browser
4. It is expected that we will return to the WITH template tab, but in the current version, the page will not change.

<br/>

#### Example 2
1. Open the [chart with query = "1"](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=1&g0.range_input=30m&g0.end_input=2023-06-09T17%3A21%3A21&g0.relative_time=last_30_minutes)
2. Manually change the url to https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=2&g0.range_input=30m&g0.end_input=2023-06-09T17%3A21%3A21&g0.relative_time=last_30_minutes
4. It is expected that a chart with query = "2" will open, but in the current version, the page will not change.

**Review by dmitryk-dk — APPROVED** [review]

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html).

**Pull request merged**
