### PR TITLE
vmui: enhancements multiline field editing

### PR DESCRIPTION
**Pull request by Loori-R**
### Changes

- Fixed the encoding issue for `with templates` requests. This fixes the issue described in this [#3811 (comment)](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3811#issuecomment-1539629676).
- Implemented saving the inputted value of `with template` into the URL. This fixes the issue described in this [#3811 (comment)](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3811#issuecomment-1539629676).
- Modified the behavior of inputs to align with the requested changes outlined in [#4294 (comment)](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4294#issuecomment-1553513578). Related [#3811 (comment)](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3811#issuecomment-1539633751) and [#3807 (comment)](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3807#issuecomment-1539635918).
- Replaced the textarea with the Monaco Editor on the `Metric relabel debug` page.

### CODE REVIEW

**Review by dmitryk-dk — COMMENTED** [review]
Overall looks good! But I see that relabel config field doesn't validate the yaml. If it is expected so, I have no other comment. If yaml's should be checked, so I think we should add this validation.

**Comment by Loori-R** [comment]
> Overall looks good! But I see that relabel config field doesn't validate the yaml. If it is expected so, I have no other comment. If yaml's should be checked, so I think we should add this validation.

To enable Monaco to perform syntax checking, additional configuration is required for the schema. Validation is currently handled on the server side, but if needed, we can consider adding client-side validation at a later stage.

**Review by dmitryk-dk — APPROVED** [review]

**Comment by valyala** [comment]
> Standardized the behavior for all multiline fields. Pressing Enter now results in a line break, while combinations of Shift + Enter or Ctrl/Cmd + Enter will execute the query

Note that the `Enter` keypress in the query field should result in query execution at the main vmui page, since the majority of queries entered by users are single-line queries.

**Comment by valyala** [comment]
Also, `shift-enter` shouldn't execute the query - it should add an additional line in input query field. Only `ctrl+enter` should execute the query.

**Comment by valyala** [comment]
@Loori-R , could you address comments at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4294#issuecomment-1546473197  and https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4294#issuecomment-1546473552 ?

In summary:

All the single-line inputs in VMUI must have the following behaviour:
  - if `enter` is pressed, then perform the default action (e.g. send the request to the server)
  - if `shift-enter` is pressed, then convert the single-line input to multi-line input where it makes sense (e.g. when editing the query at the main vmui page).
  - if multi-line text is copied into a single-line input, then automatically switch the single-line input into multi-line input. For example, if multi-line query is copy-n-pasted into single-line query input on the main page.
  - `left` and `right` keys must move the cursor to the left / right in the input field, so users could edit the value in the input field in a usual way (e.g. in the same way as in `<input type="text">` field).

All the multi-line inputs (including the automatically switched single-line inputs) in VMUI must have the following behavior:
  - if `enter` or `shift-enter` is pressed, then add a newline just after the cursor.
  - if `up`, `down`, `left` or `right` keys are pressed, then the standard navigation and editing across multi-line input must performed (e.g. in the same way as in `<textarea>` field).

Both multi-line and single-line inputs must have the following behaviour:
- if `ctrl-enter` is pressed, then the default action must be performed (e.g. to send the request to the server)
- if `ctrl-up` / `ctrl-down` is pressed, then the navigation between previously entered values must be performed by updating the input field.

**Comment by hagen1778** [comment]
Since @valyala has comments on the implementation, I'd wait for his review.

**Comment by Loori-R** [comment]
@valyala Updated considering the comments.

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Loori-R , thanks for the pull request!

**Comment by valyala** [comment]
@Loori-R , the `Metric relabel debug` page now depends on files from Internet after merging this pull request. This is no-go! All the VMUI functionality should work without access to the Internet. Could you fix this? See [the related issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1829).

**Pull request merged**
