### PR TITLE
app/vlinsert: support getting _msg_field, _time_field, _stream_fields and _ignore_fields from headers

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
### Describe Your Changes

- added ability to read params from headers
   ```
   _msg_field -> VL-Msg-Field
   _stream_fields -> VL-Stream-Fields
   _ignore_fields -> VL-Ignore-Fields
   _time_field -> VL-Time-Field
   ```
   
   It helps to allow ingesting data from telegraf to VictoriaLogs
   
- removed deprecations from victorialogs compose files, added more output format examples for logstash, telegraf, fluent-bit

remo

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by AndrewChubatiuk** [comment]
@valyala added [PR](https://github.com/fluent/fluent-bit/pull/8937) to fluent-bit to enable custom headers support for elasticsearch, which enables ability to use fluentbit elasticsearch output for victorialogs as well

**Comment by tenmozes** [comment]
Should fix - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5310

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by valyala** [comment]
FYI, this pull request has been included in [v0.29.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/).

**Pull request merged**
