### PR TITLE
lib/httputils: parse URL before creating HTTP transport

### PR DESCRIPTION
**Pull request by hagen1778**
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6740

### CODE REVIEW

**Comment by Haleygo** [comment]
Also need to fix the address examples [here](https://github.com/search?q=repo%3AVictoriaMetrics%2FVictoriaMetrics%20(e.g.%2C%20127.0.0.&type=code).

**Comment by hagen1778** [comment]
Thanks! Updated

**Review by Haleygo — APPROVED** [review]
LGTM

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Thanks for contribution!

**Pull request merged**
