### PR TITLE
vmui: update package-lock.json

### PR DESCRIPTION
**Pull request by Loori-R**
1. Updated `package-lock.json` to resolve [Dependabot alerts](https://github.com/VictoriaMetrics/VictoriaMetrics/security/dependabot).
2. Updated types to align with the latest `Preact` update.

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Review by hagen1778 — APPROVED** [review]
lgtm

**Review by dima-vm — COMMENTED** [review]
@Loori-R This PR seem to create a lot of errors like:
image

image

**Comment by Loori-R** [comment]
@dima-vm It seems your code is outdated; `StateUpdater` has been replaced everywhere with `Dispatch<SetStateAction>`. Try rebuilding the project.

**Pull request merged**
