### PR TITLE
A good change for MD files

### PR DESCRIPTION
**Pull request by hatamiarash7**
In this PR we have many Markdown files formatted and linted by MD style standards.

- All `docs` markdowns
- Repo related files ( code of conduct, contributing, readme, etc )
- Other MD files in sub-directories
- Format code sections using proper language specifier

I think MD files should be reviewed more than this PR. I can do this if I can ( have more free time )

Also, there are some changes in `docker-compose` file for deploying using Docker

- Format YAML
- Fix `vmalert` starting command for `external.url`

### CODE REVIEW

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@hatamiarash7 , thanks for the pull request!

**Comment by valyala** [comment]
> I think MD files should be reviewed more than this PR. I can do this if I can ( have more free time )

That would be awesome!

**Comment by valyala** [comment]
@hatamiarash7 , it would be great also if you could update `make docs-sync`, so it preforms proper formatting for all the `*.md` files in `docs` and `app` folders. See https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a8de1ab00069bfbb69e67ec142a84c4fa541fbfd/Makefile#L301

**Comment by hatamiarash7** [comment]
> @hatamiarash7 , it would be great also if you could update `make docs-sync`, so it preforms proper formatting for all the `*.md` files in `docs` and `app` folders. See https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a8de1ab00069bfbb69e67ec142a84c4fa541fbfd/Makefile#L301  

It's good idea. I'll go for it.

**Comment by hatamiarash7** [comment]
As I checked the repository, you are using Github actions here. What do you think about the formatting of files in the workflow?

**Pull request merged**
