### PR TITLE
vmui: add link to vmalert 

### PR DESCRIPTION
**Pull request by Loori-R**
### Describe Your Changes

Add link to VMalert when proxy is enabled. The link is displayed when the `-vmalert.proxyURL` flag is present.

#5924

image

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Loori-R , thanks for the pull request!

**Comment by hagen1778** [comment]
@valyala @Loori-R this feature doesn't work in default installation for vm single.
Here's how to reproduce:
1. Check-out to the master branch
2. Run ` make docker-single-up`
3. Navigate to http://localhost:8428/vmui. Observe that header doesn't contain link to Alerts
4. Observe console errors to discover that vmsingle makes request to http://localhost:8428/prometheus/flags and gets error in response. It should make request to http://localhost:8428/flags instead.

For cluster version it won't work if vmselect is behind the balancer. Here's how to reproduce:
1. Check-out to the master branch
2. Run ` make docker-cluster-up`
3. Navigate to http://localhost:8481/select/0/vmui. Observe that header doesn't contain link to Alerts

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7380 has been merged to address https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7088#issuecomment-2391360368

**Pull request merged**
