### PR TITLE
make encoding.MarshalVarInt64s faster

### PR DESCRIPTION
**Pull request by ahfuzhang**
Use `Switch/case` to replace `for`.
go compiler might be use jump table to replace compare.

Before:
=== RUN   BenchmarkMarshalVarInt64s/up-to-(1<<6)-1
BenchmarkMarshalVarInt64s/up-to-(1<<6)-1
BenchmarkMarshalVarInt64s/up-to-(1<<6)-1-10              1551774               686.0 ns/op      11661.55 MB/s          0 B/op          0 allocs/op
=== RUN   BenchmarkMarshalVarInt64s/up-to-(1<<13)-1
BenchmarkMarshalVarInt64s/up-to-(1<<13)-1
BenchmarkMarshalVarInt64s/up-to-(1<<13)-1-10              703304              1759 ns/op        4547.44 MB/s           0 B/op          0 allocs/op
=== RUN   BenchmarkMarshalVarInt64s/up-to-(1<<27)-1
BenchmarkMarshalVarInt64s/up-to-(1<<27)-1
BenchmarkMarshalVarInt64s/up-to-(1<<27)-1-10              362886              3343 ns/op        2393.31 MB/s           4 B/op          0 allocs/op
=== RUN   BenchmarkMarshalVarInt64s/up-to-(1<<63)-1
BenchmarkMarshalVarInt64s/up-to-(1<<63)-1
BenchmarkMarshalVarInt64s/up-to-(1<<63)-1-10              212334              6472 ns/op        1236.18 MB/s          18 B/op          0 allocs/op
PASS
ok      [github.com/VictoriaMetrics/VictoriaMetrics/lib/encoding](http://github.com/VictoriaMetrics/VictoriaMetrics/lib/encoding) 7.274s

After:
BenchmarkMarshalVarInt64s/up-to-(1<<6)-1
BenchmarkMarshalVarInt64s/up-to-(1<<6)-1-10               712990              1443 ns/op        5545.80 MB/s           0 B/op          0 allocs/op
=== RUN   BenchmarkMarshalVarInt64s/up-to-(1<<13)-1
BenchmarkMarshalVarInt64s/up-to-(1<<13)-1
BenchmarkMarshalVarInt64s/up-to-(1<<13)-1-10              796993              1475 ns/op        5425.56 MB/s           0 B/op          0 allocs/op
=== RUN   BenchmarkMarshalVarInt64s/up-to-(1<<27)-1
BenchmarkMarshalVarInt64s/up-to-(1<<27)-1
BenchmarkMarshalVarInt64s/up-to-(1<<27)-1-10              673441              1757 ns/op        4552.40 MB/s           2 B/op          0 allocs/op
=== RUN   BenchmarkMarshalVarInt64s/up-to-(1<<63)-1
BenchmarkMarshalVarInt64s/up-to-(1<<63)-1
BenchmarkMarshalVarInt64s/up-to-(1<<63)-1-10              439021              2738 ns/op        2921.60 MB/s           8 B/op          0 allocs/op

====

BTW, c version is faster 40 times than golang version.
So go assemly version is on the way.
I will commit faster version next time.

### CODE REVIEW

**Comment by ahfuzhang** [comment]
> @ahfuzhang , thanks for the optimization! It would be great optimizing the case for small integers with up to `1<<6-1` values, since this case is very common in real world. According to the provided benchmark results, the performance for this case has been dropped from 11.7Gbytes/sec to 5.5Gbytes/sec.

because I don't add fast path for 1 byte marshal.
Wait a moment pls, I add it and test again.

**Comment by ahfuzhang** [comment]
New bechmark:

=== RUN   BenchmarkMarshalVarInt64s/up-to-(1<<6)-1
BenchmarkMarshalVarInt64s/up-to-(1<<6)-1
BenchmarkMarshalVarInt64s/up-to-(1<<6)-1-10              1795152               659.3 ns/op      12133.53 MB/s          0 B/op          0 allocs/op
=== RUN   BenchmarkMarshalVarInt64s/up-to-(1<<13)-1
BenchmarkMarshalVarInt64s/up-to-(1<<13)-1
BenchmarkMarshalVarInt64s/up-to-(1<<13)-1-10              673744              1614 ns/op        4958.10 MB/s           0 B/op          0 allocs/op
=== RUN   BenchmarkMarshalVarInt64s/up-to-(1<<27)-1
BenchmarkMarshalVarInt64s/up-to-(1<<27)-1
BenchmarkMarshalVarInt64s/up-to-(1<<27)-1-10              645064              1742 ns/op        4593.73 MB/s           2 B/op          0 allocs/op
=== RUN   BenchmarkMarshalVarInt64s/up-to-(1<<63)-1
BenchmarkMarshalVarInt64s/up-to-(1<<63)-1
BenchmarkMarshalVarInt64s/up-to-(1<<63)-1-10              435181              2515 ns/op        3180.43 MB/s           8 B/op          0 allocs/op
PASS
ok      [github.com/VictoriaMetrics/VictoriaMetrics/lib/encoding](http://github.com/VictoriaMetrics/VictoriaMetrics/lib/encoding) 5.385s

And new code is:
```go
func MarshalVarInt64s(dst []byte, vs []int64) []byte {
	for _, v := range vs {
		n := uint64((v << 1) ^ (v >> 63))
		if n < (1 << 7) {
			dst = append(dst, byte(n))
			continue
		}
		switch (64 - bits.LeadingZeros64(n>>1)) / 7 {
		case 0:
			dst = append(dst, byte(n))
		case 1:
			dst = append(dst, byte(n|0x80), byte(n>>7))
		case 2:
			dst = append(dst, byte(n|0x80), byte((n>>7)|0x80), byte(n>>14))
		case 3:
			dst = append(dst, byte(n|0x80), byte((n>>7)|0x80), byte((n>>14)|0x80), byte(n>>21))
		case 4:
			dst = append(dst, byte(n|0x80), byte((n>>7)|0x80), byte((n>>14)|0x80), byte((n>>21)|0x80), byte(n>>28))
		case 5:
			dst = append(dst, byte(n|0x80), byte((n>>7)|0x80), byte((n>>14)|0x80), byte((n>>21)|0x80), byte(n>>28|0x80), byte(n>>35))
		case 6:
			dst = append(dst, byte(n|0x80), byte((n>>7)|0x80), byte((n>>14)|0x80), byte((n>>21)|0x80), byte(n>>28|0x80), byte(n>>35|0x80), byte(n>>42))
		case 7:
			dst = append(dst, byte(n|0x80), byte((n>>7)|0x80), byte((n>>14)|0x80), byte((n>>21)|0x80), byte(n>>28|0x80), byte(n>>35|0x80), byte(n>>42|0x80), byte(n>>49))
		case 8:
			dst = append(dst, byte(n|0x80), byte((n>>7)|0x80), byte((n>>14)|0x80), byte((n>>21)|0x80), byte(n>>28|0x80), byte(n>>35|0x80), byte(n>>42|0x80), byte(n>>49|0x80), byte(n>>56))
		case 9:
			fallthrough
		default:
			dst = append(dst, byte(n|0x80), byte((n>>7)|0x80), byte((n>>14)|0x80), byte((n>>21)|0x80), byte(n>>28|0x80), byte(n>>35|0x80), byte(n>>42|0x80), byte(n>>49|0x80), byte(n>>56|0x80), byte(n>>63))
		}
	}
	return dst
}
```

**Comment by ahfuzhang** [comment]
And I make `UnmarshalVarInt64s` 28% faster.

Before:
=== RUN   BenchmarkUnmarshalVarInt64s/up-to-(1<<6)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<6)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<6)-1-10            1579142               793.7 ns/op      10079.69 MB/s          0 B/op       0 allocs/op
=== RUN   BenchmarkUnmarshalVarInt64s/up-to-(1<<13)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<13)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<13)-1-10            568491              1816 ns/op        4404.86 MB/s           0 B/op       0 allocs/op
=== RUN   BenchmarkUnmarshalVarInt64s/up-to-(1<<27)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<27)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<27)-1-10            231183              4840 ns/op        1652.94 MB/s           0 B/op       0 allocs/op
=== RUN   BenchmarkUnmarshalVarInt64s/up-to-(1<<63)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<63)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<63)-1-10            124256              8935 ns/op         895.37 MB/s           0 B/op       0 allocs/op

After:
BenchmarkUnmarshalVarInt64s/up-to-(1<<6)-1-10            1543092               796.8 ns/op      10039.85 MB/s          0 B/op          0 allocs/op
=== RUN   BenchmarkUnmarshalVarInt64s/up-to-(1<<13)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<13)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<13)-1-10           1000000              1123 ns/op        7125.49 MB/s           0 B/op          0 allocs/op
=== RUN   BenchmarkUnmarshalVarInt64s/up-to-(1<<27)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<27)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<27)-1-10            282601              3802 ns/op        2104.30 MB/s           0 B/op          0 allocs/op
=== RUN   BenchmarkUnmarshalVarInt64s/up-to-(1<<63)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<63)-1
BenchmarkUnmarshalVarInt64s/up-to-(1<<63)-1-10            179688              6460 ns/op        1238.30 MB/s           0 B/op          0 allocs/op

Code is:
```go
// UnmarshalVarInt64s unmarshals len(dst) int64 values from src to dst
// and returns the remaining tail from src.
func UnmarshalVarInt64s(dst []int64, src []byte) ([]byte, error) {
	idx := uint(0)
	for i := range dst {
		if idx >= uint(len(src)) {
			return nil, fmt.Errorf("cannot unmarshal varint from empty data")
		}
		c := src[idx]
		idx++
		if c < 0x80 {
			// Fast path
			v := int8(c>>1) ^ (int8(c<<7) >> 7) // zig-zag decoding without branching.
			dst[i] = int64(v)
			continue
		}
		if idx < uint(len(src)) && src[idx] < 0x80 {
			// Fast path, for 2 bytes
			n := uint64(c&0x7f) | (uint64(src[idx]&0x7f) << 7)
			dst[i] = int64(n>>1) ^ (int64(n<<63) >> 63)
			idx++
			continue
		}
		j := idx + 1
		for ; j < uint(len(src)); j++ { // find end loc
			if src[j] < 0x80 {
				break
			}
		}
		if j-idx > 10 {
			return nil, fmt.Errorf("cannot unmarshal varint, buffer too long, len=%d", j-idx)
		}
		dst[i] = unmarshalVarInt64ForOne(src[idx-1 : j+1])
		idx = j + 1
	}
	return src[idx:], nil
}

func unmarshalVarInt64ForOne(buf []byte) int64 {
	var n uint64
	switch len(buf) {
	case 1:
		n = uint64(buf[0] & 0x7F)
	case 2:
		n = uint64(buf[0]&0x7F) | (uint64(buf[1]&0x7F) << 7)
	case 3:
		n = uint64(buf[0]&0x7F) | (uint64(buf[1]&0x7F) << 7) | (uint64(buf[2]&0x7F) << 14)
	case 4:
		n = uint64(buf[0]&0x7F) | (uint64(buf[1]&0x7F) << 7) | (uint64(buf[2]&0x7F) << 14) | (uint64(buf[3]&0x7F) << 21)
	case 5:
		n = uint64(buf[0]&0x7F) | (uint64(buf[1]&0x7F) << 7) | (uint64(buf[2]&0x7F) << 14) | (uint64(buf[3]&0x7F) << 21) | (uint64(buf[4]&0x7F) << 28)
	case 6:
		n = uint64(buf[0]&0x7F) | (uint64(buf[1]&0x7F) << 7) | (uint64(buf[2]&0x7F) << 14) | (uint64(buf[3]&0x7F) << 21) | (uint64(buf[4]&0x7F) << 28) | (uint64(buf[5]&0x7F) << 35)
	case 7:
		n = uint64(buf[0]&0x7F) | (uint64(buf[1]&0x7F) << 7) | (uint64(buf[2]&0x7F) << 14) | (uint64(buf[3]&0x7F) << 21) | (uint64(buf[4]&0x7F) << 28) | (uint64(buf[5]&0x7F) << 35) | (uint64(buf[6]&0x7F) << 42)
	case 8:
		n = uint64(buf[0]&0x7F) | (uint64(buf[1]&0x7F) << 7) | (uint64(buf[2]&0x7F) << 14) | (uint64(buf[3]&0x7F) << 21) | (uint64(buf[4]&0x7F) << 28) | (uint64(buf[5]&0x7F) << 35) | (uint64(buf[6]&0x7F) << 42) | (uint64(buf[7]&0x7F) << 49)
	case 9:
		n = uint64(buf[0]&0x7F) | (uint64(buf[1]&0x7F) << 7) | (uint64(buf[2]&0x7F) << 14) | (uint64(buf[3]&0x7F) << 21) | (uint64(buf[4]&0x7F) << 28) | (uint64(buf[5]&0x7F) << 35) | (uint64(buf[6]&0x7F) << 42) | (uint64(buf[7]&0x7F) << 49) | (uint64(buf[8]&0x7F) << 56)
	case 10:
		n = uint64(buf[0]&0x7F) | (uint64(buf[1]&0x7F) << 7) | (uint64(buf[2]&0x7F) << 14) | (uint64(buf[3]&0x7F) << 21) | (uint64(buf[4]&0x7F) << 28) | (uint64(buf[5]&0x7F) << 35) | (uint64(buf[6]&0x7F) << 42) | (uint64(buf[7]&0x7F) << 49) | (uint64(buf[8]&0x7F) << 56) | (uint64(buf[9]&0x7F) << 63)
	default:
		panic("impossible error: buf length must be 1 to 10")
	}
	return int64(n>>1) ^ (int64(n<<63) >> 63)
}

```

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@ahfuzhang , thanks for the performance optimization!

**Pull request merged**
