### PR TITLE
vmrule: include cluster info in alert CPUThrottlingHigh

### PR DESCRIPTION
**Pull request by iamtienng**

### CODE REVIEW

**Comment by zekker6** [comment]
Hello @iamtienng
Alerting rules which was changed in this PR is only used as a part of vmalert's test suite to validate the parser. Is this a correct change, or it was intended to actually change something else?

**Comment by iamtienng** [comment]
> Hello @iamtienng Alerting rules which was changed in this PR is only used as a part of vmalert's test suite to validate the parser. Is this a correct change, or it was intended to actually change something else?

Hi @zekker6 
This is a correct change. The cluster information was already added to Victoria Metrics helm chart and Prometheus Rules:
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/rules/kubernetes-resources.yaml
https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/kubernetesControlPlane-prometheusRule.yaml
I realized it hasn't been included in this section of Victoria Metrics yet so I created this pull request.

Further more, there are many contexts where there is only one VM Server and many VM Agents from another clusters send metrics to the VM Server one. This information helps us to determine the cluster that firing the alert quicker.

**Review by zekker6 — APPROVED** [review]

**Comment by zekker6** [comment]
@iamtienng Could you please [sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) your commits to get this merged?

**Comment by zekker6** [comment]
Closing this one as #5956 superseded the changes

**Pull request closed without merging**
