### PR TITLE
vmui: add select of Tenant ID

### PR DESCRIPTION
**Pull request by Loori-R**
**Add select of Tenant ID**
You can choose from a list of options.
The selected `tenantID` value is saved in the URL params. Upon page load, the `tenantID` value from the URL params is applied if it exists, else from the `server URL`

### CODE REVIEW

**Comment by Loori-R** [comment]
@valyala, there is no feature request

**Comment by valyala** [comment]
@Loori-R , could you update the following aspects of this feature?

- To move the tenantID selector to the top header of vmui.
- To show the tenantID selector only if the following conditions are met simulatenously:
   * vmui is loaded from the url containing tenantID, e.g. from `/select/<tenantID>/[prometheus/]{vmui,graph}/` url . The url can differ if `vmui` is loaded via a proxy such as [vmauth](https://docs.victoriametrics.com/vmauth.html), which can use arbitrary different url. In this case the tenantID selector isn't needed.
   * vmui is able to successfully query the list of tenantIDs by requesting the `/admin/tenants?start=...&end=...` url on the selected time range according to https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format . The `/admin/tenants` url can be unavailable for querying if `vmselect` is hidden behind a proxy such as [vmauth](https://docs.victoriametrics.com/vmauth.html).
   * The returned list of tenantIDs contains more than a single entry. There is no sense in showing the selector if only a single tenantID is available.
- The tenantID selector should provide auto-completion support from the list of tenantIDs obtained from `/admin/tenants`
- When user selects the tenantID, then the server url (aka datasource url) should be updated accordingly and all the information displayed on the currently opened page should be re-loaded from the updated server url. The selected tenantID should be stored in the page url, so the url could be copy-n-pasted to another browser window and display the same page for the selected tenant.

**Comment by Loori-R** [comment]
@valyala updated

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Loori-R , could you resolve merge conflicts?

**Comment by Loori-R** [comment]
resolved merge conflicts

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Loori-R , thanks for implementing this feature!

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Pull request merged**
