### PR TITLE
adding vminsert/opentsdb-http

### PR DESCRIPTION
**Pull request by newffy**
Adding OpenTSDB HTTP put api.
It is implemented with `valyala/fasthttp` lib, so needs to be started with `opentsdbHTTPListenAddr` setting

### CODE REVIEW

**Comment by valyala** [comment]
Please use `net/http` instead of `fasthttp`, since `fasthttp` brings no benefits to VictoriaMetrics due to the following reasons:
1) Comparatively low rate for incoming requests. `fasthttp` excels at 100k+ rps, while highly loaded VictoriaMetrics deals with two order of magnitude lower rps.
2) VictoriaMetrics accepts comparatively big request bodies on data ingestion paths when receiving big batches of data points. `fasthttp` is optimized for small request and response bodies and it doesn't work well with big request bodies.

**Comment by newffy** [comment]
> Please use `net/http` instead of `fasthttp`, since `fasthttp` brings no benefits to VictoriaMetrics due to the following reasons:
> 
> 1. Comparatively low rate for incoming requests. `fasthttp` excels at 100k+ rps, while highly loaded VictoriaMetrics deals with two order of magnitude lower rps.
> 2. VictoriaMetrics accepts comparatively big request bodies on data ingestion paths when receiving big batches of data points. `fasthttp` is optimized for small request and response bodies and it doesn't work well with big request bodies.

we have relatively small bodies (1-25 points per request) and ~ 60k req/s. That's why we chose `fasthttp`. But we also have separate `net/http` implementation.
We can contribute merged solution for both `fasthttp` and `net/http` options. Is it worth?

**Comment by valyala** [comment]
> we have relatively small bodies (1-25 points per request) and ~ 60k req/s. That's why we chose fasthttp

Could you measure the difference in CPU usage for your use case between the two implementations?

> We can contribute merged solution for both fasthttp and net/http options. Is it worth?

It would be better providing only a single solution for `net/http`.

**Comment by valyala** [comment]
Manually merged this PR at 5f33fc8e46ae8dba1fa37420f20fae131523d9fe .
@newffy , thanks for the contribution!

**Comment by valyala** [comment]
The PR is available in [v1.26.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Pull request closed without merging**
