### PR TITLE
vmui: improve error message for server response issues

### PR DESCRIPTION
**Pull request by Loori-R**
### Describe Your Changes

Updates error messages for better clarity and guidance on server response issues.

<table>
<tbody>
<tr>
<td>before</td>
<td>Screenshot 2024-04-23 at 20 00 09</td>
</tr>
<tr>
<td>after</td>
<td>Screenshot 2024-04-23 at 20 00 12</td>
</tr>
</tbody>
</table>

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Comment by hagen1778** [comment]
@Loori-R would you mind adding a line to changelog?

**Review by dmitryk-dk — APPROVED** [review]
nit: only CHANGELOG missed

**Comment by Loori-R** [comment]
updated CHANGELOG

**Review by dima-vm — APPROVED** [review]

**Review by hagen1778 — APPROVED** [review]
LGTM

**Pull request merged**
