### PR TITLE
Add flag to vminsert to disable rerouting when some of storage nodes are unavailable

### PR DESCRIPTION
**Pull request by Muxa1L**
Adds flag -disableReroutingOnUnavailable to vminsert to disable rerouting of timeseries from currently unavailable storage nodes. 
It completely stops ingestion to victoriametrics cluster if any of storage nodes are unavailable, but it also prevents creation of large amounts of new timeseries across cluster, which sometimes may lead to domino effect

### CODE REVIEW

**Comment by hagen1778** [comment]
Hello @Muxa1L and thanks for pull request!
If vminsert won't redirect data that would mean this data won't be available for querying. As result, recording/alerting rules will produce false results. How do you deal with that?

**Comment by Muxa1L** [comment]
@hagen1778 They will wait in queue on writing agents, prometheus, etc. In ours install we have a cluster of buffering vmagents plus our internal service to pass all metrics through kafka. 
Right now when one of storage nodes becomes unavailable (for different reasons - oom, host machine reboot, etc) vminsert starts rerouting tss of this storage node to other. As we know registration of new tss is very slow an resource consuming task. Which may lead to more OOM's across whole cluster. Which leads to more reroutes and so on.
If storage node was unavailable due to OOM - it restarts very quickly, and cluster returns to normal processing speed quicker.
Some tests. Ingestion rate when one of storage nodes restarts with rerouting
image
And without rerouting
image

**Comment by hagen1778** [comment]
Thanks for response @Muxa1L !
Does it mean that in both cases alerting/recording rules produce no results? Or you don't use alerting/recording rules?
Have you checked recommendations here https://docs.victoriametrics.com/cluster-victoriametrics/#improving-re-routing-performance-during-restart ?

**Comment by Muxa1L** [comment]
@hagen1778  
We use alerting/recording rules. And in case of default vminsert-with-rerouting they will produce no results for longer time, as you can see of ingestion rate graphs. We also use -datasource.lookback for vmalerts to mitigate such cases.
Given recommendations are only applicable for controlled restarts, not for unexpected ones. For updates we use "Minimum downtime strategy" btw. 
Also we have two parallel mirror clusters, and delays on one cluster do not affect us. 

One more advantage of disabled rerouting is that we dont have a lot of duplicates of same tss across cluster. Which helps a lot when exporting data. And less storage is used for indices.

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Muxa1L , please see the follow-up commit 63a43331a3e330b0e809fcc9feb0f0a10c298647 , which documents the `-disableReroutingOnUnavailable` command-line flag.

**Comment by Muxa1L** [comment]
> @Muxa1L , please see the follow-up commit [63a4333](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/63a43331a3e330b0e809fcc9feb0f0a10c298647) , which documents the `-disableReroutingOnUnavailable` command-line flag.

ah.. Forgot about docs =( Thanks!

**Comment by xiaozongyang** [comment]
If one vmstorage node is unavailable for a long peorid, all incomming writing requests will wait for the down node recover. So concurrency is always increaing, when the number of wating goroutines reach the concurrency limit, the vminsert instance can't process requests anymore.
Do we need a timeout about this flag?

ping @Muxa1L @valyala

**Pull request merged**
