### PR TITLE
lib/storage:change  table.AddRows to find single partition and split rows at one-for

### PR DESCRIPTION
**Pull request by yqylovy**
modify the `table.AddRows` method：the new implement directly split partitions，so in mulit-partition case，it do less work.

### CODE REVIEW

**Comment by valyala** [comment]
Thanks for the pull request, @yqylovy !

New data is usually written into the latest partition, so this case must be optimized the most. Multi-partition writes are quite rare - they occur once a month for a short period of time on partition boundaries, so this case can be left unoptimized.

What is your use case?

**Comment by yqylovy** [comment]
Hi！Actually，I don't have a user case. I just want to get more detail about VictoriaMetrics,so I look into it's code and think this part could be optimized.

**Comment by valyala** [comment]
Could you look at [failed test](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/190/checks?check_run_id=235926134#step:6:2179)?

> BUG: row &{TSID:{MetricGroupID:16395529084365668360 JobID:402053291 InstanceID:1682632848 MetricID:1569425359815930749} Timestamp:9423633169 Value:1.3791830075883348e+06 PrecisionBits:4} has Timestamp outside partition "/home/runner/work/VictoriaMetrics/VictoriaMetrics/lib/storage/TestStorageDeleteMetrics/data/small/1970_03" range [1970-03-01 00:00:00 +0000 UTC - 1970-03-31 23:59:59.999 +0000 UTC]

After that I'll verify ingestion performance after applying the patch.

**Comment by yqylovy** [comment]
@valyala I fix it , but check still failed.

**Comment by tenmozes** [comment]
it's failed because of coverage job, looks like same issue as https://github.com/codecov/codecov-action/issues/22

**Comment by tenmozes** [comment]
looks like github actions problem, here is discussion https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/m-p/30678

**Comment by yqylovy** [comment]
don't know what to do, so I need to wait for fix?

**Comment by tenmozes** [comment]
you don't need to fix build :) this is my problem just keep you posted about an issue, thanks for contribution

**Comment by valyala** [comment]
Closing this PR as stale.
@yqylovy , feel free resurrecting this patch while keeping in mind that the patch mustn't hurt performance for common case.

**Pull request closed without merging**
