### PR TITLE
docs: removed code-style highlighting for commanad-line flags of VM components

### PR DESCRIPTION
**Pull request by denisgolius**
It should render a description of the cmd-flags with wrapping as on the VictoriaLogs page https://docs.victoriametrics.com/victorialogs/#list-of-command-line-flags

### CODE REVIEW

**Comment by hagen1778** [comment]
> It should render a description of the cmd-flags with wrapping as on the VictoriaLogs page https://docs.victoriametrics.com/victorialogs/#list-of-command-line-flags

Why?

**Comment by denisgolius** [comment]
> > It should render a description of the cmd-flags with wrapping as on the VictoriaLogs page https://docs.victoriametrics.com/victorialogs/#list-of-command-line-flags
> 
> Why?

Because now the description of flags goes beyond the page window in the code tag, and you have to scroll the code field itself, which is very inconvenient when copying or reading it.

**Comment by hagen1778** [comment]
@denisgolius this PR was reverted in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/6aaf1768f4b093eaa228771c8a368f8d677d33fb as it breaks the code formatting:
image

**Comment by valyala** [comment]
@hagen1778 , it would be great to specify the reason for revert in the description for the `revert` commits such as 6aaf1768f4b093eaa228771c8a368f8d677d33fb . This will help investigating commit history and understanding why the particular commit has been reverted.

**Pull request merged**
