### PR TITLE
do not print redundant error logs when failed to scrape consul or no…

### PR DESCRIPTION
**Pull request by Haleygo**
…mad target

```
 2023-10-26T08:14:29.694Z	error	VictoriaMetrics/lib/promscrape/discovery/consul/api.go:178	cannot find X-Consul-Index header in response from "/v1/health/service/dev-env-archive-procore-addon?dc=dev-env-us-east-1&stale&index=29461416&wait=525s"
 2023-10-26T08:14:29.694Z	error	VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:261	cannot obtain Consul serviceNodes for serviceName="dev-env-airtable-watcher-addon" from "http://consul.dev-env.int:8500": cannot perform blocking Consul API request at "/v1/health/service/dev-env-airtable-watcher-addon?dc=dev-env-us-east-1&stale&index=30469793&wait=525s": unexpected status code returned from "http://consul.dev-env.int:8500/v1/health/service/dev-env-airtable-watcher-addon?dc=dev-env-us-east-1&stale&index=30469793&wait=525s": 504; expecting 200; response body: ""
 2023-10-26T08:14:29.694Z	error	VictoriaMetrics/lib/promscrape/discovery/consul/api.go:178	cannot find X-Consul-Index header in response from "/v1/health/service/dev-env-csv-prefill-addon?dc=dev-env-us-east-1&stale&index=27196058&wait=525s"
 2023-10-26T08:14:29.694Z	error	VictoriaMetrics/lib/promscrape/discovery/consul/api.go:178	cannot find X-Consul-Index header in response from "/v1/health/service/dev-env-auto-create-revision-addon?dc=dev-env-us-east-1&stale&index=33517349&wait=525s"
 2023-10-26T08:14:29.694Z	error	VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:261	cannot obtain Consul serviceNodes for serviceName="dev-env-csv-prefill-addon" from "http://consul.dev-env.int:8500": cannot perform blocking Consul API request at "/v1/health/service/dev-env-csv-prefill-addon?dc=dev-env-us-east-1&stale&index=27196058&wait=525s": unexpected status code returned from "http://consul.dev-env.int:8500/v1/health/service/dev-env-csv-prefill-addon?dc=dev-env-us-east-1&stale&index=27196058&wait=525s": 504; expecting 200; response body: ""
 2023-10-26T08:14:29.694Z	error	VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:261	cannot obtain Consul serviceNodes for serviceName="dev-env-auto-create-revision-addon" from "http://consul.dev-env.int:8500": cannot perform blocking Consul API request at "/v1/health/service/dev-env-auto-create-revision-addon?dc=dev-env-us-east-1&stale&index=33517349&wait=525s": unexpected status code returned from "http://consul.dev-env.int:8500/v1/health/service/dev-env-auto-create-revision-addon?dc=dev-env-us-east-1&stale&index=33517349&wait=525s": 504; expecting 200; response body: ""
 2023-10-26T08:14:29.694Z	error	VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:261	cannot obtain Consul serviceNodes for serviceName="dev-env-archive-procore-addon" from "http://consul.dev-env.int:8500": cannot perform blocking Consul API request at "/v1/health/service/dev-env-archive-procore-addon?dc=dev-env-us-east-1&stale&index=29461416&wait=525s": unexpected status code returned from "http://consul.dev-env.int:8500/v1/health/service/dev-env-archive-procore-addon?dc=dev-env-us-east-1&stale&index=29461416&wait=525s": 504; expecting 200; response body: ""
 2023-10-26T08:14:29.694Z	error	VictoriaMetrics/lib/promscrape/discovery/consul/api.go:178	cannot find X-Consul-Index header in response from "/v1/health/service/dev-env-forbid-discard-revision-addon?dc=dev-env-us-east-1&stale&index=33512745&wait=525s"
 2023-10-26T08:14:29.694Z	error	VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:261	cannot obtain Consul serviceNodes for serviceName="dev-env-jira-addon" from "http://consul.dev-env.int:8500": cannot perform blocking Consul API request at "/v1/health/service/dev-env-jira-addon?dc=dev-env-us-east-1&stale&index=36132129&wait=525s": unexpected status code returned from "http://consul.dev-env.int:8500/v1/health/service/dev-env-jira-addon?dc=dev-env-us-east-1&stale&index=36132129&wait=525s": 504; expecting 200; response body: ""
```

### CODE REVIEW

**Comment by zekker6** [comment]
If I understand this correctly, in this case targets might be missing in case Consul or Nomad would return `!= 200` status code, but logs will be empty and it will be hard to debug by user.
Maybe we should introduce rate limitting or flag to hide such logs to give user more control over this?

**Comment by Haleygo** [comment]
> in this case targets might be missing in case Consul or Nomad would return `!= 200` status code, but logs will be empty and it will be hard to debug by user

@zekker6 Hmm, I'm not aware of that.
But the interesting thing is that consul lib accutually just [drops the error](https://github.com/hashicorp/consul/blob/1806bcb38c3de97885ac48e7d8801a5a13e91d6b/api/api.go#L1134) and prometheus uses [it](https://github.com/prometheus/prometheus/blob/05356e76de82724ebf104457cb4cf1e91920621e/discovery/consul/consul.go#L383).

**Review by zekker6 — APPROVED** [review]

**Comment by valyala** [comment]
FYI, this pull request has been included in [vmagent v1.93.7 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.7).

**Comment by valyala** [comment]
FYI, this pull request has been included in [vmagent v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html)

**Pull request merged**
