### PR TITLE
Document maxConcurrentRequests default

### PR DESCRIPTION
**Pull request by nemobis**

### CODE REVIEW

**Comment by nemobis** [comment]
It's a bit weird that increasing from 4 to 8 CPUs gives you the same concurrency by default, but at least with clearer docs people can make their choices. :)

**Comment by hagen1778** [comment]
Thanks for PR! 

I assume, the relation between number of CPUs and maxConcurrentRequests was mistakenly propagated by the Grafana dashboard for cluster VM. So I addressed this here https://github.com/VictoriaMetrics/VictoriaMetrics/commit/f6208965cec732ddae75912f5a820cc3311e435d

I think adding the details of picking the right default value to the flag is unnecessary. From user perspective, it shouldn't be hard to understand. The user should see that limit is reached and follow the recommendations from docs or dashboard tooltip about what to do next. If user decides to increase the limit, they should to adjust the flag, not the number of CPUs.

**Comment by nemobis** [comment]
Thanks for the review.

Il 31/10/23 17:10, Roman Khavronenko ha scritto:
> I assume, the relation between number of CPUs and maxConcurrentRequests 
> was mistakenly propagated by the Grafana dashboard for cluster VM.

No, I've never looked at that. The description came from the 
getDefaultMaxConcurrentRequests function, isn't it the relevant one?
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/aade16f534ddcbc9e2c174d85f34ed763799ee9f/app/vmselect/main.go#L46

Yes I could wait for my loads to hit the limits and adjust the 
configuration accordingly, but I was trying to plan for the limits 
beforehand while making some changes to a cluster for an unusual load 
(data import/export).

**Comment by hagen1778** [comment]
> Yes I could wait for my loads to hit the limits and adjust the
configuration accordingly, but I was trying to plan for the limits
beforehand while making some changes to a cluster for an unusual load
(data import/export).

This is not exactly what I wanted to say. It is very likely that user can't plan beforehand without testing the expected workload first. Simply because it is impossible to tell what would be the number of concurrent selects without knowing their complexity and latency with the given hardware. So user should try running tests in the first place, and then adjust the limits accordingly. Once limits are hit during the tests, VM should provide enough of information about the issue and recommendation how to fix it:
* if vmselect is saturated, then bump the CPUs
* if it is just limit is hit, bump the limit
User shouldn't do the first to achieve the second. Hence, no point in explaining how limit depends on the number of CPUs.

**Comment by nemobis** [comment]
Still, I can't increase the limit from the default if I don't know what 
the default is.

**Pull request closed without merging**
