### PR TITLE
optimized code 

### PR DESCRIPTION
**Pull request by jiangxinlingdu**
optimized code ,because only the first error,so no need var errors []error

### CODE REVIEW

**Comment by waldoweng** [comment]
you have change the logic. the original logic will run through all block, after your modification it will be short-circuited by the first error

**Comment by jiangxinlingdu** [comment]
> you have change the logic. the original logic will run through all block, after your modification it will be short-circuited by the first error



> you have change the logic. the original logic will run through all block, after your modification it will be short-circuited by the first error

not affect logic

**Comment by valyala** [comment]
@jiangxinlingdu , thanks for the contribution!

**Comment by valyala** [comment]
@jiangxinlingdu , there was a small typo in the PR. The typo has been fixed in 776b7bc9f80c98cc8ce8185828d5eb5a3f4612b2 .

**Pull request merged**
