### PR TITLE
Vmalert tests

### PR DESCRIPTION
**Pull request by hagen1778**
See commits description

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
See failing test for i386
```
?   	github.com/VictoriaMetrics/VictoriaMetrics/app/vmalert/tpl	[no test files]
Error: app/vmalert/templates/template_test.go:86:33: cannot use 1679055557691 (untyped int constant) as int value in argument to formatting (overflows)
```

**Comment by hagen1778** [comment]
> See failing test for i386

that's old failing test. should have been addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3975/commits/c01ac4f19df08ae94c72f68ebd81e104333987e0

**Review by zekker6 — APPROVED** [review]

**Review by dmitryk-dk — APPROVED** [review]
LGTM!

**Pull request merged**
