### PR TITLE
make: add goimports task

### PR DESCRIPTION
**Pull request by zekker6**
Adds task to fix imports formatting inplace.
Formats imports into:
- standard library
- external libraries
- local packages based on github.com/VictoriaMetrics/VictoriaMetrics prefix

Note that this PR does not apply new formatting.

### CODE REVIEW

**Review by hagen1778 — APPROVED** [review]
I like it!

**Comment by hagen1778** [comment]
@zekker6 I tried the [patch](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4582/commits/4aa03dd85e38631fa9a125f7b41af3e5527a398a) locally and formatting isn't applied for changed files (committed or not). Where should I look?

**Comment by zekker6** [comment]
> @zekker6 I tried the [patch](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4582/commits/4aa03dd85e38631fa9a125f7b41af3e5527a398a) locally and formatting isn't applied for changed files (committed or not). Where should I look?

@hagen1778 Could you please try on the latest version?
Previously, it was only looking for staged changes which was quite confusing as you can see. I've updated it to check for all(staged and untracked) uncommited changes.

**Review by hagen1778 — APPROVED** [review]
Nice!

**Pull request merged**
