### PR TITLE
add release-vmutils-arm64,release-vmutils-arm64 make targets

### PR DESCRIPTION
**Pull request by Legogris**

### CODE REVIEW

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Legogris , thanks for the contribution!

**Comment by Legogris** [comment]
@valyala And thank you! I realized one thing now; the binaries for amd64 are named e.g. `vmagent{-prod}`, with arm64 being `vmagent-arm64{-prod}`, and that is also the case with the archived binaries here.

To not need to have inconsistent name patterns for different architectures (which needs to be taken into consideration in any deployment/provisioning scripts), it'd IMO be much better to have the same pattern, either:
1.  `vmagent-arm64{-prod}`/`vmagent-arm64{-prod}`
2.  `vmagent{-prod}` for both

if you agree and have a preference I can make a pr for that

**Comment by valyala** [comment]
Agreed that the `prod` suffix must be in the end of binary name. @ledeuns , could you post a follow-up pull request that fixes this?

**Comment by valyala** [comment]
Oops, I meant sticking to the second option then. This should simplify maintaining cross-platform wrapper scripts for victoriametrics binaries.

**Comment by valyala** [comment]
Binaries must be renamed before putting them into `tar.gz` archive.

**Pull request merged**
