### PR TITLE
vmui: add metric relabel debug

### PR DESCRIPTION
**Pull request by Loori-R**
Add Relabeling Playground into VMUI (only [metric-relabel-debug](http://127.0.0.1:8428/metric-relabel-debug))

#3807

localhost_3000_d_wNf0q_kZk_victoriametrics_orgId=1 (1)

### CODE REVIEW

**Comment by valyala** [comment]
@Loori-R , could you resolve merge conflicts for this pull request?

**Review by hagen1778 — APPROVED** [review]
Looks great!
One thing I'd change is preloading of example by default.

**Comment by Loori-R** [comment]
> Looks great! One thing I'd change is preloading of example by default.


@hagen1778, by default the fields are empty, an example is loaded when you press the "Try example" button.

**Comment by hagen1778** [comment]
> @hagen1778, by default the fields are empty, an example is loaded when you press the "Try example" button.

Yes, I 've seen that. But it took a while for me to see that button and load the example. WOuld be great, if it was already pre-loaded.

**Pull request merged**
