### PR TITLE
Change default value of '-remoteWrite.queues' to cgroup.AvailableCPUs * 2

### PR DESCRIPTION
**Pull request by xiaozongyang**
# Overview
Default value of vmagent option '-remotewrite.queues' is 4 and default
size of vmagent ScheudleUnmarshalWorkers is number of CPUs, when available
CPUs is much greater than 4, e.g 32, worker are competing push queues
which will increase scrape interval and may cause scrape timeout.

# Background & Motivation
We have a vmagnet deployed in k8s pod which consumes 32 cores CPU and scrapes 24k active targets. We found that scraping of kube-state-metrics timeout with error message `context deadline exceeded` and scrape duration is about 45s shown in vmagent targets page. When we request the kube-state-metrics endpoint in vmagent container, it costs nearly 1s. 

wecom-temp-a8bb0bb843d5b97efde5468b4ff84f78
wecom-temp-a04c328080e11854961b4492129a48e2

As shown in following picture, when we increase the option `-remoteWrite.queues` from 10 to 64, the scrape duration decreased to 9s. Timeout error disappeared!
wecom-temp-5f154c0fa5340a0c14de437e80af2146

**So we recommend that change the default value of option `-remoteWrite.queues` to 2 * numberOfCPUs to avoid scraping context deadline exceed due to competing push mutex.**

The diff of pprof mutex dump shows that lock competing of function `pendingseries.Push` decreased 50%.

image

# Changes

1. Change default value of vmagent option `-remoteWrite.queues` to `2 * numberOfCPUs`

# Attachments
The pprof mutex and profile dump of vmagent with 10 queues and 64 queues are here. 
[vmagent-pprof.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/6661374/vmagent-pprof.zip)

### CODE REVIEW

**Comment by xiaozongyang** [comment]
TODO fix readme and flag description

**Review by valyala — APPROVED** [review]
LGTM

**Comment by valyala** [comment]
@xiaozongyang , thanks for the contribution!

**Comment by valyala** [comment]
FYI, the optimization for the default value of `-remoteWrite.queues` has been added in [v1.62.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by xiaozongyang** [comment]
@valyala 👍

**Pull request merged**
