### PR TITLE
vmui: improve mobile ui

### PR DESCRIPTION
**Pull request by Loori-R**
Added a logo to the header for mobile.
Improved the usability of selects, pop-up and modal windows on mobile. 
Reduced the height of charts and decreased the margins for mobile.

Frame 7

### CODE REVIEW

**Review by valyala — APPROVED** [review]

**Comment by valyala** [comment]
@Loori-R , could you fix the merge conflict?

**Comment by Loori-R** [comment]
@valyala, merged

**Comment by valyala** [comment]
@Loori-R , thanks for the pull request!

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html).

**Pull request merged**
