### PR TITLE
adding AggregateSeriesLists graphite function

### PR DESCRIPTION
**Pull request by rbizos**
Adding AggregateSeriesLists and its aliases. Reused aggregate logic and divideSeriesList. Facturized divideSeriesLists with the new logic.

### CODE REVIEW

**Comment by rbizos** [comment]
I used the cluster branch to ease my tests but I can cherry-pick on top of master If needed :)

**Review by f41gh7 — COMMENTED** [review]
Looks great, thanks for contribution!

  Could you please add tests for new functions at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmselect/graphite/eval_test.go#L14

**Comment by f41gh7** [comment]
May I ask you to sign commits ( squad and force may be required) and updates changelog at docs?

**Comment by rbizos** [comment]
I thought I had done it before, sorry about that, it should be good now :)

**Comment by f41gh7** [comment]
Thanks for contribution!

**Comment by valyala** [comment]
@rbizos , please see the follow-up commit e4eccd7074da09daf8aa6db6007aaf9fb2ffd049 .

**Comment by rbizos** [comment]
Thanks, sorry for this mistake

**Pull request merged**
