### PR TITLE
vmstorage: fix panic caused by pushing metrics during graceful shutting down

### LINKED ISSUE #5548: vmstorage: panic when graceful shutdown caused by push metrics
### Describe the bug

showdown
panic

I found that during the graceful shutdown of a vmstorage node, a panic was caused by pushing metrics。I can fix this bug. I will submit a Merge Request later to help VictoriaMetrics resolve this issue.

### To Reproduce

None

### Version

vmstorage-20231101-230002-tags-v1.93.7-cluster-0-g1415cd7cd

### Logs

No response

### Screenshots

No response

### Used command-line flags

No response

### Additional information

No response

### PR DESCRIPTION
**Pull request by zhdd99**
Fix #5548

### CODE REVIEW

**Review by hagen1778 — APPROVED** [review]
LGTM! Thanks for the fix!

**Comment by hagen1778** [comment]
Please see the follow-up https://github.com/VictoriaMetrics/VictoriaMetrics/commit/2a7207f38ace1a40e87330508cec9b4e6e26a59b

**Comment by valyala** [comment]
FYI, see the follow-up commit be509b39951efbc40dca5eb707a8917132801ce6 , which fixes a race when metrics could be collected from already destroyed services such as `storage.Storage` by background goroutine after returning from `storage.Stop()`. The commit waits while the background goroutine is stopped before returning from `storage.Stop()`.

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.87.13 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.13).

**Comment by valyala** [comment]
FYI, this pull request has been included in [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html).

**Pull request merged**
