### PR TITLE
cluster: Fix inconsistent error handling in Storage.AddRows()

### PR DESCRIPTION
**Pull request by rtm0**
This is a cluster version of PR #6583. Please review together.

### Checklist

The following checks are **mandatory**:

- [x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

### CODE REVIEW

**Review by f41gh7 — APPROVED** [review]
LGTM

**Comment by f41gh7** [comment]
Please reflect changes at changelog.md file

**Comment by rtm0** [comment]
Updated changelog

**Comment by f41gh7** [comment]
Thanks for the PR, but there is no need to additional changes to the cluster branch.

All changes from master branch back-ported to the other branches by members of VictoriaMetrics team.

**Pull request closed without merging**
